### ISSUE TITLE
Add utf-8 validation when parsing strings.

### ISSUE THREAD

**Issue by mmjdotdk** [json-c/json-c#122]
php -r 'var_dump(json_decode("\"\xff\""));'
string(1) "�"

According to the maintainer Remi Collet, the fix for this needs to go in json-c:

https://github.com/remicollet/pecl-json-c/issues/9

Since json is used extensively these days for all kinds of services, this is a rather bad bug. Is there any way we can get this fixed in json-c, so the fix can move upstream to the distros using it?

**Comment by vote539** [comment]
I've been encountering the problem for a while now.  The JSON spec says that JSON is assumed to be UTF-8 encoded, but json-c naively spits out whatever garbage it is handed in functions like `json_object_new_string_len`, producing invalid JSON that causes exceptions when it is interpreted by other JSON parsers elsewhere in my stack.  I think a fix would just involve modifying this function:

https://github.com/json-c/json-c/blob/1e4824a8412c1b785cac3c95c80d3a9fdcf577d4/json_object.c#L144

It already does the work of escaping the first 32 bytes to "\u00xx" sequences and special characters like '"' and '\'.  It shouldn't be hard to add UTF-8 validation in this function as well.  If an invalid UTF-8 byte is encountered, the byte can be replaced by "\uFFFD".

**Comment by dota17** [comment]
Utf-8 validation has been implemented and we can close this issue @hawicz
