### ISSUE TITLE
json_object_from_file cannot accept max_depth

### ISSUE THREAD

**Issue by minaguib** [json-c/json-c#139]
If I currently want to parse a json file while increasing the maximum nesting depth, I'm forced to either:
- Patch JSON_TOKENER_DEFAULT_DEPTH at json-c compile time
- Copy the entire body of json_object_from_file() into my own application , then adjust its internals to manually create a tokener with json_tokener_parse_ex(depth) and use it instead of the vanilla json_tokener_parse() used in it.

I propose, and if you agree, would be happy to submit a patch that:
- Creates a new public function json_object_from_file_ex(const char _filename, struct json_tokener_ tok, enum json_tokener_error *error) - this will have the bulk of the current json_object_from_file() code but will allow an external consumer to supply their own tokener as well as retrieve parsing error code
- Update existing json_object_from_file(const char *filename) to be a very lightweight wrapper around the new json_object_from_file_ex() - maintaining 100% signature and behavior

**Comment by dota17** [comment]
The public function json_object_from_file_ex()  and corresponding testcase have been created in [commit baed998](https://github.com/json-c/json-c/commit/baed9983b30b46cf6685a061632bbc42cec0ce8d). this issue and #166  could be closed. @hawicz

**Comment by hawicz** [comment]
json_object_from_fd_ex() actually, but yes, let's close this now.
