### ISSUE TITLE
Please undeprecate json_object_object_get

### ISSUE THREAD

**Issue by fclairamb** [json-c/json-c#142]
One of the great advantages of using json-c is to have very little code to write. Now with this json_object_object_get deprecation, we have to change:

	int timeout = json_object_get_int(json_object_object_get(request, "timeout"));

to this:

	int timeout;
	{
		json_object * jTimeout;
		if ( json_object_object_get_ex(request, "timeout", & jTimeout) ) {
			timeout = json_object_get_int(jTimeout);
		}
	}

same thing for strings. We cannot do:

    const char * name = json_object_get_string( json_object_object_get(request, "name"));

Sure, it relies on the fact that the API is nice enough to accept NULL object to the `json_object_get_int` and `json_object_get_string` functions.

And sure we can make our own wrapper:

	json_object * json_object_object_get_old(json_object * obj, const char * name) {
		json_object * sub;
		return json_object_object_get_ex(obj, name, & sub) ? sub : NULL;
	}

But I don't understand why you decided to remove something in the API that forces us to write more code.

**Comment by pianohacker** [comment]
I agree; the nested access pattern becomes a lot harder with `json_object_object_get` being deprecated.

**Comment by gchaincl** [comment]
+1

**Comment by ghazel** [comment]
+1

**Comment by IronFox** [comment]
+1

**Comment by Raduh** [comment]
+1

**Comment by megahall** [comment]
+1

**Comment by malaterre** [comment]
+1

**Comment by kYroL01** [comment]
You're completely right! +1

**Comment by cockroach** [comment]
+1

**Comment by skyatua** [comment]
+1

**Comment by whoo** [comment]
+1

**Comment by fclairamb** [comment]
Guys please note this has been done, this function is not deprecated anymore. No need add new comments around it.

**Comment by megahall** [comment]
Hurrah. In that case maybe makes sense for maintainers to resolve close and lock it.

**Comment by hawicz** [comment]
It has been closed since I un-deprecated the function.  If you guys want to keep yammering on, who am I to say you can't? :)

**Comment by megahall** [comment]
Fair enough. For whatever reason normally the pull request submits for a bug appear in the ticket email and people quit replying but in this case it never propagated so that's probably why the users got mixed up. :)

**Comment by robodan** [comment]
When was this un-deprecated?
What release would have it?

The 0.12.1 docs still show it as deprecated.
https://json-c.github.io/json-c/json-c-0.12.1/doc/html/json__object_8h.html#a1345aaf3ee46e9b6185355b733ec362d

I can't find dates for the releases (and I'm new to json-c), so I don't know what release corresponds to the comments above.

**Comment by IronFox** [comment]
Looks like '@deprecated Please use json_object_object_get_ex' was left in the doxygen documentation. Seems harmless though, just use the function. It won't disappear

**Comment by liudf0716** [comment]
+1

**Comment by neofutur** [comment]
The 0.13.1 version still shows it as deprecated. which version do I need to have this fix ? I couldnt find a changelog about that .

**Comment by hawicz** [comment]
0.13.1 is ancient, you should upgrade to 0.15.
However, it is _not_ marked deprecated in that version: https://github.com/json-c/json-c/blob/json-c-0.13.1-20180305/json_object.h#L467, nor even in https://github.com/json-c/json-c/blob/json-c-0.13-20171207/json_object.h#L456

**Comment by reubenhwk** [comment]
+1
