### ISSUE TITLE
RFE / enhancement for full 64-bit signed/unsigned support

### ISSUE THREAD

**Issue by dlethe** [json-c/json-c#143]
I'm simply going to have to make some mods that facilitate handling 64 bit signed and unsigned numbers correctly so there is no loss of precision, especially if javascript is dealing with the numbers.  [For those not familiar with large numbers, javascript converts to float internally so numbers > 53 bits or so are rounded, so all math breaks unless you use special libraries]

Lots of ways to do this, but I hate to reinvent the wheel and get this incorporated into main repository.  

Seeing things like splitting into 2 x 32-bit ints [highorder,low order]
and twitters technique of sending large integers as:
 {"id": 10765432100123456789, "id_str": "10765432100123456789"}   instead of "id": 10765432100123456789 

To indicate the use. If numbers match then no worries, if not, then user knows it is a large integer so they have to work with the '_str' value and use some additional code to convert.

As incorporating this into the library itself touches a lot of code, want to run this by the community and  see if something like json_object_parse_split_uint64, split_int64, and associated tokening logic and such already exists, or if this is something best left out of it.

Thoughts?

**Comment by hawicz** [comment]
#542 added support for uint64_t to json-c, but didn't do anything to address compatibility with javascript.  Defining a "special" serialization format seems like something that should probably sit on top of json-c, rather than implemented inside of it, so I'm closing this issue.
