### ISSUE TITLE
Please introduce soname bump if API changed

### ISSUE THREAD

**Issue by cicku** [json-c/json-c#147]
Postgis built with 0.11 failed to start:

could not load library "/usr/lib64/pgsql/postgis-2.1.so": /usr/lib64/pgsql/postgis-2.1.so: undefined symbol: json_tokener_errors

And next time please bump the soname if API has been changed, this will affect the binary distros since we can't compile endlessly.

Thanks.

**Comment by hawicz** [comment]
soname was bumped a while ago.  Also, a new release (0.13) with that soname is now available.
