### ISSUE TITLE
JSON-C shall not exit on calloc fail.

### ISSUE THREAD

**Issue by d0i** [json-c/json-c#157]
Hi,

Thank you for developing the software.

Linked list in JSON-C exits when calloc fails (linkhash.c:22). I think it's not a polite behavior for a library software. Application software shall be able to handle malloc (or any library) fails gracefully on the application, isn't it?

I appreciate JSON-C can return NULL (namely, on json_object_new_object()) if malloc fails.

Thanks,

Yusuke

**Comment by hawicz** [comment]
Fixed in changeset 2be921d8
