### ISSUE TITLE
while using json-c 0.11, I am facing strange crash issue in json_object_put.

### ISSUE THREAD

**Issue by VishalBemblekar** [json-c/json-c#158]
While using json-c 0.11, I am facing strange crash issue in json_object_put. I am creating json object which is embedded with 2 json array objects and 1 json object, and after processing I am releasing it.
The above process I am doing in a loop with the delay of 200 milliseconds, after around 8000 iterations my application crashes out in json_object_put. When I took the back-trace, it shows the crash in free function due to Segmentation fault. The GDB back-trace is as below.... 

0x000215d0 in free ()
#1  0x00018a20 in lh_table_free (t=0x570a8) at linkhash.c:120
#2  0x00015afc in json_object_object_delete (jso=0x29) at json_object.c:349
#3  0x00015b7c in json_object_put (jso=0x3e588) at json_object.c:153
#4  0x000191f8 in array_list_free (arr=0x53b08) at arraylist.c:50
#5  0x00015550 in json_object_array_delete (jso=0x29) at json_object.c:736
#6  0x00015b7c in json_object_put (jso=0x3e8e8) at json_object.c:153
#7  0x00018a0c in lh_table_free (t=0x52fc0) at linkhash.c:117
#8  0x00015afc in json_object_object_delete (jso=0x29) at json_object.c:349
#9  0x00015b7c in json_object_put (jso=0x530e8) at json_object.c:153

Some more information of frame 1 using GDB
(gdb) frame 1
#1  0x00018a20 in lh_table_free (t=0x570a8) at linkhash.c:120
120             free(t->table);

and the content of table which is causing a crash is

(gdb) p *t->table
$2 = {
  k = 0xffffffff,
  v = 0x0,
  next = 0x0,
  prev = 0x0
}

Please suggest me how to overcome this issue.

Thanks,
Vishal

**Comment by hawicz** [comment]
Without sample code, it's hard to know what's wrong.  If this is still a problem with the current json-c code, please re-open.
