### ISSUE TITLE
json_tokener.c compile error

### ISSUE THREAD

**Issue by BrentHuang** [json-c/json-c#159]
json_tokener.c: In function 'json_tokener_parse_ex':
json_tokener.c:355:6: error: variable 'size' set but not used [-Werror=unused-but-set-variable]
  int size;
      ^
cc1: all warnings being treated as errors

ps:
json-c vesion: json-c-json-c-0.12-20140410

platform: Linux ubuntu 3.13.0-39-generic #66-Ubuntu SMP Tue Oct 28 13:30:27 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

gcc version: gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2

**Comment by dgoujard** [comment]
Same issue with ubuntu 14.10 64bit

**Comment by strk** [comment]
Yep, and CFLAGS can't be set via env variable in either ./configure or make invocations.

**Comment by strk** [comment]
YOu have to manually remove it from Makefile.am.inc

**Comment by rgerhards** [comment]
Which branch is used in that build? I just cloned the repro and tried both master branch and 0.12 and both worked for me.

**Comment by strk** [comment]
It was fixed by 3859e99f50abe11a8dade28efa9ea3d99dfaac11 in json-c-0.12 branch

**Comment by ThomasWaldmann** [comment]
It's not really fixed until you release the fixed version.

**Comment by ThomasWaldmann** [comment]
BTW, 0.11 release works without this issue.

**Comment by hawicz** [comment]
0.12.1 is released, so you should be able build from that tarball, or from the current code off of master, without this error.

**Comment by ThomasWaldmann** [comment]
\o/
