### ISSUE TITLE
Is there a way to append to file?

### ISSUE THREAD

**Issue by bhavyanshu** [json-c/json-c#161]
The default json_object_to_file only writes to the file. I can't find anything related to appending to file. Why not let us open file using fopen in append mode and just provide a function json_object_to_file accepting file pointer as argument or something like that or just provide an optional argument for specifying file modes. Any way would be good.

**Comment by cameronkerrnz** [comment]
This would be very good for logging as JSON, particularly if using the likes of logstash, with its 'jsonlines' input module. This is a requirement for a project I'm working on.
