### ISSUE TITLE
Need a way to specify nesting depth when opening JSON file

### ISSUE THREAD

**Issue by mvbrock** [json-c/json-c#166]
The json_object_from_file() doesn't allow the user to specify the max nesting depth. Would be nice to have maybe a json_object_from_file_ex() with options like that for the internal tokener. Obviously I can just open up the file contents into a string buffer and tokenize it myself :).

**Comment by harkue** [comment]
duplicate with #139

**Comment by hawicz** [comment]
See commit baed998 for json_object_from_fd_ex().
