### ISSUE TITLE
Adding support for parsing octal numbers

### ISSUE THREAD

**Issue by ageekymonk** [json-c/json-c#172]
If the number starts with 0, then it should be parsed as an octal number. Currently it parses it as integer.

**Comment by crawley** [comment]
Please DO NOT add support for parsing octal numbers.  The JSON specifications clearly say that JSON only supports decimal.  If you add octal (or hexadecimal) you are 1) violating the spec, 2) encouraging users in the belief that these things *should* work.

If you want octal support in JSON, get the specification revised >>first<<.

**Comment by rgerhards** [comment]
+1 for not violating the spec  (RFC4627, Sect. 2.4)

**Comment by hawicz** [comment]
Following the spec sounds good to me, closing w/o changes.
