### ISSUE TITLE
json_parse_int64 doesn't work correctly at illumos

### ISSUE THREAD

**Issue by pyhalov** [json-c/json-c#173]
When I run json-c 0.12 tests on OpenIndiana, I receive complaint on test_parse_int64.test. 
When there's overflow, sscanf sets num64 to 0. So, test
 if (num64 == 0) // assume all sscanf impl's will parse -0 to 0
                        orig_has_neg = 0; // "-0" is the same as just plain "0"
is incorrect, sscanf set  num64 to 0 when it can't parse input line, and this code will reset orig_has_neg to 0.
The following patch allows tests to pass:

```
--- json-c-0.12/json_util.c.~1~ 2014-04-11 04:41:08.000000000 +0400
+++ json-c-0.12/json_util.c     2015-03-15 14:49:17.934357502 +0300
@@ -221,7 +222,7 @@
                // Skip leading zeros, but keep at least one digit
                while (buf_sig_digits[0] == '0' && buf_sig_digits[1] != '\0')
                        buf_sig_digits++;
-               if (num64 == 0) // assume all sscanf impl's will parse -0 to 0
+               if (buf_sig_digits[0] == '0' && buf_sig_digits[1] == '\0') 
                        orig_has_neg = 0; // "-0" is the same as just plain "0"

                snprintf(buf_cmp_start, sizeof(buf_cmp), "%" PRId64, num64);
```

**Comment by hawicz** [comment]
Tested on the OpenIndiana "Hipster" release 20170502.

**Comment by jasonbking** [comment]
The test itself is non-standard and non-portable.   The return value of `sscanf()` indicates how many items have been parsed.   On error this might be `-1` or `0` (depending on the nature of the error) and is what should be used.   `ERANGE` is also only documented to be set on Linux (and is explicitly even noted as being non-standard).  FreeBSD goes as far as to not document _any_ errno values on failure.  On failure, the values of the parameters to receive the results are also undefined, and nothing should assume they hold any dependable value.

**Comment by hawicz** [comment]
The Illumos sscanf is broken with respect to that return value too.  It returns 1 even when it is unable to correctly parse the number.
This code should probably use strtol or stroll, if it can be determined that one of those is the right size to match int64_t.

**Comment by jasonbking** [comment]
Looking at it further, there's really no standard guidance on what it should do here (which is unfortunate), though I think making it behave in a more predictable manner would be good.  Unfortunately the illumos sscanf() code dates back to the AT&T days (and is quite ugly), so it might take a bit to get that changed.
However, I do have a version of `json_parse_int64()` that uses `strtoll()` and fully passes the test suite on illumos (SmartOS specifically).  I'll file a PR in a sec for that.
