### ISSUE TITLE
Possible to delete an array element at a given idx ?

### ISSUE THREAD

**Issue by makareth** [json-c/json-c#176]
Hi,

I thought json-c would allow for something like  json_object_array_del_idx(struct json_object *obj, int idx) ).

Applied to [0 1 2 ], json_object_del_idx(o,1)  would transform the object to [0 2].

The put_idx with a null object is not what I want.

Did I miss something ?

**Comment by hawicz** [comment]
No, you didn't miss anything, such a function does not (yet) exist.
