### ISSUE TITLE
json_tokener_parse_ex accepts invalid JSON

### ISSUE THREAD

**Issue by rgerhards** [json-c/json-c#181]
RFC4627 says in Sect. 2 that valid json must be either an object or array at the root:
```
JSON-text = object / array
```
following the ABNF definitions in RFC4627, this means that it must start with either '{' or '['. Unfortunately, json-c also accepts other root elements, e.g. numbers. Here is an example:

```
#include <stdio.h>
#include <json-c/json.h>

int main()
{
	struct json_tokener *tokener = json_tokener_new();
	struct json_object *const json
		= json_tokener_parse_ex(tokener, "15:00", 5);
	printf("return code %d\n", json_tokener_get_error(tokener));
	printf("extracted %s\n", json_object_to_json_string(json));
}
```

build and executed:
```
$ gcc testjsonc.c -ljson-c
$ ./a.out
return code 0
extracted 15
```

**Comment by skizzerz** [comment]
4627 is not on the standards track and is obsoleted by 7159, where JSON-text is any value surrounded by whitespace. ECMA 404 also allows the top level of a json document to be any value, not just objects or arrays.

**Comment by hawicz** [comment]
We should aim to follow RFC 7159.  I updated the README.md to mention this (changeset ae66b24).
