### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by aqzwss** [json-c/json-c#185]
json_tokener.c: In function 'json_tokener_parse_ex':
json_tokener.c:355:6: error: variable 'size' set but not used [-Werror=unused-but-set-variable]
int size;

CentOS7
gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC)

**Comment by aqzwss** [comment]
json-c-json-c-0.12-20140410.tar.gz

**Comment by ThomasWaldmann** [comment]
I have the same thing. The newest release does not compile. :(

I tried it on a raspberry pi 2 with raspian (debian 7) in case that matters.

**Comment by ThomasWaldmann** [comment]
Duplicate of #159.
