### ISSUE TITLE
array_list_get_idx and negative indexes.

### ISSUE THREAD

**Issue by pneuse** [json-c/json-c#187]
Potential problem with array_list_get_idx

As shown below, array_list_get_idx will validate i is less then the array list, but there is no check for a negative index value.  As a result, I believe that this function when given a negative number will return garbage.

void* array_list_get_idx(struct array_list *arr, int i)
{
  if(i >= arr->length) return NULL;
  return arr->array[i];
}

**Comment by fweimer** [comment]
In addition, `array_list_expand_internal` should check for negative `max` values and integer overflows.

**Comment by hawicz** [comment]
I'd say that's a problem with your code, not json-c.  If it's going to do anything, it should abort if the array index is out of range.
