### ISSUE TITLE
warning: initialization discards ‘const’ qualifier from pointer target type [enabled by default]

### ISSUE THREAD

**Issue by v4ssilij** [json-c/json-c#190]
This is the code:

void send_file(json_object *jobj){
	FILE *fp_test;
	fp_test = fopen("test.out", "a+");
	char *serialnumber = json_object_get_string(jobj);	
	fprintf(fp_test, " %s\n", serialnumber);
	fclose(fp_test);
						
}

¿What's happend?

**Comment by hawicz** [comment]
You're not allowed to modify the value returned from json_object_get_string() so it returns a _const_ char *, but your "serialnumber" variable isn't const, so you're not allowed to assign it like that.  This isn't a json-c bug.
