### ISSUE TITLE
json_tokener_parse  accepts invalid JSON {"key": "value" ,  }

### ISSUE THREAD

**Issue by YorkTsai2012** [json-c/json-c#192]
#include <json-c/json.h>                                                                                                                                                            
#include <stdio.h>
#include <string>

int main() {
    std::string json = "{\"op\":\"set\",}";
    printf("an invalid json string = %s\n", json.c_str());
    json_object *root = json_tokener_parse(json.c_str());
    if (root) {
        printf("root = %x, is not NULL\n", root);
    }
    return 0;
}

g++ test-json.cpp -I/usr/local/include/json-c -ljson-c
./a.out 
an invalid json string = {"op":"set",}
root = 18b9510, is not NULL 

@hawicz

**Comment by hawicz** [comment]
On August 24, 2015 1:36:25 AM EDT, "蔡月樵" <notifications@github.com> wrote:
>#include <json-c/json.h>                                               
>                                                                       
>#include <stdio.h>
>#include <string>
>
>int main() {
>    std::string json = "{\"op\":\"set\",}";
>    printf("an invalid json string = %s\n", json.c_str());
>    json_object *root = json_tokener_parse(json.c_str());
>    if (root) {
>        printf("root = %x, is not NULL\n", root);
>    }
>    return 0;
>}
>
>g++ test-json.cpp -I/usr/local/include/json-c -ljson-c
>./a.out 
>an invalid json string = {"op":"set",}
>root = 18b9510, is not NULL 

If you want full control over the parsing, and be able to see the error returned, you should use json_tokener_parse_ex and pass the JSON_TOKENER_STRICT flag.
The lenient behaviour you see with json_tokener_parse() is intentional.

**Comment by YorkTsai2012** [comment]
@hawicz  Thank you for your  explanation, which is also helpful to understand the difference of json_tokener_parse and json_tokener_parse_ex.
