### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by jite** [json-c/json-c#197]
Since 0.12 doesn't build on systems with newer gcc perhaps it's time to release a new version?

Thanks

**Comment by hawicz** [comment]
Does the most recent code build on the system that you're referring to?

**Comment by doctaweeks** [comment]
I have an application that makes use of the "new" json_object_from_fd function for (de)serializing via pipes and stdin. It would be incredibly useful if there was a new tagged version to reference as a dependency instead of a commit checksum.

**Comment by hawicz** [comment]
I just created a 0.12.1 release that includes the two small compile fixes on the json-c-0.12 branch.  I'll probably create a 0.13 release, with all the other changes from the master branch, sometime in the relatively near future.
