### ISSUE TITLE
Add source position/coordinates to API

### ISSUE THREAD

**Issue by dejj** [json-c/json-c#203]
Is there a way to access source coordinates via the json-c api?

I read in JSON data and perform semantic consistency checks. I would like to emit warnings for consistency failures, which shall contain line and column number.

Is it feasible to store json_tokener::st_pos into json_object for this purpose?

**Comment by hawicz** [comment]
No, there's nothing like that available right now.  Perhaps something could be hacked in at the point when a field is added to an object:
https://github.com/json-c/json-c/blob/master/json_tokener.c#L863

Also, you'll want to save tok->char_offset, not st_pos.
A minimally intrusive way to do this might be by having some way to set a tokener callback that fills the _userdata field.  If you can come up with a reasonable way to do so, I'd be happy to consider it for inclusion.
