### ISSUE TITLE
json-c Compiled with Visual Studios

### ISSUE THREAD

**Issue by cuitpoisson** [json-c/json-c#205]
Hi, I was trying to run a compiled version on VS2013 and noticed that freeing up memory that was allocated with strdup caused some asserts/exceptions. It turns out VS doesn't want us to use strdup and instead use _strdup so you can correctly free it. I changed my version so that it uses the correct strdup (which has some defines to get the correct one) and thought you should update your code.

The define in config.h.win32 should change to:
```
/* Define to 1 if you have the `strdup' function. */
#define HAVE_STRDUP 0

**Comment by Nzbuu** [comment]
Pull request?
