### ISSUE TITLE
what do i use in place of json_object_object_get?

### ISSUE THREAD

**Issue by gaby64** [json-c/json-c#206]
ive been out of the loop for a while

**Comment by rgerhards** [comment]
json_object_object_get_ex(), but be sure to read the doc, semantics are a bit different.

**Comment by hawicz** [comment]
Fwiw, you can see an example of it in the tests: https://github.com/json-c/json-c/blob/1757a31750134577faf80b91d0cf6f98d3918e6c/tests/test_cast.c#L69
