### ISSUE TITLE
fix to compile with microsoft visual c++ 2010

### ISSUE THREAD

**Issue by denisdemais** [json-c/json-c#213]
Hi,

i was fixed to compile with minimal changes, attached.

[compile_vs2010_errros.txt](https://github.com/json-c/json-c/files/60625/compile_vs2010_errros.txt)
[linkhash.h.txt](https://github.com/json-c/json-c/files/60626/linkhash.h.txt)
[json_object.c.txt](https://github.com/json-c/json-c/files/60627/json_object.c.txt)
[json_tokener.c.txt](https://github.com/json-c/json-c/files/60628/json_tokener.c.txt)

**Comment by denisdemais** [comment]
![dump](https://cloud.githubusercontent.com/assets/13302670/11769815/68155360-a1d7-11e5-89fe-db2d57cb13d1.png)

**Comment by hawicz** [comment]
I'm lazy, and VS2010 is pretty old by now so I'm not inclined to put much effort into this.
If the changes are minimal, and you can provide at least diffs (ideally a pull request), then I'll merge this, but with entire files (and no starting changeset) it's hard to tell what's different.
