### ISSUE TITLE
Some non-GNU systems support __sync_val_compare_and_swap

### ISSUE THREAD

**Issue by andy-js** [json-c/json-c#214]
This is the diff I've been using when building libjson-c on illumos with GCC 5.1 (which has __sync_val_compare_and_swap).

<pre>
diff --git a/linkhash.c b/linkhash.c
index c89e35b..b19c055 100644
--- a/linkhash.c
+++ b/linkhash.c
@@ -4,6 +4,7 @@
  * Copyright (c) 2004, 2005 Metaparadigm Pte. Ltd.
  * Michael Clark <michael@metaparadigm.com>
  * Copyright (c) 2009 Hewlett-Packard Development Company, L.P.
+ * Copyright 2015 RackTop Systems.
  *
  * This library is free software; you can redistribute it and/or modify
  * it under the terms of the MIT license. See COPYING for details.
@@ -447,7 +448,7 @@ static unsigned long lh_char_hash(const void *k)
                int seed;
                /* we can't use -1 as it is the unitialized sentinel */
                while ((seed = json_c_get_random_seed()) == -1);
-#if defined __GNUC__
+#if defined __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4
                (void)__sync_val_compare_and_swap(&random_seed, -1, seed);
 #elif defined _MSC_VER
                InterlockedCompareExchange((LONG *)&random_seed, seed, -1);
</pre>

**Comment by sknaumov** [comment]
BTW, I'm using json-c-0.12 and finally faced toochain that doesn't have __sync_val_compare_and_swap_4. When I tried to apply a patch from this issue, I saw that some toolchains that worked OK with __sync_val_compare_and_swap no longer do so and produce a warning about racy behavior. So it seems that __GCC_HAVE_SYNC_COMPARE_AND_SWAP_* macro are not defined in all toolchains that have this functionality. I tried to use configure.ac AC_TRY_LINK instead and now I see no regressions for other toolchains.

[0003-fix-compare-and-swap.patch.bad.txt](https://github.com/json-c/json-c/files/3301353/0003-fix-compare-and-swap.patch.bad.txt)
[0003-fix-compare-and-swap.patch.good.txt](https://github.com/json-c/json-c/files/3301354/0003-fix-compare-and-swap.patch.good.txt)
