### ISSUE TITLE
Build json-c for window 64 bit.

### ISSUE THREAD

**Issue by bachlx-bitmark** [json-c/json-c#215]
Dear all.
I need build dll file of "json-c", I had build dll file (32bit) but it can't run in my library.
Can you support me build dll(64bit) of json-c?

Please help me.
Thanks!

**Comment by Nzbuu** [comment]
What have you done so far?

**Comment by bachlx-bitmark** [comment]
Dear Nzbuu!

Now I had build success json_c.dll and json_c.lib (64bit) by Visual studio 2013. 
I will use json_c (and some other library) for my library (ex:mylib.dll) file, and my program will load dll files (contain json_c.dll and mylib.dll).
When load mylib.dll, It always show error : Win32 error 127. ( don't show other message or more detail)
If in my library, I remove code use json_c, my program load dll files success.
So I think, there are problem when I build json_c.

But, I had try build and use json_c in 32bit version, it load success.
So, I think I had build error json_c in 64bit version.

I hope you can help me.

Thanks!

**Comment by Nzbuu** [comment]
What have you done to diagnose the problem yourself? Have you looked at this: http://stackoverflow.com/questions/1053180/loadlibrary-error-code-127. I'm not sure this is a problem with the json-c library, but with the way you're loading it.

**Comment by bachlx-bitmark** [comment]
I had detach my issue, It is not and issue of json_c.
I close this issue. 
Thanks
