### ISSUE TITLE
Checking for functions in float.h

### ISSUE THREAD

**Issue by sevan** [json-c/json-c#217]
Hi,
According to the POSIX spec , `isnan` & `finite` are defined in `math.h`, is there any reason why the autoconf script checks for them in `float.h` instead, [then links in libmath after as a separate test](https://github.com/json-c/json-c/blob/master/configure.ac#L52-L57)?

**Comment by hawicz** [comment]
No, it checks for _isnan and _finite (*with* underscores) there to allow for building on MS Windows.
