### ISSUE TITLE
Bump SOVERSION to 3

### ISSUE THREAD

**Issue by oerdnj** [json-c/json-c#227]
You simply cannot remove interfaces (`json_tokener_errors` and `mc_abort`) and don't bump SOVERSION. That breaks all existing applications using the old ABI and already linked with libjson-c.so.2.

See https://autotools.io/libtool/version.html and http://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html#Updating-version-info

**Comment by hawicz** [comment]
dup of #147
