### ISSUE TITLE
Building a project which uses json-c with flag -Wcast-qual causes compilation errors

### ISSUE THREAD

**Issue by svagionitis** [json-c/json-c#236]
I use `json-c` in one project which one of the compiler flags is [-Wcast-qual](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html). I use the macro `json_object_object_foreach` and I get the following error when compiling

```
error: cast from 'const void *' to 'struct json_object *' drops const qualifier [-Werror,-Wcast-qual]
    json_object_object_foreach(body_json, key, val)
    ^
/usr/include/json-c/json_object.h:320:31: note: expanded from macro 'json_object_object_foreach'
                        val = (struct json_object*)entry ## key->v; \
                                                   ^
```

This happens because [the value, in the `lh_entry`, is set as const](https://github.com/json-c/json-c/blob/master/linkhash.h#L88) but in the macro `json_object_object_foreach` [the value is type casted as non-const](https://github.com/json-c/json-c/blob/master/json_object.h#L459).

Now, removing the `const` qualifier from the value in `lh_entry` fixes the issue, but I am not familiar with the `json-c` code base and I don't think that might be the proper solution.

**Comment by hawicz** [comment]
No, the const should stay there.  I've got some changes that should improve the situation, which I'll be pushing shortly.

**Comment by svagionitis** [comment]
Cool, thanks @hawicz for your quick reply and fix.
