### ISSUE TITLE
handle escaped utf-8

### ISSUE THREAD

**Issue by ldv** [json-c/json-c#237]
The library does not seem to handle UTF-8 escaped strings correctly.

```
int main(void)
{
  char *s;
  json_object *json;

  s = "{ \"foo\" : \"\u00a9\" }";

  printf("string = %s\n", s);
  json = json_tokener_parse(s);
  printf("json = %s\n", json_object_to_json_string_ext(json, JSON_C_TO_STRING_PRETTY));

  json_object_put(json);
}
```

Output:

```
string = { "foo" : "©" }
json = {
  "foo":"\u00
```

Maybe I'm doing something wrong, or is it a bug?

**Comment by rgerhards** [comment]
@ldv are you sure you **actually** have this problem with json-c? I could reproduce it with libfastjson, but the fix there is not needed by json-c. I also crafted a testbench test, which initially failed on libfastjson, but works great on json-c.

**Comment by hawicz** [comment]
Closing, since it doesn't appear to be a problem with json-c.
