### ISSUE TITLE
json_tokener_parse error

### ISSUE THREAD

**Issue by ooooldman** [json-c/json-c#242]
printf("json_source %s\n", buf);
// output:  {"pt-BR":"Ásia"}

json = json_tokener_parse(buf);
printf("json = %s\n", json_object_to_json_string(json)); 

//output: json = {"pt-BR": "\u00 

???

**Comment by rgerhards** [comment]
Are you sure this is with json-c and not with libfastjson? See #237

**Comment by ooooldman** [comment]
thanks!

**Comment by hawicz** [comment]
Closing, since it doesn't appear to be a problem with json-c.
