### ISSUE TITLE
json_object_array_del_idx function has segment fault error?

### ISSUE THREAD

**Issue by jalnanco** [json-c/json-c#247]
I made an array to take three json_objects.
When I use json_object_array_del_idx function it has error like this

save part

```
        json_object *my_object = json_object_new_object();
        json_object_object_add(my_object, "EUI64", json_object_new_int64(eui64.llvalue));
        json_object_object_add(my_object, "nodeId", json_object_new_int(nodeId.lvalue)); 
        json_object_object_add(my_object, "Key", json_object_new_int(globalKey.lvalue));
        json_object_array_add(pairArray, my_object);

```

delete part
```
int targetIndex = searchPairWithEUI64(pairArray, eui64);
if(targetIndex != -1) {
    if(json_object_array_del_idx(pairArray, targetIndex, 1) == 0 ) {
        emberSerialPrintf(APP_SERIAL,"Delete Success\r\n");
    }
}
```

the result in delete part:
Segmentation fault (core dumped)

**Comment by hawicz** [comment]
There's nothing obviously wrong in those few lines of code you listed but you're not provide enough information to figure out anything at all.
Where does it crash?  Have you checked targetIndex vs the size of pairArray to ensure it's in range?  Do you have a minimal test case that shows the problem?

**Comment by jalnanco** [comment]
I think It might be my mistake.
I should make a code and test it again.
Sorry for bother you. this is not enough explained.
Anyway, Thank you for reply

**Comment by hawicz** [comment]
Ok, good luck finding the bug.  If it turns out to be a problem in json-c, please re-open this issue.
