### ISSUE TITLE
Mailing list dead?

### ISSUE THREAD

**Issue by RyDroid** [json-c/json-c#256]
Hi.

I sent an email to the "json-c at googlegroups dot com" (the email indicated in the wiki). https://github.com/json-c/json-c/wiki
I received this answer:

> Hello user@computer.tld,
> 
> We're writing to let you know that the group you tried to contact (json-c) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post:
> 
>  * You might have spelled or formatted the group name incorrectly.
>  * The owner of the group may have removed this group.
> * You may need to join the group before receiving permission to post.
>  * This group may not be open to posting.
> 
> If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/.
> 
> Thanks,
> 
> Google Groups

However the webpage seems to work. o_O
https://groups.google.com/forum/?_escaped_fragment_=forum/json-c#!forum/json-c

Regards.

**Comment by hawicz** [comment]
As the reply says, you need to join the group before you can post.

**Comment by hawicz** [comment]
That could use a mention on the wiki page.

**Comment by hawicz** [comment]
That could use a mention on the wiki page.

**Comment by RyDroid** [comment]
Ah, ok.
The only solution I found is to have a Google account and use a lot of [proprietary JavaScript](https://www.gnu.org/philosophy/javascript-trap). Is there a clean way (no [Big Brother](https://www.gnu.org/philosophy/surveillance-vs-democracy) and no proprietary software)? Is it a special thing against Tor users (I use the Tor Browser)?
Otherwise, is there an other way to ask for help?

**Comment by hawicz** [comment]
You could submit a bug through github, which has no JavaScr... er scratch that.  Telepathy?
I have nothing against Tor users, but I don't use it myself, so any roadblocks you run into are likely accidental.
