### ISSUE TITLE
Defining a coding style

### ISSUE THREAD

**Issue by RyDroid** [json-c/json-c#257]
Hi.

I read some parts of the source code. Unfortunately, it is not homogeneous. Fox example, some parts seem to respect the GNU coding style and some parts are indented with tabulations.
I think that it should be good to define a clear coding style. I suggest that to use one that is already widely used like the GNU one or K&R.
https://en.wikipedia.org/wiki/Indent_style

Regards.

**Comment by hawicz** [comment]
I've been using a tab based indent style for new code and major changes, but an overall convention is not well defined yet.  I'll write something up later today.

**Comment by hawicz** [comment]
I added a brief style guide as https://github.com/json-c/json-c/blob/master/STYLE.txt
I think it should cover the main points, but feel free to suggest additions/changes.

**Comment by RyDroid** [comment]
Great.
