### ISSUE TITLE
Enable CI services

### ISSUE THREAD

**Issue by Nzbuu** [json-c/json-c#258]
There are build scripts for both [Travis](https://travis-ci.org/) (Linux and MacOS) and [Appveyor](https://www.appveyor.com/) (Windows) in the repository. Can you enable these services for the main project, please? They're both free for open-source projects.

This should reduce the chances of the code becoming un-compilable (as a minimum). In particular, the Windows builds were working in November 2015, but are now broken.

**Comment by hawicz** [comment]
done
