### ISSUE TITLE
Compiler Warnings with VS2015

### ISSUE THREAD

**Issue by SparhawkSoftware** [json-c/json-c#263]
json_object.c(453): warning C4028: formal parameter 2 different from declaration
json_object.c(453): warning C4028: formal parameter 3 different from declaration

It appears the const qualifiers are different:

implementation:
```
int json_object_object_add_ex(struct json_object* jso,
	const char *const key,
	struct json_object *const val,
	const unsigned opts)
```

declaration:
```
extern int json_object_object_add_ex(struct json_object* obj, const char *key,
				   struct json_object *val, const unsigned opts);
```
What is the right fix?

**Comment by hawicz** [comment]
That's odd that gcc doesn't emit a warning.  Anyway, I'll add the const qualifier to the header file.
