### ISSUE TITLE
Conformance report for reference

### ISSUE THREAD

**Issue by miloyip** [json-c/json-c#265]
https://github.com/miloyip/nativejson-benchmark/blob/master/sample/conformance_json-c%20(C).md

**Comment by hawicz** [comment]
Many of those are behaving as intended.  If you want to be picky about what it accepted, be sure to set JSON_TOKENER_STRICT when parsing.

On the other hand, json-c's number parsing looks like it needs some fixes.

**Comment by sdrsdr** [comment]
Can we have JSON5 compat table? These are  really handy features:  trailing comas, names without quotes, single quotes. Here is the full reference:  http://json5.org/

**Comment by hawicz** [comment]
Feel free to add such a page to the wiki (https://github.com/json-c/json-c/wiki).
