### ISSUE TITLE
new API json_object_new_double_f(doubel d,const char * fmt);

### ISSUE THREAD

**Issue by sdrsdr** [json-c/json-c#270]
It is internally possible to use different format for serializing double values  - the format is attached to user data filed of the json object as done in json_object_new_double_ds.  The function to be set to jso->_to_json_string  must be  json_object_double_to_json_string and not json_object_double_to_json_string_default. 
This can't be done "extenally" as json_object_double_to_json_string is declared static and thus not exported by the library.

**Comment by hawicz** [comment]
Rather than adding another ..._new_... function, it would be better to simply publish the appropriate ...to_json_string function.  Pull requests (including any doc and test changes) are welcome.

**Comment by sdrsdr** [comment]
I was thinking about creating json_object_double_set_format() that will do the needed internal structures manipulating as the other approach will require users including json_object_private.h which is bad practice IMHO

**Comment by hawicz** [comment]
If you make json_object_double_to_json_string_format() non-static, and declare it in json_object.h, there is no need for users to do anything with json_object_private.h

**Comment by sdrsdr** [comment]
Yes but this will not work when serializing complex objects as there is no user exposed way to control how objects are serialized

**Comment by hawicz** [comment]
Yes there is: json_object_set_serializer()
Is that not sufficient for your needs?

**Comment by hawicz** [comment]
Closing, since I believe json_object_set_serializer() make this new function unnecessary.
