### ISSUE TITLE
Serialization of double with no fractional component drops trailing zero

### ISSUE THREAD

**Issue by SteVwonder** [json-c/json-c#278]
Calling `double-to-json_string` on a double with no fractional component results in the dropping of both the trailing zero and the period (e.g. `1.0` is serialized as `1`).   So when that string is deserialized, the type is inferred as an int.  I am not sure if this is the intended behavior of this function or not.  [This comment](https://github.com/json-c/json-c/blob/master/json_object.c#L716) leads me to believe it is not.  It seems that the use of `%g` is the cause of this behavior.

FWIW, you can find the full discussion we had about this issue in the flux-framework project [here](https://github.com/flux-framework/flux-sched/issues/214#issuecomment-256104514).

**Comment by hawicz** [comment]
Yeah, that sounds like a bug to me.
