### ISSUE TITLE
Segmentation fault in array_list_length()

### ISSUE THREAD

**Issue by ssevugan** [json-c/json-c#279]
I see a coredump with segmentation fault when handling invalid JSON message. Shouldn't the json_tokener_parse() return a NULL json-object for invalid JSON message.

This is my code:

json_object *jobj = json_tokener_parse(msg);
    if (!jobj)
        return rc;
   parse_msg_json_obj(jobj, ctrl_msgs);

This is the coredump i see,

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f2397d98c60 in array_list_length () from /usr/lib64/libjson-c.so.2
[Current thread is 1 (Thread 0x7f23968ce700 (LWP 6571))]

Thread 1 (Thread 0x7f23968ce700 (LWP 6571)):
#0  0x00007f2397d98c60 in array_list_length () from /usr/lib64/libjson-c.so.2
#1  0x00000000004ac285 in parse_msg_json_obj(json_object*, std::vector<std::shared_ptr<ControlMsg>, std::allocator<std::shared_ptr<ControlMsg> > >&) ()
#2  0x00000000004ac33c in parse_msg(char*, std::vector<std::shared_ptr<ControlMsg>, std::allocator<std::shared_ptr<ControlMsg> > >&) ()
#3  0x00000000004a92d8 in control_connection::do_read_body()::{lambda(boost::system::error_code, unsigned long)#1}::operator()(boost::system::error_code, unsigned long) const ()

**Comment by hawicz** [comment]
Should json_tokener_parse return NULL?  Sure, but that depend on what you mean by "invalid", please show your input.

Also, json-c doesn't have a parse_msg_json_obj function, so please show the actual code that is crashing, preferrably as a minimal test case.

**Comment by ssevugan** [comment]
Invalid in the sense random messages sent through the socket.

Sorry about that, here is the flow continuation

void
parse_msg_json_obj(json_object* root_jobj, std::vector<std::shared_ptr<ControlMsg>>& msgs) {

    if (!root_jobj)
        return;

    //json_object* val_obj = NULL;
    int msg_cnt = json_object_array_length(root_jobj); --> "crashes here where the array_list_length() is invoked"

**Comment by hawicz** [comment]
In the universe of all possible bytes strings generated at random, there are a sizeable number (infinite, actually) that at least start with json, and thus will cause a non-NULL return when parsing.

However, not all of those returned objects are arrays, and it's not valid to call array functions on other types of objects, so this sounds like "programmer error".  You should check the type of object you're dealing with using json_object_get_type() and handle different types appropriately.

**Comment by hawicz** [comment]
Closing based on the assumption that a non-array was passed to json_object_array_length().
