### ISSUE TITLE
Should json_object_array_get_idx  check whether input obj is array? 

### ISSUE THREAD

**Issue by sigusr1** [json-c/json-c#280]
If input param obj isn't array, json_object_array_get_idx  encounter segment fault.

**Comment by hawicz** [comment]
What would it do when passed another object type?  It seems like a pretty significant programmer error to be trying to get an array element out of something that isnt an array, so perhaps it could emit a more useful error to stderr, then reliably crash by calling abort.

**Comment by ploxiln** [comment]
This is a case where an `assert()` may be appropriate, something like

```c
assert(json_object_get_type(jso) == json_type_array);
```

(when compiled with NDEBUG it goes away, which is appropriate for purely-programmer-error)
