### ISSUE TITLE
how to pretty print json-c? 

### ISSUE THREAD

**Issue by daiziyi** [json-c/json-c#281]
is it hava a function to pretty print json-c ?

**Comment by daiziyi** [comment]
json_object_to_json_string_ext(jobj, JSON_C_TO_STRING_PRETTY );

see: "json_object.h", the header file has a lot of introdution.

**Comment by hawicz** [comment]
Glad you found the flag.  There are a few others there too, depending on how exactly you want the output to be formatted.
