### ISSUE TITLE
configure error  "./configure: line 13121: syntax error near unexpected token `-Wall'"

### ISSUE THREAD

**Issue by daiziyi** [json-c/json-c#292]
hi,  when i execute the follower command, happen error: 
`# ./configure `

![default](https://cloud.githubusercontent.com/assets/5773786/21047606/cd41edee-be45-11e6-9956-615236422c62.png)

json-c version: 0.12.99
my os:  Linux localhost.localdomain 2.6.32-431.el6.x86_64

thank you!

**Comment by hawicz** [comment]
That's just the kernel version, not the actual OS version.  Are you running CentOS or RHEL?

Also, what version of autoconf do you have?  If "autoconf -V" doesn't say at least version 2.64 you'll need to update to a newer one.

**Comment by hawicz** [comment]
I updated configure.ac to specify the minimum version of autoconf needed.  See commit a443b9f7e72.

Note that if you need to build and run your own newer copy I've tested with autoconf-2.64, automake-1.10.3 and libtool-2.2.6b installed into an arbitrary location.

**Comment by daiziyi** [comment]
Thank you @hawicz !  I have use the lastest json-c git version and update autoconf to 2.69, before is autoconf-2.63.  And the "./configure" is pass, and then successfully compile json-c lib . 
my os is RHEL 6.5.

**Comment by hau7626520** [comment]
Hi,

My OS is Mint (linuxmint-18-cinnamon-32bit.iso), and I try the command 'autoconf -V':
autoconf (GNU Autoconf) 2.69

I process the steps below, and got the same error message:
git clone git://github.com/json-c/json-c.git /opt/git/json-c
cd /opt/git/json-c/
autoreconf -i
./configure --prefix=/usr

Could you please help on this?

**Comment by daiziyi** [comment]
@hau7626520 I just 'git clone' the lastest version of 'json-c' and install 'autoconf' with source code, 
and then successfully compile json-c. But I don't know why is work. My system has two version of 'autoconf': 2.63, 2.69.  '2.69' is installed in '/usr/local/bin/autoconf', '2.63' is installed in '/usr/bin/autoconf'.  
My Path is:
![default](https://cloud.githubusercontent.com/assets/5773786/21258290/3e3fb05a-c3b7-11e6-82de-71b3d1d4b675.png)

**Comment by jaartamendi** [comment]
In my case, despite having autoconf 2.69 installed, I also had to install the "autoconf-archive" package to get rid of this error.

**Comment by linghuazaii** [comment]
@jaartamendi @hawicz I install the `autoconf-archive` but I still have this error.
