### ISSUE TITLE
Missing functions header in json_object.h

### ISSUE THREAD

**Issue by kxp** [json-c/json-c#296]
I was trying to use `extern int json_object_set_int(struct json_object *obj,int new_value);` which I include from `/usr/include/json-c/json_object.h` but its not there. But if I use the original header that I use to compile the lib I get undifined reference. 
The same thing happens to other setters. There is a test file(test_set_vale.c) that also uses this function,in that case I 'm assuming that it can be use from the "outside".
I am using the version 0.12.1.

**Comment by hawicz** [comment]
json_object_set_int was added on October 5th in commit 05f025c0.
Version 0.12.1 is from June.
If you want to use that function you'll need to build and install from a more recent copy of the code than the 0.12.1 release.
