### ISSUE TITLE
could not parse string to Json object? Like string str=\"helloworld;E\\test\\log\\;end\"

### ISSUE THREAD

**Issue by daiziyi** [json-c/json-c#297]
hi, I want parse string to json object, but when the string has symbol "\\", parsing is failure? why it happen? Here is my test code:
```
#include <json-c/json.h>
#include <string>
using namespace std;

int main()
{
    string str = "\"helloworld;E\\test\\log\\;end\""; /* not working! */
    //string str = "\"helloworld;E\test\log\;end\"";  /* work! */

    enum json_tokener_error jerr = json_tokener_success;

    json_object *json;

    json =  json_tokener_parse_verbose( str.c_str(), &jerr);

    if( jerr != json_tokener_success){
        cout << "Failed to parse string: ->" << str << "<- to json" << endl;
        cout << "ERROR: " << jerr << " " << json_tokener_error_desc(jerr) << endl;
        return -1;
    }

    cout << "json string: " << json_object_get_string(json) <<endl;

    json_object_put(json);
    return 0;

}
```

Console Result:

```
*******************************************************
1. when  str = "\"helloworld;E\\test\\log\\;end\""
output is: 
Failed to parse string: ->"helloworld;E\test\log\;end"<- to json
ERROR: 12 invalid string sequence
 
2. when  str = "\"helloworld;E\test\log\;end\""
output is: 
json string: helloworld;E	estlog;end
```

```
";E\\test\\log\\;" is invalid string sequence?    Thank you!
```

**Comment by ploxiln** [comment]
When you write `\t` in `E\test` in c or c++, that means a tab character. That's OK.

When you write `\\` in `test\\log` in c or c++, that means a single actual `\`. Then, json sees `\l` in `test\log` and `\l` is an invalid escape sequence. See http://json.org/

**Comment by hawicz** [comment]
If you actually want a backslash in the string object, you'll need another level of backslashes in your source code:

    string str = "\"helloworld;E\\\\test\\\\log\\\\;end\""; /* not working! */

Turns into this sequence of bytes in memory:

      "helloworld;E\\test\\log\\;end"

which will then get parsed into this sequence of bytes by json-c:

      helloworld;E\test\log\;end
