### ISSUE TITLE
(.text+0x72846): undefined reference to `is_error'

### ISSUE THREAD

**Issue by sangli00** [json-c/json-c#304]
Why json-c is not include is_error function?

**Comment by hawicz** [comment]
Because it is horribly vague, and mostly useless.  If you want to check whether json_tokener_parse() failed, just compare its return value against NULL.

**Comment by ploxiln** [comment]
`is_error` is a macro ('#define`), not a function. But perhaps you didn't include the header `json-c/bits.h`, so your compiler first complained "warning: implicit declaration of function" ...

**Comment by sangli00** [comment]
``` json-c.h``` is not include ```bits.h```,and nobody include ```bits.h```

**Comment by sangli00** [comment]
I modify  json-c.h ,add this  macro.

**Comment by ploxiln** [comment]
It's intentionally not used by anything in json-c

commit d4e81f9ec8273914739808737fa0a27a3f0589fb
Author: Eric Haszlakiewicz
Date:   Sat May 3 22:29:10 2014 -0400

    Move the json_min() and json_max() macros to json_util.h and mark everything else in bits.h deprecated.
    Eliminate all uses of bits.h within the json-c code.

**Comment by hawicz** [comment]
Do not use bits.h, nor any of the macros in it, and it definitely should not be added to json-c's json.h header.  It will be entirely removed in a future release.

**Comment by sangli00** [comment]
@hawicz  some old project is used this macros...
If you entirely removed ,some project is can't compile

**Comment by hawicz** [comment]
Well "some old project" will need to be updated then.  The world doesn't remain static, and although json-c has kept this to help maintain compatibility for quite some time we're not going to leave old crap around forever.

**Comment by sangli00** [comment]
@hawicz  OK  thanks.

**Comment by hawicz** [comment]
Note that the definitions in this header are trivial.  If you want to keep using them in some other project, just copy over what you need.
