### ISSUE TITLE
GCC 7 reports various -Wimplicit-fallthrough= errors

### ISSUE THREAD

**Issue by marxin** [json-c/json-c#309]
GCC properly reports various places in code, where a case label falls through to another label:

json_object.c:678:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
json_tokener.c:339:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:418:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:419:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:420:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:421:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:422:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:423:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:424:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:425:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:426:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:427:15: warning: this statement may fall through [-Wimplicit-fallthrough=]
linkhash.c:428:15: warning: this statement may fall through [-Wimplicit-fallthrough=]

Can you please take a look?

**Comment by hawicz** [comment]
I expect those locations need /* FALLTHRU */ comments added.  Pull requests are welcome.
