### ISSUE TITLE
new release ?

### ISSUE THREAD

**Issue by commodo** [json-c/json-c#314]
Hey,

More of a question than an issue.
Feel free to close it whenever.

Seems the last tarball release was a while ago [last year], and it did not contain some new stuff.
Any thoughts on when the next tarball release will be ?
Or if there will be one ?
Or thoughts on the release process ?

Thanks
Alex

**Comment by qlyoung** [comment]
👍

**Comment by qlyoung** [comment]
@hawicz updates on this?

**Comment by pavel-odintsov** [comment]
Hiya!

We're (FastNetMon) also waiting for new release to get gcc 7 support! :)

**Comment by LeSpocky** [comment]
Version json-c-0.13-20171207 was tagged just yesterday. This can be closed then?

**Comment by commodo** [comment]
looks like it :)

will close
thanks for notifying 

w00h00: celebration :)
