### ISSUE TITLE
json_object_get_string gives segmentation error

### ISSUE THREAD

**Issue by tikluganguly** [json-c/json-c#317]
Hi All,

 I am trying to parse a json object using json-c. the output of json_tokener_parse_verbose is coming as  "success". The type from json_object_get_type coming as "json_type_string". Also, I can see the length of string by using "json_object_get_string_len". I can even see the string object by calling "json_object_to_json_string". But if I am calling "json_object_get_string" to get the actual string. I am getting a segmentation error. I am using version "1.6" cross compiled for embedded powerpc running linux. Any idea why the error is coming? 

Regards
Tiklu

**Comment by hawicz** [comment]
1.6?  There is no such version of json-c.  The most recent (though old) release is 0.12.

Without more information, such as the line of code where it's crashing, or a full stack trace, it's nearly impossible to suggest what's going wrong.

**Comment by tikluganguly** [comment]
Hi Guys,
      Sorry, I was actually using json-c with azure c sdk. Azure c sdk have parson built into it. Both parson and json-c have "json_object_get_string" function. Now as I was doing a dynamic linking for json-c and static linking on azure sdk. During runtime the function was crashing. The issue is now solved. 

Thanks
Tiklu
