### ISSUE TITLE
PVS-Studio static analyzer analyze results

### ISSUE THREAD

**Issue by kloun** [json-c/json-c#318]
www.viva64.com/en/w:1:1: error: Help: The documentation for all analyzer warnings is available here: http://www.viva64.com/en/w/.
/home/me/src/json-c/json_tokener.c:598:1: warning: V512 A call of the 'memcpy' function will lead to underflow of the buffer 'unescaped_utf'.
/home/me/src/json-c/json_tokener.c:602:1: warning: V512 A call of the 'memcpy' function will lead to underflow of the buffer 'unescaped_utf'.

**Comment by hawicz** [comment]
json_tokener.c only uses memcpy from within the printbuf_memappend_fast macro, so I'm assuming the warnings you list actually refer to lines 597 and 601.
What the heck is a buffer "underflow"?  Is it complaining that the memcpy isn't copying the full size of the buffer?  If so, that's a completely bogus thing for it to be warning about.  As far as I can tell there is no problem here.
