### ISSUE TITLE
implicit fallthrough detected by gcc 7.1

### ISSUE THREAD

**Issue by wongsyrone** [json-c/json-c#323]
```
json_object.c: In function 'json_object_get_int64':
json_object.c:554:5: error: this statement may fall through [-Werror=implicit-fallthrough=]
  if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;
     ^
json_object.c:555:3: note: here
   default:
   ^~~~~~~

```

**Comment by commodo** [comment]
@wongsyrone 
I think you are referencing an older version [ the released one ].
The code in this repo is pretty far ahead of that released version.

This has been addressed in this commit : https://github.com/json-c/json-c/pull/310/commits/014924ba899f659917bb64392bbff7d3c803afc2

Maybe, feel free to backport it :)

**Comment by wongsyrone** [comment]
Yes. We are using json-c-0.12.1. I'm closing this and wait for the next release.

**Comment by commodo** [comment]
There's issue https://github.com/json-c/json-c/issues/314
Maybe add a vote to ? :p
