### ISSUE TITLE
JsonPath like function?

### ISSUE THREAD

**Issue by noisybe** [json-c/json-c#324]
I have had a look at enough JsonPath implementations and, so far, they turned out to be garbage having all kinds of different problems.

Are there any plans to add a JsonPath functionality to libjson-c?

The following XPath expression
`/store/book[1]/title`
would look like
`x.store.book[0].title`
or
`x['store']['book'][0]['title']`

Or is there an JsonPath implementation (that has no other dependencies than libjson-c) i am not aware of?

**Comment by ploxiln** [comment]
I think what you're looking for was added to master in #283 and #287

**Comment by noisybe** [comment]
That is exactly what I am looking for... :D

Thanks.

**Comment by jtojnar** [comment]
JSONPath has recently [received a RFC](https://www.rfc-editor.org/rfc/rfc9535.html). Would you be open to PRs implementing (possibly a subset of) that?
