### ISSUE TITLE
Please extend api json_object_get_uint64

### ISSUE THREAD

**Issue by topilski** [json-c/json-c#326]
Hi, can you add some usefull functions like `json_object_get_uint64 json_object_get_uint32`.

**Comment by hawicz** [comment]
_uint32 would be fairly easy, just a matter of copying json_object_get_int() and replacing types and constants.  _uint64 is harder, since the internal value only parses and stores 63 bits of magnitude.  I'm not sure it's worth the trouble.

**Comment by linghuazaii** [comment]
Yes, I think it is needed. I write a interface `json_object_get_uint64` for internal use. Waiting for this `new-feature`.

**Comment by dota17** [comment]
Adding uint64 data type has been shown in #542 .You can review it and put forward some rectification opinions.

**Comment by hawicz** [comment]
Closing, since support was added in #542.
