### ISSUE TITLE
why json-c so hard to compile

### ISSUE THREAD

**Issue by liudf0716** [json-c/json-c#327]
very time I used it, it will waste much of my time to resolve this and that configuring problem.

**Comment by liudf0716** [comment]
In fact, it's only a little project.

**Comment by hawicz** [comment]
Is there a specific problem you're having?  
On the environments where I use it (NetBSD, Debian, CentOS) it builds just fine, so unless you provide some details, there's not much that can be done.

**Comment by liudf0716** [comment]
@hawicz I can build it fine too, but every time it will take me long time to pass through it in a new building environment. most of time to resolve problem just like this:
1, error: possibly undefined macro: AM_PROG_LIBTOOL
2, error: Libtool library used but 'LIBTOOL' is undefined
It not only my problem, many people using my project [xkcptun](https://github.com/liudf0716/xkcptun) asked me, why choose json-c, why not choose other json library, blablabla....
I am really feel helpless.

**Comment by NieDzejkob** [comment]
The libtool problem can be solved by installing the `libtool` package. Did you have any other problems?

**Comment by ploxiln** [comment]
json-c is "so hard to compile" because it is a C library that attempts to be compatible with many different platforms and toolchains. This issue is too vague, it would be appropriate to close.

**Comment by liudf0716** [comment]
In fact, most of time is not spent on resolve problem such as compatible with many different platforms and toolchains, but like libtool version was too old, u need to update your version, when u update your libtool version, u will encounter other problem. It was not such problem u can not resolve, but really make u annoying

**Comment by hawicz** [comment]
The AM_PROG_LIBTOOL problem is being tracked as Issue #308.  @NieDzejkob explained the "fix" for the "LIBTOOL is undefined" problem.  If there's something else *specific* that needs to be addressed, then that's one thing, but I'm closing this issue.
