### ISSUE TITLE
Valgrind: invalid read after json_object_array_del_idx.

### ISSUE THREAD

**Issue by louandutoit** [json-c/json-c#332]
Hi,
I need to clear an array and add some new elements, but using json_object_array_del_idx is raising a possible issue, when adding new values after deleting.
Below is a snippet of code to reproduce the error. I can work around this by deleting the array object, and recreating, but that is a more time consuming process.

```
int32_t doSomeArrayStuff() {
	json_object * opContainer = json_object_new_object();
	json_object * opArray = json_object_new_array();
	json_object_array_add(opArray, json_object_new_string("string1"));
	json_object_array_add(opArray, json_object_new_string("string2")); //block allocated here
	json_object_array_add(opArray, json_object_new_string("string3")); //block allocated here
	json_object_array_add(opArray, json_object_new_string("string4"));
	json_object_object_add(opContainer, "myarray", opArray);

	if(json_object_array_del_idx(opArray, 0, 3) != 0) { //block free here
		return 1;
	}

	json_object_array_add(opArray, json_object_new_string("string5")); //invalid read of size 4
	json_object_array_add(opArray, json_object_new_string("string6")); //invalid read of size 4
	json_object_put(opContainer);

	return 0;
}
```
Running this through valgrind raises:
Invalid read of size 4

At the position as indicated in the comments. I'm using version "json-c 0.12.99".

**Comment by hawicz** [comment]
hmm... your code looks fine, seems like a bug somewhere in json-c.  I'll see what I can figure out.

**Comment by hawicz** [comment]
Sometimes you wonder how it ever worked.  It should be fixed now, please try again with the most recent code.

**Comment by louandutoit** [comment]
Thanks

**Comment by elbaraka** [comment]
Hi I have exactely the same problem ! any solution please !

**Comment by hawicz** [comment]
@elbaraka, what problem are you talking about?  If you're still getting a valgrind error even after the fix from fd9b3b2 then please open an issue with the details.

**Comment by elbaraka** [comment]
I set this but always the same problem ! it destroys the structure of objects after deletion

**Comment by hawicz** [comment]
I'll be happy to help you, but I don't understand what you're trying to explain.  Please create a separate issue with an example of the problem that you are seeing.
