### ISSUE TITLE
Switch json-c builds to use CMake

### ISSUE THREAD

**Issue by hawicz** [json-c/json-c#334]
As @guru-florida suggested in Issue #308:
Why not just switch to CMake? It isnt that hard to setup and I find real cmake builds always work and autoconf is usually a PITA.

https://github.com/guru-florida/json-c

I'm expecting to merge over these changes after the next json-c release.  (See Issue #314)

**Comment by guru-florida** [comment]
Sounds great. Let know when you do and I can help test and debug.

**Comment by keithbowes** [comment]
Really?  I find the opposite to be true.  ./configure will always tell you what went wrong (e.g. what header file is missing) and you can fix it easily.  With cmake, if something goes wrong, cmake gives you a worthless message (like CMAKE_SOMEESOTERIC_LIB-NOTFOUND) and you have to dig through the cmake lists, cache, and log files to try to figure out what went wrong.  Usually, I just give up with cmake if I can't figure out what went wrong immediately.

**Comment by guru-florida** [comment]
We definitely have a different experience with these two tools but I respect what you are saying because although we differ on the tool I can say the exact same experience with autoconf...cryptic messages, reading log outputs and so on until I give up. So irregardless I feel your pain. :)

Here's my story. I was forced into CMake on a project because we used CLion IDE and it is only cmake compatible. Finally an IDE I liked more than vim. lol. It was after writing some CMake files that I became a fan and I can read the output/errors easily. What I liked most was how good it was at finding various install locations of tools, headers, and libs in the various places on different OSs and distros. Like I just discovered in Java JNI on Windows it actually checks the registry to find the currently selected Java JDK! I have CMake projects that build in Linux, Solaris, OSX and Windows 32/64 (Ming and Visual Studio) and I dont need specialized logic in my cmake scripts to do it. There is definitely experience needed to get it right but I've only been doing cmake for about a year and a half so it's not a big leap.

**Comment by topilski** [comment]
Main CMAKE advantages is debuging in IDE and simple unit test integration CTEST/CDASH.

**Comment by rswindell** [comment]
+1 for CMake support. Cross-platform/tool builds is the most obvious benefit but I found that CMake's ease/encouragement of out-of-tree builds (where all the build output files are located in a completely independent directory tree) was a feature I found surprisingly helpful.

**Comment by guru-florida** [comment]
Hi Rob,

I've forked Json-C and added cmake support and I've been using it in
production for over a year. See https://github.com/guru-florida/json-c

Colin

*Colin MacKenzie*

*FlyingEinstein.com <http://flyingeinstein.com/>*

**Comment by LeSpocky** [comment]
Today I had a look at the `CMakeLists.txt` currently part of json-c and there's a lot to improve. While I support the idea in general I recommend reading about modern CMake before merging pull requests for that:

* [It’s Time To Do CMake Right](https://pabloariasal.github.io/2018/02/19/its-time-to-do-cmake-right/)
* [The Ultimate Guide to Modern CMake](https://rix0r.nl/blog/2015/08/13/cmake-guide/)
* [Effective CMake](https://github.com/boostcon/cppnow_presentations_2017/blob/master/05-19-2017_friday/effective_cmake__daniel_pfeifer__cppnow_05-19-2017.pdf)

**Comment by guru-florida** [comment]
@LeSpocky Did you have a look at the one in my forked version? (link above your msg.) It is entirely different than the one here and doesnt rely on automake or other build tool. I'd welcome any comments and/or criticism.

**Comment by LeSpocky** [comment]
@guru-florida I had a short look at the Git history of your fork. Would it be possible for you to make a separate branch with your cmake related changes only and rebase on current master? That would make review easier, especially if you plan to make a pull request from that in the end.

**Comment by hawicz** [comment]
I took a quick peek at the CMakeLists.txt from guru-florida/json-c, and it seems to include much of the relevant checks that the autoconf code does.  If that can be extended to include the various other things that are done in autoconf (_REENTRANT handling, threading support, HAVE_ATOMIC_BUILTINS, etc...) then I'd be happy to merge those changes in.

**Comment by s0m30n3** [comment]
I just tried using cmake on HEAD and it works for me .. except pkg-config doesn't find json-c.pc.
I used find to make sure it wasn't in a hidden folder or something and no, it's not.
I see json-c.pc.in so I guess CMakeList.txt is missing something

**Comment by LeSpocky** [comment]
> I used find to make sure it wasn't in a hidden folder or something and no, it's not.
> I see json-c.pc.in so I guess CMakeList.txt is missing something

That got lost with f2e991a3419ee4078e8915e840b1a0d9003b349e …

**Comment by hawicz** [comment]
Re-added json-c.pc installation in commit 994e6c1

**Comment by s0m30n3** [comment]
Thanks but I have still an issue.

I build json-c with cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr [...] to avoid using -Wl,-rpath="/usr/local/lib/" in my Makefile.
I just wanna use a simple LDFLAGS += `pkg-config --libs json-c` which should work but doesn't.
I get many undefined reference to <json function>.

For me, `pkg-config --libs json-c` resolves to "-L -ljson-c". The "-L" switch is wrong preventing the linker to find json-c library. If I manually use "-ljson-c" it defaults to standard library path and works. Alternatively, if I specify "-L/usr/lib" it also works.
I guess you're doing -L$var but $var is "" for some reason.

**Comment by hawicz** [comment]
Currently installed json-c.pc seems to have the right entry ("Libs: -L${libdir} -ljson-c).

All autoconf machinery has been removed, and we're fully using cmake except for a couple of issues (#369, #370).
If anything else isn't working right, please open a new issue.
