### ISSUE TITLE
Json schema validation

### ISSUE THREAD

**Issue by simon-p-r** [json-c/json-c#339]
Hi

Just wondering if json schema is part of plans for this project, I found this [project ](https://github.com/ocedo/jsonschema-c) which uses json-c but it appears to be dead. 

Thanks

**Comment by jbboehr** [comment]
[libucl](https://github.com/vstakhov/libucl) claims to support json and has a json schema validator, although because of it's include directive, it's probably not usable for API request validation.

**Comment by hawicz** [comment]
I'm not planning on adding that, nor do I know of anyone else that is.  Having this feature as a library built on top of json-c, like ocedo/jsonschema-c is, seems like a perfectly reasonable way to do it, but if you or anyone else want to work on adding such a thing directly in json-c I wouldn't be opposed.
