### ISSUE TITLE
`INSTALL` overrides an automake script.

### ISSUE THREAD

**Issue by lhunath** [json-c/json-c#352]
The repository contains an `INSTALL` file at the root, which conflicts with automake's `INSTALL` script.  `autoreconf` kills the original file.  We should rename or remove `INSTALL` from the repo.

**Comment by hawicz** [comment]
Perhaps you are using an old version of autoconf?  I'm using 2.69-8, and running autoreconf does *not* do so for me.

Or, if you happen to be running autoreconf with the -f option, then don't do that.  https://unix.stackexchange.com/a/197327
