### ISSUE TITLE
VS2008 test  test_util_file.cpp err!

### ISSUE THREAD

**Issue by wenhuancai** [json-c/json-c#356]
1>test_util_file.obj : error LNK2001: 无法解析的外部符号 "int _json_c_strerror_enable" (?_json_c_strerror_enable@@3HA)  

i get warning ,when I link the Jsonlib .

c:\program files (x86)\microsoft visual studio 9.0\vc\include\string.h(126) : warning C4985: “_json_c_strerror”

what should i do ?

**Comment by hawicz** [comment]
No idea, I can't read that error.  Were you able to figure out how to get it working?

**Comment by hawicz** [comment]
Dup of #347
