### ISSUE TITLE
Cmake is Errir

### ISSUE THREAD

**Issue by wenhuancai** [json-c/json-c#364]
![ky 2k jt 7 m7fnpb](https://user-images.githubusercontent.com/20059816/30786771-7be241d2-a1ad-11e7-95e9-2de81327e4c4.png)
![wd q rz3gznxnqm5gx4fabr](https://user-images.githubusercontent.com/20059816/30786784-a1d15b08-a1ad-11e7-9814-fdf7334920d3.png)
in VS2013. i can't get correct sln.
now i get the sln is 
![wd q rz3gznxnqm5gx4fabr](https://user-images.githubusercontent.com/20059816/30786794-ce5fd820-a1ad-11e7-9660-8a0fae34fdb6.png)

**Comment by wenhuancai** [comment]
two  ( ./strerror_override.c )

**Comment by wenhuancai** [comment]
![fz fbuher3 k y 7 y1r](https://user-images.githubusercontent.com/20059816/30786799-f7fc9fa6-a1ad-11e7-9af2-26aea5d4cf02.png)

**Comment by hawicz** [comment]
I have some changes I've been working on to try to fix this.  I should be able to push them this weekend sometime.

**Comment by hawicz** [comment]
Commit 579f074 should fix this.
