### ISSUE TITLE
how to check  the json string,crash!

### ISSUE THREAD

**Issue by wenhuancai** [json-c/json-c#366]
if ( NULL != (jsroot = json_tokener_parse(content_)) )
	{
			for(size_t  i = 0; i < json_object_array_length(jsroot); i++ )
			{
                        }
        }
the  content_ is not json's string. The program will crash,because of json_object_array_length(jsroot).

**Comment by hawicz** [comment]
I don't see any evidence of a json-c bug here.  If content_ doesn't describe an array, then you can't use array functions on it, and I'm assuming that you probably have a object, like '{"foo":[1,2,3]}'.  If you still think there's a problem with the library, please provide a more complete code sample.

**Comment by wenhuancai** [comment]
Content_normal should be a json array.But Conten_t, for network reasons, causes the content_t I receive is not the correct json string.I hope I can rule out this mistake.Now,the program will be crash.\
So I wonder how I check json.@ @hawicz

**Comment by ploxiln** [comment]
`json_object_is_type(jsroot, json_type_array)`
http://json-c.github.io/json-c/json-c-0.12.1/doc/html/json__object_8h.html#ab6dc8b19f8da310e78f402f83d6ae6c5

**Comment by wenhuancai** [comment]
@ploxiln thank you! i don't know that the doc is exists.
