### ISSUE TITLE
Is json-c support "redirect" semantic?

### ISSUE THREAD

**Issue by waveness** [json-c/json-c#367]
Dear guys:
    I want to konw is json-c support "redirect" semantic ?
such as below test case:
======mytest.json==========
{
	"insert": {
		"mem1": "test mem1"
	},
	"people":{
		"name": "czb",
		"age": 23
	},
	"float": 1.20,
	"another":{
		"redirect" : "mytest2.json"
	}
}
=======mytest2.json=============
{
	"test2":"this is test2"
}

**Comment by hawicz** [comment]
Nope.  json-c just implements standard parsing of json objects.  If you want to layer some interpretation of certain field names and have that load some other json object from somewhere that's up to you.

You might want to consider using a "JSON Reference" style syntax: https://tools.ietf.org/id/draft-pbryan-zyp-json-ref-03.html  Although it seems to never have made it past the draft stage, it is used for things like the Swagger spec (https://swagger.io/specification/).  
In JSON reference syntax your first object might look a bit like:

{...
 "redirect": { "$ref": "file:mytest2.json" }
...}

Another option, which seems to be more recently maintained, but more complex, is JSON-LD: https://json-ld.org/

However, json-c doesn't implement anything like this.
