### ISSUE TITLE
How to build json-c library for android?

### ISSUE THREAD

**Issue by topilski** [json-c/json-c#369]
Hi, i tried next line: `CC="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc" LD="/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ld" ./configure --host=arm-linux-androideabi --with-sysroot=/opt/android-ndk/platforms/android-9/arch-arm` but configuration failed.

**Comment by hawicz** [comment]
Even were I to have any idea about how to build things on Android I doubt I'd be able to help you.  Care to expand on what you mean by "configuration failed"?

**Comment by topilski** [comment]
Hi, the output is: 

```
configure: error: in `/home/sasha/work/fastonosql/build/build_env_android/json-c':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

**Comment by topilski** [comment]
Ok, i builded for android but you didn't have any tutotial how to do it so what i did:
```
export PATH=$PATH:/opt/android-ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/
export SYSROOT=/opt/android-ndk/platforms/android-9/arch-arm/usr/
export LD=arm-linux-androideabi-ld
export CC="arm-linux-androideabi-gcc --sysroot=/opt/android-ndk/platforms/android-9/arch-arm"
./autogen.sh
./configure
make
make install
```

**Comment by topilski** [comment]
And in CMakeLists.txt you execute ./configure, this is only workaround, you need to write cmake properly without external exec_program, because for example i have cmake toolchan file for android, or other system which won't work for this solution.

**Comment by PrithviBoddu** [comment]
Is there any Android.mk file for the library
