### ISSUE TITLE
Eclipse error 

### ISSUE THREAD

**Issue by maramej** [json-c/json-c#376]
I'm trying to use it in Eclipse, but I add it in GCC Linker, but when I compile it has the following error: can not find -ljson-c

Any idea?

**Comment by hawicz** [comment]
Are you building json-c itself, or program that uses it.?
If the latter, my guess is that you need to set the library path to point to whereever libjson-c is installed.
https://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.cdt.doc.user%2Freference%2Fcdt_u_prop_general_pns_libpath.htm

**Comment by maramej** [comment]
![tela1](https://user-images.githubusercontent.com/10420776/32995759-37f95bd4-cd60-11e7-9a36-1d6cd34dca86.png)
![tela2](https://user-images.githubusercontent.com/10420776/32995760-381dc398-cd60-11e7-8ead-42c36592c35a.png)
![tela4](https://user-images.githubusercontent.com/10420776/32995761-3863cd5c-cd60-11e7-8984-05664231cfdb.png)

Good afternoon. It is already configured in Eclipse, I even use other libraries, such as LibCurl, for example. But I checked the other libraries I have files in the `/ inc` folder and files with extension `* .so` in the / lib folder. In the json-c installation package I do not have these files. And at the time of compiling, I set the settings according to the attached image, however it says not find. Would you help me?
