### ISSUE TITLE
on gcc 7.2.0 on my linux distribution with json-c  2013-04-02 source

### ISSUE THREAD

**Issue by Rodartist** [json-c/json-c#377]
there were errors : which i had to edit a few files for to get it to go
i think these are the main errors where // fallthrough, // -fallthrough, or //fallthrough would have it compiling

json_object.c 
line 548 `
        if (json_parse_int64(jso->o.c_string.str, &cint) == 0) return cint;  //`
fallthrough
line 549
`  default: // fallthrough`

line 608
```
    if(sscanf(jso->o.c_string.str, "%lf", &cdouble) == 1) return cdouble; // fal
lthrough
```
line 609
`  default: // fallthrough`

i think thats all but it really got going once i figured to download the previous version rather than 0.12.1
though 0.12 use to be in this distribution before it was removed.

oh well. first time doing it was something new for me

**Comment by hawicz** [comment]
Fixed by PR#365 (commit ddc97b2)
