### ISSUE TITLE
 Eclipse: library (libjson-c) not found, but configured

### ISSUE THREAD

**Issue by maramej** [json-c/json-c#378]
Good afternoon. It is already configured in Eclipse, I even use other libraries, such as LibCurl, for example. But I checked the other libraries I have files in the / inc folder and files with extension * .so in the / lib folder. In the json-c installation package I do not have these files. And at the time of compiling, I set the settings according to the attached image, however it says not find. Would you help me?
![tela4](https://user-images.githubusercontent.com/10420776/32995956-4ac18e00-cd63-11e7-917d-3f5559f7b4e9.png)
![tela1](https://user-images.githubusercontent.com/10420776/32995957-4ae60988-cd63-11e7-8e62-f382548e6d84.png)
![tela2](https://user-images.githubusercontent.com/10420776/32995958-4b09d41c-cd63-11e7-8842-34acbe98feaa.png)

**Comment by ploxiln** [comment]
Sorry, this project is not the right place to ask about using eclipse.

json-c has to be built somehow, and the resulting library and header needs to be installed somewhere. If you understand how to do that manually, and you find and can isolate a specific bug in the json-c build system, you can report it here. But if you don't know how to build and install c libraries in general, or for the IDE you are using, this project can't help you, sorry.

**Comment by maramej** [comment]
@ploxiln 
Since you are trying to help me, I am not able to compile due to the following error:

json_object.c: 777: undefined reference to `_finite '
json_object.c: 773: undefined reference to `_isnan '

How do I resolve the following?

**Comment by ploxiln** [comment]
Those are from https://github.com/json-c/json-c/blob/json-c-0.12.1-20160607/math_compat.h which is theoretically should only apply on windows platforms - on other platforms the configure checks should pass: https://github.com/json-c/json-c/blob/json-c-0.12.1-20160607/configure#L4786-L4796

did you run `./configure`?

**Comment by maramej** [comment]
When U try ./ configure after sh autogen.sh, the following error:

./configure: line 2798: syntax error near unexpected token `autoconf-archive/m4'
./configure: line 2798: `AC_CONFIG_MACRO_DIRS(autoconf-archive/m4)'

Any ideia?

**Comment by ploxiln** [comment]
Clearly, configure isn't working.

  *  What exact version of json-c are you using?
  *  Was there a configure script already there before you ran `./autogen.sh`? Did you try using it as-is?
  * What versions of autoconf and automake do you have installed?
  * Can you show more output from ./autogen.sh and ./configure.sh? There are probably other error messages.

**Comment by hawicz** [comment]
I suspect the minimum autoconf and automake versions specified in the "Prerequisites" section of https://github.com/json-c/json-c/blob/master/README.md (2.64 and 1.10.3, respectively) are a bit too old.
According to https://autotools.io/autoconf/macros.html, you'll need at least automake version 1.13 or autoconf 2.70 to get the AC_CONFIG_MACRO_DIRS macro.
If you don't have a convenient package for your OS to install versions that recent you should be able to follow the "Manually install and build autoconf, automake and libtool" steps at the end of the README.md, which *does* specify new enough versions.

**Comment by hawicz** [comment]
Actually, looking at your screenshots again, based on what your file browser windows look like I suspect that you're trying to build something on MS Windows.  If that is the case, .so files are totally the wrong things to be trying to link again.
If we ignore that problem, even just trying to build in Eclipse you're going to have a hard time unless you're quite familiar with what you're doing, especially since you're trying to use the rather old 0.12 branch.  You'll have better luck with the most recent json-c code, and perform the json-c build with cmake and Visual Studio.
Another option is that you can try using the pre-built library over at https://ci.appveyor.com/project/hawicz/json-c
