### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by goodandrewsoft** [json-c/json-c#380]
Hello, anybody give step by step instruction for noobs, how build json-c on windows?

**Comment by hawicz** [comment]
If you just want something to use, the easiest thing to do is probably to grab a pre-built library from from https://ci.appveyor.com/project/hawicz/json-c, such as https://ci.appveyor.com/api/buildjobs/wd290j65dbwa9jmn/artifacts/json-c.lib.zip

If you really want to built it, there are some brief instructions at https://github.com/json-c/json-c/blob/HEAD/README.html
