### ISSUE TITLE
Problem serializing double

### ISSUE THREAD

**Issue by michelboaventura** [json-c/json-c#394]
Hi,

First of all, thank you for 0.13 release! I have a json intensive code which became 30% faster by just upgrading libjson! :1st_place_medal: 

Second, I need to serialize some doubles using always two decimal places. On version 0.12 I had to use ``json_object_new_double_s``. But with 0.13 I started playing with ``json_object_set_serializer``, which I think has an issue. If I use ``%.2f`` to serialize a number like 12.34, everything works as expected. But if I try to serialize ``12.0``, I get ``12.00.0``.

I think the problem is with:
https://github.com/json-c/json-c/blob/cfd09c87f0227b0a4c4a3666a7d6d744be9d5775/json_object.c#L823-L828

Since ``modf(12.0, &dummy) == 0``, the code concatenates the ``.0``

The doc says I should use the ``%g`` print format, but I couldn't find a way to fix two decimal places.

**Comment by hawicz** [comment]
oops, yeah, that's a bug.  I'm working on some changes to make it work better.

**Comment by hawicz** [comment]
Should be fixed by commit d5da847.  Let me know if that fixes it for you, and I'll merge it over to the 0.13 branch.

**Comment by hawicz** [comment]
Pushed to 0.13 too as commits 8270e83 and a70466e

**Comment by michelboaventura** [comment]
Great! Thank you very much. I will try it after NYE and let you know if I find any issue.

Cheers
