### ISSUE TITLE
Key gets modified if it contains "\"

### ISSUE THREAD

**Issue by singhgaurav1302** [json-c/json-c#395]
json_object_object_add(object, "abc\def\ghi", value);
::std::string data(json_object_to_json_string(object));
cout << data << endl; 

if the key contains "\\", the content of key is getting changed to "abc\\/def\\/ghi" which is not intended.

**Comment by hawicz** [comment]
Your code can't possibly compile cleanly in the form that you listed it here: \d and \g are undefined escape sequences.  If you ignore the compiler warnings, and try to use it anyway, then the backslashes are just dropped, and you end up with a string that just contains "abcdefghi".

On the other hand, if you have *forward* slashes in the string, then the inclusion of the backslashes in the result from json_object_to_json_string() **is** the intended output.
Please see json_object_to_json_string_ext() and [JSON_C_TO_STRING_NOSLASHESCAPE](http://json-c.github.io/json-c/json-c-0.13/doc/html/json__object_8h.html#a5c11d72c55f3ab7c088f19e7bf118163) if you want to change that behavior.

**Comment by singhgaurav1302** [comment]
Hello,
Sorry for backward slashes, actually I am dealing with forward slashes only as you mentioned.
But the version of json we are using does not have  JSON_C_TO_STRING_NOSLASHESCAPE.
As per the file json_c_version.h I am using JSON_C_VERSION "0.12.99" and i guess fix to escape forward slashes was introduced in later versions.

Is there any workaround in the version I am using.

**Comment by hawicz** [comment]
That flag was added in commit 316da858, back at the end of 2015.  It sounds like you're working off of a very old development version of json-c (somewhere between 2014/04/10 and 2015/11/28) and you should upgrade.
You could try backporting that change to your version, or just hack up your version of json-c to always skip the escaping of forward-slashes, but you'd be missing out on hundreds of other changes and bug fixes, so I wouldn't recommend it.
