### ISSUE TITLE
update json object with key.

### ISSUE THREAD

**Issue by vehere-ccu1** [json-c/json-c#397]
Hi,
I'm trying to update json object with key but it's not taking new value:- 

Current json string is like[rules_list] :- 
{ 
	"324981": { "_id": 324981, "description": "Creating event Alert", "category": "Category Of the threat", "severity": 1,
	"alert": { "enabled": false }, "mail": { "enabled": false, "to": "chirxxxxx_dey@outlook.com" }, "syslog": { "enabled": true },
	"keyword": "hello*world", "condition": { "all": [ { "fact": "ip.src_city", "operator": "contains", "value": "mumba" } ] } } 
}

rule_id_as_key="324981"
rule :- 

	"324981": { "_id": 324981, "description": "Creating event Alert", "category": "Category Of the threat", "severity": 1,
	"alert": { "enabled": false }, "mail": { "enabled": false, "to": "chirxxxxx_dey@outlook.com" }, "syslog": { "enabled": true },
	"keyword": "hello*world", "condition": { "all": [ { "fact": "ip.src_city", "operator": "contains", "value": "mumbai" } ] } } 

json_object_object_del(rules_list,rule_id_as_key);
json_object_object_add(rules_list,rule_id_as_key,rule);

Then After[rules_list] :-  

{ 
	"324981":""
}

**Comment by hawicz** [comment]
How are you creating "rule"?   Are you freeing it after calling json_object_object_add()? (you shouldn't be)

**Comment by vehere-ccu1** [comment]
Thanks hawicz,

I fixed the issue,There is no problem with json-c.
After calling json_object_object_add(rules_list,rule_id_as_key,rule),
I was calling json_object_object_put(rule); [As json-c is new for me].
