### ISSUE TITLE
Segmentation fault when double quotes is used 

### ISSUE THREAD

**Issue by kalwar** [json-c/json-c#403]
Quit anyway? (y or n) y
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...

(gdb) run
Starting program: xxx.c
[Thread debugging using libthread_db enabled]
Detaching after fork from child process 31510.
Detaching after fork from child process 31511.
Detaching after fork from child process 31512.
Detaching after fork from child process 31514.
[New Thread 0x7fffee123700 (LWP 31515)]
[New Thread 0x7fffed722700 (LWP 31516)]
[Thread 0x7fffee123700 (LWP 31515) exited]
[Thread 0x7fffed722700 (LWP 31516) exited]
[New Thread 0x7fffed722700 (LWP 31520)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5e3859b in json_object_object_add () from /lib64/libjson-c.so.2
Missing separate debuginfos, use: debuginfo-install audit-libs-2.4.5-6.el6.x86_64 glib2-2.28.8-9.el6.x86_64 glibc-2.12-1.209.el6_9.2.x86_64 json-c-0.11-13.el6.x86_64 keyutils-libs-1.4-5.el6.x86_64 krb5-libs-1.10.3-65.el6.x86_64 libcom_err-1.41.12-23.el6.x86_64 libgcc-4.4.7-18.el6.x86_64 libselinux-2.0.94-7.el6.x86_64 libstdc++-4.4.7-18.el6.x86_64 libxml2-2.7.6-21.el6_8.1.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 openssl-1.0.1e-57.el6.x86_64 pam-1.1.1-24.el6.x86_64 protobuf-c-0.15-2.el6.x86_64 zlib-1.2.3-29.el6.x86_64
(gdb) quit 
A debugging session is active.

    Inferior 1 [process 31505] will be killed.

Quit anyway? (y or n) y
-bash-4.1$ echo "eyJxdWVyeSI6eyJzaW1wbGVfcXVlcnlfc3RyaW5nIjp7InF1ZXJ5IjoiZGVtbyIsImZpZWxkcyI6WyJfYWxsIl0sImFuYWx5emVyIjoic3RhbmRhcmQiLCAiZGVmYXVsdF9vcGVyYXRvciI6ICJhbmQiLCAib3IifX19" | base64 -d 
{"query":{"simple_query_string":{"query":"demo","fields":["_all"],"analyzer":"standard", "default_operator": "and", "or"}}}-bash-4.1$

**Comment by hawicz** [comment]
What the code?

**Comment by hawicz** [comment]
This seems to work fine for me.  Calling json_tokener_parse() on invalid input returns NULL.  If you then pass NULL to json_object_object_add and you're using a version of json-c before commit f8132f9 (i.e. v0.12.1 or earlier), which added some explicit asserts on what is passed in, then you can expect a segv crash.
This has nothing to do with double quotes, and it doesn't appear that there is any bug in json-c, so I'm closing it.
