### ISSUE TITLE
Undefine NDEBUG for tests

### ISSUE THREAD

**Issue by nehaljwani** [json-c/json-c#406]
Our build system defines `-DNDEBUG` via `CPPFLAGS` for release builds. Because of this, the tests don't compile. 

```
  CC       test2.o                                                                                                                                                                                        [21/1905]
  CCLD     test2
  CC       test4.o
  CCLD     test4
  CC       testReplaceExisting.o
  CCLD     testReplaceExisting
  CC       test_parse_int64.o
  CCLD     test_parse_int64
  CC       test_deep_copy.o
test_deep_copy.c: In function 'main':
test_deep_copy.c:201:14: error: unused variable 'special_output' [-Werror=unused-variable]
  const char *special_output = json_object_to_json_string(dest_with_serializer);
              ^~~~~~~~~~~~~~
test_deep_copy.c:198:8: error: unused variable 'dst_userdata' [-Werror=unused-variable]
  char *dst_userdata = json_object_get_userdata(dest_with_serializer);
        ^~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [test_deep_copy.o] Error 1
make[2]: Leaving directory `/home/nwani/m3/conda-bld/json-c_1520910223423/work/tests'
make[1]: *** [check-am] Error 2
make[1]: Leaving directory `/home/nwani/m3/conda-bld/json-c_1520910223423/work/tests'
```

I think all all tests should have:
```
#ifdef NDEBUG
#/**/undef/**/ NDEBUG
#endif
```

But I couldn't find a header file common to only tests.

**Comment by hawicz** [comment]
Sure, a header for the tests sounds like a good idea.

**Comment by andy5995** [comment]
@neh , I submitted #497

**Comment by hawicz** [comment]
Rather than a header, how about just finding a way to tack on -UNDEBUG to the compile line for the tests?  It seems like that'd be a simpler change.

**Comment by andy5995** [comment]
What if I did a PR to make this change?

`AM_CPPFLAGS = -I$(top_srcdir) -I$(top_srcdir)/tests -UNDEBUG`

in https://github.com/json-c/json-c/blob/a91aa5e35d0e2b6a5ed00ad6ae870d4918511ff0/tests/Makefile.am#L2 ?

**Comment by hawicz** [comment]
Yeah, that should work, even with CPPFLAGS being overridden.

**Comment by andy5995** [comment]
Actually, what do you think of using this solution instead?

https://www.gnu.org/software/autoconf-archive/ax_check_enable_debug.html

that would add this option to ./configure:

`--enable-debug=[yes/info/profile/no]
                          compile with debugging`

and I'm pretty sure NDEBUG wouldn't get defined when "no" is used. I could try it and test, but what's the easiest way to make sure something is or isn't defined? I experimented a little with `nm`,  but that didn't show me.
