### ISSUE TITLE
json_tokener_parse is crash 

### ISSUE THREAD

**Issue by wenhuancai** [json-c/json-c#407]
当解析空的utf8文件的时候，调用json_tokener_parse（） 会导致崩溃
![image](https://user-images.githubusercontent.com/20059816/37747545-b21219e6-2dba-11e8-80bb-2f650acdb147.png)
![image](https://user-images.githubusercontent.com/20059816/37747588-ec0789d8-2dba-11e8-8f57-eba4effe2022.png)

	content_ = new char[content_size_ + 1];
content_  = 3 .  是utf8的文件头

**Comment by hawicz** [comment]
Per google translate "当解析空的utf8文件的时候，调用json_tokener_parse（） 会导致崩溃" seems to be:
"Calling json_tokener_parse() causes a crash when parsing an empty utf8 file"
and "3 . 是utf8的文件头" is "3 is the utf8 file header"

Do you mean you're passing in a buffer that only contains a UTF-8 byte order mark (BOM), i.e. 0xEF 0xBB 0xBF ?  As far as I can tell, that works perfectly fine.  i.e., using the test code included with json-c:

```
cd tests
make USE_VALGRIND=0 check   # just to ensure everything is built
echo EFBBFE | xxd -r -p > valid.json
./test_util_file.test
```
Which correctly produces;

> FAIL: unable to parse content of ./valid.json: (null)
> ...other errors...

and a testSubDir/test_util_file/test_util_file.vg.out with no errors.

Please provide more information about where exactly the crash happens, ideally in the form of a *complete* example that demonstrates the problem.

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/37750183-a3c1f8b4-2dc6-11e8-8ce5-959011b0f14e.png)
![image](https://user-images.githubusercontent.com/20059816/37750196-b93d4ad6-2dc6-11e8-8d51-2f85f4769ad6.png)
[1.txt](https://github.com/json-c/json-c/files/1836013/1.txt)

**Comment by wenhuancai** [comment]
I pulled the code out, and there was a crash. 
  run if (NULL != (jsroot = json_tokener_parse(content_)))
When you debug this line, it crashes.
![image](https://user-images.githubusercontent.com/20059816/37750335-60103904-2dc7-11e8-98c4-574d5f41b9b4.png)
content_ is . 0xEF 0xBB 0xBF

**Comment by hawicz** [comment]
Looks like that's because the char type is signed, and the cast that json_tokener() does when calling isspace() is wrong, and ends up turning 0xBF into -65 instead of 191.
Try changing this line in json_tokener.c (s/b line 298):
```
      while (isspace((int)c)) {
```

to:
```
      while (isspace((unsigned char)c)) {
```

and let me know if that helps.  

Assuming that works, there are a few other places that need to be fixed too.

**Comment by wenhuancai** [comment]
thank you ! There is no problem now.Why is it that your test is okay? It's an environmental problem.

**Comment by hawicz** [comment]
The first line of your error popup provides a clue: "Debug assertion failed"
I expect that you're running with debug assertions enabled, and MS VC++ considers anything outside of the range [-1,255] to be invalid (an entirely reasonable check).
In contrast, the ctype functions on (some versions of?) Linux (but not necessarily other unix variants) seem to have explicit support for code that uses the wrong cast:
"we also support negative `signed char' values for broken old programs"
https://sourceware.org/git/?p=glibc.git;a=blob;f=ctype/ctype.h;h=0e0936ac9565350672cc73bc978fdfafc2753024;hb=HEAD#l74

**Comment by wenhuancai** [comment]
Now, when my program runs, I always have popovers. But I have added the crash library, which should not happen.Will it be a json library?
The broken window was not shown useful information. And I can't reproduce it. Do you have any good methods?

**Comment by hawicz** [comment]
The crashes in isspace should be fixed with the most recent code..  However, if you want to parse a JSON message from a file with a BOM at the start you'll need to detect and skip that yourself.
Adding support for doing so to json_object_from_file/json_object_from_fd would be reasonable (although adding that to json_tokener_parse not so much, since it has no way of knowing whether you're actually at the beginning of a file), but that's really a new feature that shouldn't be tracked as part of this issue.

**Comment by hawicz** [comment]
I'm sorry, I'm having trouble decoding what you said in your last comment.  Are you still having an issue even with the change in the cast to use (unsigned char)?

**Comment by wenhuancai** [comment]
![image](https://user-images.githubusercontent.com/20059816/37889674-1fb12d96-3100-11e8-968e-ae0745fa53e7.png)
![image](https://user-images.githubusercontent.com/20059816/37889690-2fdc62da-3100-11e8-9600-073821c89cee.png)
```
CString GPSParse::prasejson(const char * content,CString &strLng,CString &strLat)//
{
	json_object *jsroot = NULL, *jobj = NULL, *jobj2 = NULL;
	json_object *jarray = NULL;
	CString str_x, str_y;
	CString strBackupFile;

	if (NULL != (jsroot = json_tokener_parse(content)))
	{
		if (NULL != (jobj = json_object_object_get(jsroot, "status")))
		{
			if (0 == json_object_get_int(jobj))
			{
				jarray = json_object_object_get(jsroot, "result");
				if (!json_object_is_type(jarray, json_type_array))
				{
					if (jsroot != NULL) json_object_put(jsroot);
					return "";
				}
				
				for (size_t i = 0; i < json_object_array_length(jarray); i++)
				{

					jobj = json_object_array_get_idx(jarray, i);
					if (NULL != (jobj2 = json_object_object_get(jobj, "x")))
					{
						str_x = json_object_get_string(jobj2);
						strLng = str_x.Mid(0, str_x.Find('.') + 6);//取6位精度
																  //str_x.Format(_T("%s"),)
					}
					if (NULL != (jobj2 = json_object_object_get(jobj, "y")))
					{
						str_y = json_object_get_string(jobj2);
						strLat = str_y.Mid(0, str_y.Find('.') + 6);//取6位精度
					}
				}

			}
		}
	}
		if (jsroot != NULL) json_object_put(jsroot);
			return strLng + "," + strLat;
}
```

**Comment by wenhuancai** [comment]
why json_tokener_parse is crash?

**Comment by wenhuancai** [comment]
@hawicz

**Comment by hawicz** [comment]
Well, it's crashing in the first couple setlocale() calls, i.e.:
https://github.com/json-c/json-c/blob/master/json_tokener.c#L283

```
  {
    char *tmplocale;
    tmplocale = setlocale(LC_NUMERIC, NULL);
    if (tmplocale) oldlocale = strdup(tmplocale);
    setlocale(LC_NUMERIC, "C");
  }
```

but as far as I can tell the locale handling there is fine.  The fact that it crashes in HeapFree makes me think that setlocale is at the point where it's trying to free the previously set locale, but unless you have memory corruption of some kind I don't know how that would cause a problem.

I notice that you aren't guaranteed to have strLng and strLat set, but you're using both of them anyway at the end of the function.  However, I think at most that would cause you to use a stale value from a previous call to prasejson [sic], so it shouldn't cause a crash.

It seems like something is stomping on your heap, but I have no idea what.  You might want to try some heap debugging approach, such as _CrtCheckMemory as described at https://msdn.microsoft.com/en-us/library/974tc9t1.aspx (I've never used this, it was just the first thing that popped up in my search results)

**Comment by wenhuancai** [comment]
https://blog.csdn.net/atceedsun/article/details/52839623
It looks like this function can only be called globally once.
There was no problem before, since you released V13, the program often crashed in this location.
![image](https://user-images.githubusercontent.com/20059816/37944465-45ac6232-31ae-11e8-8e47-dca7a8a712af.png)
Yesterday I modified the parse json code without using the json-clib. Everything is fine now. So I think it's a question of setlocale. You should just initialize it once.

**Comment by wenhuancai** [comment]
https://blog.csdn.net/xiejianjun417/article/details/8859500
I should have chosen MD at compile time instead of MT.

**Comment by hawicz** [comment]
That code can't just initialize it once, because it is specifically switching it back and forth between the non-"C" locale and the "C" locale so parsing works correctly.  Unfortunately, doing so introduces a limitation that parsing can't reliably done in multiple threads simultaneously, which is what that link that you mentioned seems to be saying.
The alternate code which uses uselocale() wouldn't have this issue, since uselocale() is defined to be thread-specific, but I guess that's not available on Windows.  Having the json-c library call _configthreadlocale( _ENABLE_PER_THREAD_LOCALE) doesn't seem like something it should be doing, but I suspect that if you were to do that yourself before calling json-c functions then things would work better.

**Comment by hawicz** [comment]
See issue #409 for any additional thoughts about setlocale problems.
