### ISSUE TITLE
bug in array_list_del_idx when array_list_length()==1

### ISSUE THREAD

**Issue by smdjeff** [json-c/json-c#408]
calling array_list_del_idx( arr, i, 1 ) several times.
once array_list_length()==0, from then on array_list_del_idx,free_fn keeps getting called over and over on that same pointer.

**Comment by smdjeff** [comment]
note that your unit test only tests json_object_array_del_idx where i = 0

**Comment by hawicz** [comment]
Deleting a non-existent array element is not a valid operation, don't do that.  However, let's say you do anyway, the code at https://github.com/json-c/json-c/blob/master/arraylist.c#L139 will prevent the free_fn from being called:
```
if ( idx >= arr->length || stop > arr->length ) return -1;
```

How are you actually causing a problem to occur?

**Comment by smdjeff** [comment]
Sorry. Wrong title.  It's when it's Len=0

**Comment by hawicz** [comment]
*how* is it called incorrectly?  As far as I can tell, it works perfectly fine.  e.g.:
```
#include <stdio.h>
#include "arraylist.h"

void free_func(void *foo)
{
        printf("free called on %p\n", foo);
}
int main()
{
        struct array_list *al;
        al = array_list_new(free_func);
        array_list_add(al, "somedata");
        printf("first call\n");
        array_list_del_idx(al, 0, 1);
        printf("second call\n");
        array_list_del_idx(al, 0, 1);
        printf("third call\n");
        array_list_del_idx(al, 0, 1);
        printf("freeing\n");
        array_list_free(al);
}
```

Produces:

> first call
> free called on 0x400957
> second call
> third call
> freeing

Note the lack of calls to free for the second and third call.

**Comment by smdjeff** [comment]
Try it where those zeros arent always zeros.

**Comment by hawicz** [comment]
Closing, since it works fine as far as I can tell.  If you have an actual test case that demonstrates the problem, feel free to provide it and reopen.
