### ISSUE TITLE
how to read object of type `json_object *` in c++

### ISSUE THREAD

**Issue by boddumanohar** [json-c/json-c#413]
I am working on an application where two process exchange data through shared memory. So instead of using structs to pack the data, I choose to use JSON so that I won't face any issues due to compilers.

My sender side is written in C and the receiver side is written in C++14 code. 

On my sender side, I can just use 
```
json_object * jobj = json_tokener_parse(string);
```
and copy this `jobj` into the shared memory region.

On the reciver side, which is C++, how do I read get the json data from the `json_object * ` object?

I really appreciate the help.

**Comment by ploxiln** [comment]
Looks like #412 again.

**Comment by ploxiln** [comment]
You should be able to `#include <json-c/json.h>` and call json-c functions the same way in C++ as you do in C.

**Comment by boddumanohar** [comment]
Thanks @ploxiln, this solves my problem.
