### ISSUE TITLE
[Question] How JSON-c stores the serialized data in memory?

### ISSUE THREAD

**Issue by boddumanohar** [json-c/json-c#414]
Json-c allows to parse JSON data in C lang. JSON is plain text based serialized data. How does json-c preserve the serialization with in the `json_object *` struct?

I am trying to understand how json-c work. Helping me understand this question will solve a doubts for me.
Thanks.

**Comment by hawicz** [comment]
For the most part, it doesn't.  When you want to get back the serialized text, the json_object_to_json_string_ext() function generates it anew.  (except for a special case for floating point numbers)
