### ISSUE TITLE
json_tokener_parse  json_object_object_get_ex with string value which is json string

### ISSUE THREAD

**Issue by kingmayko** [json-c/json-c#417]
for some result, I  need jsonString with below
```
char* config = "{
  \"key\" :\" {\" key1\": \"value1\"} \"
}";


json_object* test,  *test2;
test = json_tokener_parse(config);
int result = json_object_object_get_ex(test, "key", &test2);  
```
and
result is always false

**Comment by hawicz** [comment]
That's not valid json.  Without the escaping, what you're trying to parse is:

> { "key": " {" key1": "value1"} " }
Note that the value for key "key" is just " {", and key1... is invalid after that point.

You probably want a few more backslashes in there.
