### ISSUE TITLE
Suggestion: document (and define) that json_object_put() accepts NULL pointer to object

### ISSUE THREAD

**Issue by barsnick** [json-c/json-c#419]
In all implementations (old and current) of json_object_put() which I checked, its code handles being passed a NULL pointer as an object just fine.

If this is by design and meant to stay this way, it would be nice if this were documented.
https://github.com/json-c/json-c/blob/4414d068b308bff4fd98c83e1ae08346913f93c4/json_object.h#L200

It would save the user from doing
```
if (obj) {
    json_object_put(obj);
}
```
i.e. it would also work if some previous json-c call returned a NULL pointer.

**Comment by hawicz** [comment]
Yes, passing a NULL to json_object_put() has always been safe.
