### ISSUE TITLE
json_object_get_double() does not set errno when there is no valid conversion

### ISSUE THREAD

**Issue by mpratt9521** [json-c/json-c#422]
The documentation for json_object_get_double states, in part:

> Strings will be parsed as a double. If no conversion exists then 0.0 is returned and errno is set to EINVAL.

However, errno is not set in this case. Here is an example program:

```
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <json-c/json.h>

int main(int argc, char** argv)
{
    const char* json_str = "{ \"X\" : \"asdf\" }";
    struct json_object* json = json_tokener_parse(json_str);
    struct json_object* value = NULL;

    errno = 0;
    json_object_object_get_ex(json, "X", &value);
    double x = json_object_get_double(value);
    printf("%s (%d): %s -> %f\n", strerror(errno), errno, json_object_get_string(value), x);
}
```

This outputs the following:

> Success (0): asdf -> 0.000000

0.0 is returned, as expected, but errno is not set to EINVAL to indicate conversion failure.

**Comment by hawicz** [comment]
True, this is due to to strtod() not setting errno except on underflow or overflow.  Looks like there are a couple of places around https://github.com/json-c/json-c/blob/master/json_object.c#L953 where we should be setting errno explicitly.
