### ISSUE TITLE
Parse string contains "\" or "/" errors

### ISSUE THREAD

**Issue by gdchnly** [json-c/json-c#424]
when parse json string like {"type": "a\c"}, json_tokener_parse return NULL.
when parse json string like {"type": "a/c"}, json_object_to_json_string will return { "type": "a\/c" }, there is one extra escape character

**Comment by hawicz** [comment]
That sounds fine to me.  \c is not a valid escape sequence in JSON (see chapter 7 of https://tools.ietf.org/html/rfc7159.html)

If you don't want forward slashes to be escaped in the output, i.e.:

    { "type": "a\/c" }

(which seems to be what you tried to say above, but github's markdown hides the backslash), then pass the JSON_C_TO_STRING_NOSLASHESCAPE flag when calling json_object_to_json_string_ext().

**Comment by gdchnly** [comment]
3Q, I misunderstood it.
