### ISSUE TITLE
CMake: builds involving this target will not be correct

### ISSUE THREAD

**Issue by TheAifam5** [json-c/json-c#427]
Hey!

I'm get an warning when I try to compile it using CMake:
`warning: multiple rules generate thirdparty/json-c/json-c.lib. builds involving this target will not be correct; continuing anyway [-w dupbuild=warn]`

I think that's because the project does not have switch between static library and dynamic library, and also because of: `set_target_properties(json-c-static PROPERTIES OUTPUT_NAME json-c)`

Without that `set_target_properties` I'm don't get any warnings.

Regards,
Mateusz

**Comment by ploxiln** [comment]
looks related to #415

**Comment by TheAifam5** [comment]
On windows you try to set the same name for shared and static libraries using ‚set_target_properties‘. Simple if with NOT (MSVC OR MINGW OR WIN32) etc should be enough.

**Comment by hawicz** [comment]
s/b fixed by merging the changes in #415.
