### ISSUE TITLE
json_object_object_del() and Segmentation fault

### ISSUE THREAD

**Issue by santosh0705** [json-c/json-c#430]
I searched for similar issue but didn't get any so posting my issue here. The below code is resulting Segmentation fault. The line which causing has been marked. If I comment the line there is no errors. Can't figure out why it is not working. I want to release all the memory used by json-c once I read the values from json.

Code:
```
    struct json_object *obj = json_tokener_parse(addr); // <- Reading JSON from file
...
...
    struct json_object *v_obj, *p_obj;
    if (json_object_object_get_ex(obj, "listen", &v_obj)) {
        if (json_object_object_get_ex(v_obj, "port", &p_obj))
            port = json_object_get_int(p_obj);
        if (json_object_object_get_ex(v_obj, "ip", &p_obj))
            ip = json_object_get_string(p_obj);
    }
    json_object_object_del(p_obj, ""); // <- This cause Segmentation fault
    json_object_object_del(v_obj, "");
    json_object_object_del(obj, "");
```

Json:
```
{
  "listen": {
    "port": 3000,
    "ip": "127.0.0.1"
  },
...
...
}
```

**Comment by ploxiln** [comment]
If you want to free the entire `obj`, just `json_object_put(obj)`, and you remove all your calls to `json_object_object_del()`. `json_object_object_get_ex()` does not increase the reference count on the children, so just freeing the root will free the whole tree.

It does not make sense to call `json_object_object_del()` when an empty string for the object member key to be deleted.

**Comment by hawicz** [comment]
What @ploxiln said, but also: if you're want to keep using the string after freeing the object, you need to copy it, perhaps with strdup.

http://json-c.github.io/json-c/json-c-0.13.1/doc/html/json__object_8h.html#a9ee29ca8d79896e15007131527f6002e
"... The returned string memory is managed by the json_object and will be freed when the reference count of the json_object drops to zero."

**Comment by santosh0705** [comment]
Got it. Thank you so much 😄

**Comment by santosh0705** [comment]
`json_object_put(jobj)` was working with older version (v0.11-4) of json-c from CentOS 7 base repository. 

But with the latest version of json-c compiled from source I'm getting below error:
```
json_object.c:189: json_object_put: Assertion `jso->_ref_count > 0' failed.
```

**Comment by santosh0705** [comment]
Still I'm not getting how `json_object_put()` works 😞 

I've two json objects in my program:
```
    struct json_object *conf = json_object_new_object();
    struct json_object *jobj = NULL;
...
...
    jobj = json_tokener_parse_ex(tok, buf, st.st_size);
...
...
    json_object_put(conf);
    if (jobj != NULL)
        json_object_put(jobj);
```

If i delete any of the two `json_object_put()` than I'm not getting any errors.
Someone please help me to correctly use `json_object_put()`.

**Comment by santosh0705** [comment]
Got it working. Few sub-objects of `conf` were referencing sub-objects in `jobj` due to which it was happening.
Used `json_object_deep_copy()` to copy the sub-objects from `jobj` and added in `conf`.
