### ISSUE TITLE
error  in configure file

### ISSUE THREAD

**Issue by itssivashankar** [json-c/json-c#442]
Hi,
I am trying to build json-c using  (./congigure) command i am getting this error on  **coreos.**
so, kindly help me to solve this error 

./configure: line 12361: syntax error near unexpected token `-Wall'
./configure: line 12361: `AX_APPEND_COMPILE_FLAGS(-Wall -Werror -Wcast-qual -Wno-error=deprecated-declarations)'

**Comment by hawicz** [comment]
What version of the code are you using?  If you're using a release tarball or branch, that error shouldn't be possible.  If you're using the most recent code from the master branch, you need to make sure you have a recent enough version of autoconf and automake.  See https://github.com/json-c/json-c/blob/master/README.md

**Comment by itssivashankar** [comment]
i am using the latest version autoconf(2.69)

**Comment by itssivashankar** [comment]
their is no error on autogen.sh i am getting error only on the **configure** file  
can you tell me what is the reason for the error

**Comment by ploxiln** [comment]
`./autogen.sh` is how `configure` is generated. Your error looks like you just renamed `configure.ac` to `configure` and tried to run it.

If you downloaded a release tarball it should have had a properly generated `configure` in it, but if you cloned the git repo, or downloaded a tarball generated by github, it would be lacking the `configure` script, and you would have to run `./autogen.sh` to generate it, and you would need new-enough versions of autoconf and automake.

**Comment by hawicz** [comment]
I think it's more complicated than just renaming the configure.ac script, look at the line number of the error.  You'd get the error that itssivashankar sees if the autoconf-archive/m4 directory is missing, or if the AC_CONFIG_MACRO_DIRS isn't working properly.  That macro wasn't available with too early of a version of automake, and he still hasn't told us what version of **that** he is using, so my guess is that it's too old to work.

**Comment by ploxiln** [comment]
yeah that makes more sense

**Comment by sperumalcse** [comment]
Hi Ploxiln, 

This post saved my day! I was banging my head why 'configure' file is available in release tar ball not in git clone.

Thank you very much!!

**Comment by hawicz** [comment]
There doesn't seem to be anything that needs to be fixed in json-c here, closing.
