### ISSUE TITLE
Add missing "make check" target to cmake config

### ISSUE THREAD

**Issue by hawicz** [json-c/json-c#445]
Commit f2e991a (issue #334) added "real cmake support", but it missed the tests.  These need to be added.

**Comment by dota17** [comment]
"Make test" has been added in cmake build. This issue and # 334 could been closed @hawicz 
（‐＾▽＾‐）

**Comment by hawicz** [comment]
I'll close this one, but #334 isn't quite done yet.  There's still at least some clean up to do to remove the old autoconf machinery, and it probably is missing something useful that the old build approach has (e.g. distcheck, etc...)
