### ISSUE TITLE
Need of json_type_int64 returned by json_object_get_type()

### ISSUE THREAD

**Issue by puran157** [json-c/json-c#449]
Hi everyone,

I see we have APIs for int and int64 but json_object_get_type() returns just json_type_int for both cases.

I have a test code where the value was added as json_object_new_int64() to root json. While parsing, I am using json_object_get_int() when json_object_get_type() retuns json_type_int.

Should we have json_type_int64 also returned as part of json_object_get_type() or is there a way already which can be used to differentiate object type for int and int64.

If not, please let me know and I will be happy to work on this.

**Comment by hawicz** [comment]
Whether you created the object using new_int64 or new_int, it's stored as an int64_t internally, so there is no actual difference in the types.  You should just always use json_object_get_int64()

**Comment by hawicz** [comment]
See https://github.com/json-c/json-c/blob/master/json_object_private.h#L37

**Comment by puran157** [comment]
Cool, thanks @hawicz.
