### ISSUE TITLE
Add option to disable HAVE___THREAD

### ISSUE THREAD

**Issue by drizt** [json-c/json-c#451]
`HAVE___THREAD` produces libgcc_s_sjlj-1.dll extra dependencies with MinGW. It's not good. Please add a way to disable it.

**Comment by besser82** [comment]
You may want to test the mentioned [pull-request as a whole](https://github.com/json-c/json-c/pull/617.patch), since there is another commit included, that fixes the failing `test_double_serializer`, when building without thread-local storage.
