### ISSUE TITLE
configure:3610: error: C compiler cannot create executables

### ISSUE THREAD

**Issue by gramels** [json-c/json-c#466]
Hi,

I tried to complie on raspbian and get the error

`configure:3610: error: C compiler cannot create executables`

build tools are installed, but maybe I miss some

[config.log](https://github.com/json-c/json-c/files/2687017/config.log)

**Comment by hawicz** [comment]
That's not a json-c problem, you likely have the wrong version of gcc installed.  See the "internal compiler error: Illegal instruction" error in config.log, and a few examples of people having similar problems:

- https://www.raspberrypi.org/forums/viewtopic.php?t=58666
- https://stackoverflow.com/questions/16526493/what-is-this-gcc-error-on-linux-and-how-do-i-solve-it-gcc-internal-compiler-e
- https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build/issues/7
