### ISSUE TITLE
json_object_get_string_len returns 0 when value is number

### ISSUE THREAD

**Issue by DusteDdk** [json-c/json-c#478]
I was surprised that I can call json_object_get_string on a key containing a number, and it returns the string representation of the number. That's very useful! However, the json_object_get_string_len method will return 0, which strictly speaking makes sense, but makes it slightly less convenient.
I suggest either disallowing returning the string representation from json_object_get_string or
making json_object_get_string_len return the length of the string representation.

**Comment by hawicz** [comment]
While the inconsistency is rather unfortunate, changing the behavior now is likely to cause issues for apps that have come to depend on it.  If we were to do this, I'd say the thing to do would be to drop the implicit call to json_object_to_json_string for other types, but that'd need to be done as part of a major revision bump.  This won't be done right now, so I'm just closing this issue, but I created a page to list things that might get into a future major version release: https://github.com/json-c/json-c/wiki/Proposed-changes-for-new-v1.0-version
