### ISSUE TITLE
 error while loading shared libraries: libjson-c.so.4

### ISSUE THREAD

**Issue by FerenczD** [json-c/json-c#481]
I followed the building instructions of the library and I'm getting the following error when I try to run my JSON application.
`     error while loading shared libraries: libjson-c.so.4: cannot open shared object file: No such file or directory`

This is my make file 
```
CC=gcc

CFLAGS += $(shell pkg-config --cflags json-c)
LDFLAGS += $(shell pkg-config --libs json-c)

OBJ=jsonTest.o

all:  jsonTest

jsonTest: $(OBJ)
	$(CC) $^ -o $@ $(LDFLAGS) $(CFLAGS) 
```

I checked the path /usr/local/lib and indeed the libjson.so.4 is there.

How can I solve this?

EDIT: I'm running Ubuntu 14.04, and made sure all dependencies were over the version requirements.

**Comment by hawicz** [comment]
1 - Check that the library names actually match.  Do you have a libjson.so.4 or libjson-c.so.4?
2 - Try adding -Wl,-R/usr/local/lib to your LDFLAGS

**Comment by FerenczD** [comment]
I re installed the program after rebooting the OS and it magically worked. Thanks for the reply tho.
