### ISSUE TITLE
Error "double free or corruption" after free()

### ISSUE THREAD

**Issue by FerenczD** [json-c/json-c#482]
The idea of my code is that I'm trying to save the result of `json_object_to_json_string()` on a dynamic allocated char* buffer.

This is my code:
```
  char* tmp;
  struct json_object *root = NULL;

  root = json_object_new_object();
  json_object_object_add(root, "user_id", json_object_new_string(user_id));
  json_object_object_add(root, "user_name", json_object_new_string(user_name));
  json_object_object_add(root, "estimated_runtime", json_object_new_int(estimated_runtime));
  json_object_object_add(root, "instrument_UDI", json_object_new_string(instrument_UDI));

  tmp = (char *)malloc(1024); /* Does not matter size */
  tmp = json_object_to_json_string(root);


  printf("New string = %s\n", tmp);
  free(tmp);
  json_object_put(root);  /* Free json obj */
```

If I use `free(tmp)` I get the error from the title. If I don't `free(tmp)` I get memory leak. Is it a library issue?

I tried also not using `json_object_to_json_string()` and instead just set tmp as a string so there is no relation between the `json object *` and the string... however, the problem persists.

Any thoughts?

This is the whole error I get 
```
*** Error in `./jsonTest': double free or corruption (top): 0x0000000001d9d970 ***
Aborted (core dumped)
```

**Comment by ploxiln** [comment]
```c
  tmp = (char *)malloc(1024); /* Does not matter size */
  tmp = json_object_to_json_string(root);
```

That does not copy into the buffer that `tmp` points to, it just over-writes the `tmp` pointer and leaks what `malloc()` returned immediately.

What you want is:

```c
tmp = strdup(json_object_to_json_string(root))
```

**Comment by FerenczD** [comment]
Ohh I see. It makes sense. Thanks for the help.
