### ISSUE TITLE
Any plans to make new release? (0.14)

### ISSUE THREAD

**Issue by kloczek** [json-c/json-c#487]
I think that it wood be good make new release with current code base :)

**Comment by hawicz** [comment]
I haven't even looked to see what might be included.  Are there enough changes to make a release worthwhile?  Is there any particular change that you're looking to see in the next release?

**Comment by kloczek** [comment]
Since last release have been committed few changes. I think that it would be good to flush all those changes and make new release with updated code base :)

**Comment by rossburton** [comment]
Considering the last release was over a year ago, a new one would be nice.

**Comment by kloczek** [comment]
It would be as well this time change tagging patter by use in new version tag just version without date and project name to make easier to use autogenerated by github tart ball on packaging.
Please .. :)

**Comment by Croydon** [comment]
It seems like XCode 10 isn't supported by the last release, but it seems to be supported by master.

Please make a new release
and as @kloczek said please don't add the release data to the git tag, this would make packaging json-c easier

**Comment by harkue** [comment]
A new release will be very welcome~

**Comment by dota17** [comment]
hi, @hawicz , maybe, it's time to prepare to release a new version. The two-year interval is a bit long. Many users expect one new version.

**Comment by hawicz** [comment]
I'd like to complete the switch over to cmake (#334) first, including eliminating all the autoconf machinery, but yes, it's well past time for a new version.
I created https://github.com/json-c/json-c/wiki/Notes-for-v0.14-release as a place to work on the release.

**Comment by kloczek** [comment]
So what is wrong with current automake/autoconf? (IMO ItWorks(tm) and nothing here needs to be changed)

**Comment by hawicz** [comment]
We've decided to switch to cmake for easier support across different environment, and we don't intend to support more than one build method.

**Comment by rossburton** [comment]
I presume it's too late to suggest Meson over CMake?

**Comment by hawicz** [comment]
yes, it's too late

**Comment by besser82** [comment]
@hawicz Is there a list of items, that are currently blocking a new release?  Maybe I can fix some of them…

**Comment by kloczek** [comment]
@besser82 I'm not the json-c maintainer :)

**Comment by dota17** [comment]
@besser82 you can see the [Notes-for-v0.14-release](https://github.com/json-c/json-c/wiki/Notes-for-v0.14-release).

**Comment by hawicz** [comment]
The two tasks that could use someone to take a look are:
* Analyze APIs to produce list of changes  (how?  eyeballs?)
* Assemble a list of issues & PRs closed (i.e. follow the steps in issues_closed_for_0.13.md that I did last time, though I just realized that _that_ file displays terribly when actually rendered as markdown)

**Comment by besser82** [comment]
> * Analyze APIs to produce list of changes  (how?  eyeballs?)

I've created an [ABI and API diff report](https://besser82.fedorapeople.org/json-c-api/) with the [abi-compliance-checker](https://lvc.github.io/abi-compliance-checker/).

@hawicz You may need your eyeballs for reading its html output. :P

**Comment by besser82** [comment]
> > * Analyze APIs to produce list of changes  (how?  eyeballs?)
> 
> I've created an [ABI and API diff report](https://besser82.fedorapeople.org/json-c-api/) with the [abi-compliance-checker](https://lvc.github.io/abi-compliance-checker/).
> 
> @hawicz You may need your eyeballs for reading its html output. :P

I forgot to mention that the defines for `TRUE` and `FALSE` also have been removed.  That is another API break compared to earlier versions.

**Comment by hawicz** [comment]
I think I've got the tentative release notes in a pretty good shape over on the wiki page.
I'm going to give it one more read-through when I'm a bit more rested, and aim to create the json-c-0.14 branch in the next few days.

**Comment by hawicz** [comment]
json-c 0.14 has been released.  See the announcement at https://groups.google.com/forum/#!topic/json-c/yLwwAqiRf-4

**Comment by kloczek** [comment]
After year IMO it would be nice to make new release again :)

Is it possible to change this time tagging patter from `json-c-<version>-<date>` to just `<version>`?
Release date is in git tag date so it is a bit redundant .. :P
