### ISSUE TITLE
Some APIs are not exported when built as shared lib on Win32

### ISSUE THREAD

**Issue by myd7349** [json-c/json-c#488]
Hi! I am trying to add `json-c` to `vcpkg` these days: https://github.com/json-c/json-c/pull/485 . And I encountered several link errors when I tried to link with a shared build of `json-c`:
>json_c_test.obj : error LNK2019: unresolved external symbol _json_c_version referenced in function _main [E:\json_c_tes
t\build-x86-windows\json_c_test.vcxproj]
json_c_test.obj : error LNK2019: unresolved external symbol _json_pointer_get referenced in function _main [E:\json_c_t
est\build-x86-windows\json_c_test.vcxproj]
json_c_test.obj : error LNK2019: unresolved external symbol _json_object_from_file referenced in function _main [E:\jso
n_c_test\build-x86-windows\json_c_test.vcxproj]
E:\json_c_test\build-x86-windows\Release\json_c_test.exe : fatal error LNK1120: 3 unresolved externals [E:\json_c_test\
build-x86-windows\json_c_test.vcxproj]

Test project: https://github.com/myd7349/Ongoing-Study/tree/master/cpp/CMake/vcpkg/json_c_test

It seems caused by the lack of `JSON_EXPORT` in the declarations of these APIs:
https://github.com/json-c/json-c/blob/485f2a02c79da8a7b31e972f0c652f06094bcfb9/json_c_version.h#L27
https://github.com/json-c/json-c/blob/485f2a02c79da8a7b31e972f0c652f06094bcfb9/json_util.h#L43

The correct way:
https://github.com/json-c/json-c/blob/485f2a02c79da8a7b31e972f0c652f06094bcfb9/json_object.h#L190

**Comment by hawicz** [comment]
s/b fixed in commit eae040a.
