### ISSUE TITLE
Don't use -Werror by default

### ISSUE THREAD

**Issue by rossburton** [json-c/json-c#489]
Whilst I have no problem with the developer using `-Werror` to ensure that all compiler warnings are solved, please don't force this on everyone who wants to build json-c.

All it takes is one slightly changed dependency, or a newer compiler, or a different architecture, for there to be new warnings.  Latest example: json-c doesn't build in icecc because icecc strips out comments, so the switch fallthrough warnings are emitted, which are fatal because of `-Werror`.

**Comment by hawicz** [comment]
json-c will continue to build with -Werror by default, but if you want to add a configure option (e.g. --allow-compiler-warnings, or similar) to override that, that'd be fine.
