### ISSUE TITLE
Code generator?

### ISSUE THREAD

**Issue by fusionJose** [json-c/json-c#494]
Is there any tool which can generate the c code, from a JSON schema or file?. I mean something which writes all the json_objects and all of the types to serialize from a shema or a json file, and is prepared to work with this library. Thanks

**Comment by hawicz** [comment]
From a schema?  Not that I know of, however if you have a json file you can parse it with the [json_tokener_parse_ex() function](http://json-c.github.io/json-c/json-c-0.13/doc/html/json__tokener_8h.html#a61679f178111963a9ffa3c8179553f7a) or [json_object_from_file](http://json-c.github.io/json-c/json-c-0.13/doc/html/json__util_8h.html#a8fa0bba6b7ddb149a2159d99bae709ce)

Of course, it's up to you to write the code to do something with the parsed objects.
