### ISSUE TITLE
configure error

### ISSUE THREAD

**Issue by haozhuo1987** [json-c/json-c#502]
hi 
    i want to build json use on arm chip，but when i use configure to build，it wrong，it said the gcc complier can not create executables file，just like this picture，i don't know why，could you tell me how to build it？
![image](https://user-images.githubusercontent.com/39908996/63336426-b8c2b680-c371-11e9-8f88-6d8d0f4ef44a.png)

**Comment by HelderMagalhaes** [comment]
How to prepare a proper build environment is, AFAIK, out of the scope of this project.
Said that, configure is telling you "black-on-white" (in this case white-on-black) that

**Comment by hawicz** [comment]
Closing, not enough information to help here.
