### ISSUE TITLE
json_object_put coredump

### ISSUE THREAD

**Issue by cnggu2018** [json-c/json-c#504]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Core was generated by `/sbin/lldp.elf'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5ff1b5e82f in je_bitmap_get (binfo=<optimized out>, bit=0,
    bitmap=0x7f606600a58d) at include/jemalloc/internal/bitmap.h:84
84      include/jemalloc/internal/bitmap.h: No such file or directory.
[Current thread is 1 (Thread 0x7f5fe9baa700 (LWP 10998))]
(gdb) bt full
#0  0x00007f5ff1b5e82f in je_bitmap_get (binfo=<optimized out>, bit=0,
    bitmap=0x7f606600a58d) at include/jemalloc/internal/bitmap.h:84
        goff = 0
#1  arena_run_reg_dalloc (ptr=0x7f5fe8c88100, run=0x7f5fe8c87000)
    at src/arena.c:323
        chunk = <optimized out>
        bin_info = <optimized out>
        pageind = <optimized out>
        bitmap = 0x7f606600a58d
#2  je_arena_dalloc_bin_locked (arena=arena@entry=0x7f5feb409140,
    chunk=chunk@entry=0x7f5fe8c00000, ptr=ptr@entry=0x7f5fe8c88100,
    mapelm=mapelm@entry=0x7f5fe8c00c60) at src/arena.c:1905
        pageind = 136
        run = 0x7f5fe8c87000
        bin = 0x7f5feb4092f8
        bin_info = 0x7f5ff1d86fb8 <_dl_start+1416>
        size = 7797293670239152772
#3  0x00007f5ff1b5ec57 in je_arena_dalloc_bin (mapelm=<optimized out>,
    pageind=<optimized out>, ptr=0x7f5fe8c88100, chunk=0x7f5fe8c00000,
    arena=0x7f5feb409140) at src/arena.c:1947
        run = <optimized out>
        bin = <optimized out>
#4  je_arena_dalloc_small (arena=0x7f5feb409140, chunk=0x7f5fe8c00000,
---Type <return> to continue, or q <return> to quit---
    ptr=0x7f5fe8c88100, pageind=<optimized out>) at src/arena.c:1963
No locals.
#5  0x00007f5fef462bc4 in lh_table_free (t=0x7f5fe8c700c0) at linkhash.c:570
        c = 0x0
#6  0x00007f5fef459de2 in json_object_object_delete (jso=0x7f5fe8c79140)
    at json_object.c:426
No locals.
#7  0x00007f5fef459730 in json_object_put (jso=0x7f5fe8c79140)
    at json_object.c:199
No locals.
#8  0x00007f5fef45b41b in json_object_array_entry_free (data=0x7f5fe8c79140)
    at json_object.c:1125

hello everyone. What's the reason for this coredump?

**Comment by hawicz** [comment]
You haven't provided enough information to know what the problem might be.  Perhaps you freed an array entry twice?  Perhaps some other part of your program stomped on memory?
If you think there's a problem with json-c, please provide some example code that demonstrates the crash.
