### ISSUE TITLE
Cannot parse more than one object

### ISSUE THREAD

**Issue by Haseeb30000** [json-c/json-c#506]
I have tried everything to split json objects so that json_tokener_parse() could parse it.

My Code: json_tokener_parse() doesn't work if there are more than 1 object in the json file but works good when it have one object. I have read all the documentation but couldn't find a way to divid string objects and parse each object at a time.
```
[{
    "hash":"121234365869689789789fghgh",
    "time":"1999999",
    "TxIn":["121312313","21312312","23123123"]
},
{
    "hash":"221234365869689789789fghgh",
    "time":"2999999",
    "TxIn":["2121312313","21312312","23123123"]
},
{
    "hash":"321234365869689789789fghgh",
    "time":"3999999",
    "TxIn":["3121312313","21312312","23123123"]
}]
```

**Comment by hawicz** [comment]
Your example here has a single object.  If that's actually what your input looks like, then it is correct that you only get a single object back.
On the other hand, if you have another object (_immediately_) after that one, simply grab the char_offset of where the previous call to json_tokener_parse_ex left off, and call it again starting from that point in your buffer.  
e.g. starting from the example in the docs at http://json-c.github.io/json-c/json-c-0.13/doc/html/json__tokener_8h.html#a61679f178111963a9ffa3c8179553f7a, you might do something like:
```
mystring += tok->char_offset;
jobj = json_tokener_parse_ex(tok, mystring, strlen(mystring));
```
assuming you have all your bytes already available in memory.

**Comment by hawicz** [comment]
Closing, since no additional detail was provided.
