### ISSUE TITLE
Double value -1.0 converts to integer in json_object_to_json_string()

### ISSUE THREAD

**Issue by endian02** [json-c/json-c#507]
Hi,

I have a calibration module that are supposed to store a couple of values as doubles in a json file. They currently only take the values 1.0 and -1.0. When saving the value 1.0 everything works ok, but when trying to store the value -1.0 it stores it as an int i.e. I get the string "-1" instead of the value "-1.0" in the resulting string.

I am using json-c version 0.13.1

**Comment by hawicz** [comment]
Fixed in commit 485f2a02, but not in any release yet.

**Comment by endian02** [comment]
Good, thanks.

When will the next release be frozen?

Den ons 30 okt. 2019 kl 01:24 skrev Eric Haszlakiewicz <
notifications@github.com>:

**Comment by hawicz** [comment]
Closing this since the upcoming 0.14 release will include the fix.  I expect to be branching in the next day or so.
