### ISSUE TITLE
Sometimes a double value is not serialized 

### ISSUE THREAD

**Issue by endian02** [json-c/json-c#509]
We have seen twice now error messages where json-c has failed parsing a json file written by the same app (and thus json-c). In both cases the files got invalid syntax, as one double value had not been serialized, like the missing width value in the example below.

.... “size”: { “width”: , “height”: 0.5 }, ....

It happens very seldom, and was detected by automated testing in both cases.

**Comment by hawicz** [comment]
Can you provide any other details?  It's going to be pretty hard to do anything with this bug report without a reproducible test case, or at least some kind of description of what might be unique in the situation where you've noticed a problem.

**Comment by endian02** [comment]
Yes I know. There is nothing special. The value is supposed to have been
0.5 likely. It is not supposed to be nan. We might do some more attempts to
reproduce it. If so I will update with results.

/ Kenneth

Den tors 21 nov. 2019 03:37Eric Haszlakiewicz <notifications@github.com>
skrev:

**Comment by hawicz** [comment]
Note that if it was really a NaN value (e.g. 0.0/0.0), you'd see ```"width": NaN```

**Comment by endian02** [comment]
Ahh ok Good to know.

/ Kenneth

Den fre 22 nov. 2019 06:24Eric Haszlakiewicz <notifications@github.com>
skrev:

**Comment by endian02** [comment]
We just got another ticket on this problem today. 

This time it seems like the floating point value is serialized as the character Y, which causes the parser to complain.

 ... "Pid": { "kp": Y, "ki": 3.0, "kd": 18.0 } ...

**Comment by endian02** [comment]
We are using this function multiple times in our app (possibly in different threads)

json_c_set_serialization_double_format("%.3g", JSON_C_OPTION_GLOBAL);

with parameter "%.3g", "%.6g" and "%.4g"

**Comment by hawicz** [comment]
Careful with threading, you shouldn't expect that using the same (portions of the) object tree across different threads is completely safe, especially if more than one thread is serializing at the same time.
If you're running threaded, I would recommend against setting the global format, and instead see if you can use JSON_C_OPTION_THREAD instead: we don't have any memory barriers in place so I suspect explicitly using thread-local storage would be a bit more reliable.

**Comment by endian02** [comment]
Ok, thanks. We will try using the thread setting. Should work fine for us since we are not sharing json-objects between threads.

**Comment by hawicz** [comment]
I'm assuming more careful threaded handling has solved your problem.  If you still see an issue, and can provide an example, please reopen.

**Comment by endian02** [comment]
We made the change last week. Still waiting for final result, but no
problems seen yet afaik.

Den ons 11 dec. 2019 kl 04:59 skrev Eric Haszlakiewicz <
notifications@github.com>:

**Comment by endian02** [comment]
It has worked quite well since we made the thread change above, but today I received a report that one double value <51.0> had been encoded as just "51" in the string. Could this happen?

**Comment by hawicz** [comment]
If you're using a very old version of json-c, yes, but the most recent release (0.15) always adds a ".0", and I think anything starting from 0.13 should be fine.  If you have a reproducible test case, please open a new bug and provide it.

**Comment by endian02** [comment]
We're using 0.13.1

Den fre 7 aug. 2020 kl 16:31 skrev Eric Hawicz <notifications@github.com>:

**Comment by dota17** [comment]
I parsed the "[50.0, 1.00, 63.1, 0.0]" and get the same array in master branch and 0.13.1. How about providing a test case?
