### ISSUE TITLE
Adding type uint64

### ISSUE THREAD

**Issue by JayyCee** [json-c/json-c#520]
I've enhanced the code with adding _uint64_ functions in my local branch.  This _uint64_ type is needed for my project that needs to handling a full data value of a 64-bit register from a hardware module.

I would like to share my enhancements.  What are the steps for me to do to make a pull-request?

--JC

**Comment by hawicz** [comment]
This was asked before by @topilski , see https://github.com/json-c/json-c/issues/326
However, the implementation leaves a lot to be desired.  In particular, what he suggested adds a whole new "uint" type, but doesn't appear to do anything to deal with overflow of the internal signed storage field, and particular poor behavior when trying to retrieve negative values (i.e. just returns 0).

Also, any attempt to add additional bits is going to increase overhead and have various tradeoffs, and I'm skeptical that it's worth doing that for just a single bit.  On the other hand, if you want to bump things up to 128 bits, then things get more interesting.  Either way, I'd expect a characterization from you as to what you believe the benefits and drawbacks are/will be, and why it's justified to include the changes you want.

**Comment by JayyCee** [comment]
I see where you come from regarding adding 64-bit thing.  

The single benefit:
Using current master's uint/int type, it gets a wrong value of -1 or the like,  when processing an unsigned integer value of 0xFFFFFFFFFFFFFFFF from an hardware register.

After adding  uint64_t capable of functions,  there is a working function of "json_object_new_uint64(0xFFFFFFFFFFFFFFFF), and then json_obj.to_string() function correctly produces a right number for it.
 
Trying the 128-bit thing is a very interesting challenge and it is beyond of my capability.  Hope you understand.

**Comment by dota17** [comment]
Adding uint64 data type is complicated but not difficult. I have made it in #542 . UINT64 is useful and many json libraries have this feature. I am willing to promote the solution of this issue. 
@hawicz @JayyCee How do you think of #542? Need your suggestions.  0.0

**Comment by hawicz** [comment]
Closing this, since #542 has been merged.  It adds support for uint64_t w/o adding a new json_type.  Overflow should be handled reasonably, by capping at UINT64_MAX, while negative values still end up being returned as 0.
