### ISSUE TITLE
build cmake windows 10

### ISSUE THREAD

**Issue by holzpfanne** [json-c/json-c#521]
I am trying to build json-c on windows 10 with cmake
after I execute `cmake ../` at the end I get:
```-- Performing Test HAS_GNU_WARNING_LONG
-- Performing Test HAS_GNU_WARNING_LONG - Failed
-- Performing Test HAVE_ATOMIC_BUILTINS
-- Performing Test HAVE_ATOMIC_BUILTINS - Failed
-- Performing Test HAVE___THREAD
-- Performing Test HAVE___THREAD - Failed
-- Written C:/Users/****/source/repos/json-c/build/config.h
-- Written C:/Users/****/source/repos/json-c/build/json_config.h
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/****/source/repos/json-c/build
```
And no `makefile` is then created
I am following [those](https://github.com/json-c/json-c#building-with-cmake-) instructions
Am I doing something wrong?
Any help is appreciated
thanks in advance

**Comment by hawicz** [comment]
The cmake build on windows doesn't create makefiles, it creates Visual Studio project files instead.  You can build from the command line using something similar to what https://github.com/json-c/json-c/blob/master/appveyor.yml does (i.e. `cmake --build . --target install`), but you'll need to do that from a command prompt that is set up to run the VS tools (e.g. cl.exe) properly (e.g. "VS2015 x86 Native Tools Command Prompt").  Or, you can open the project files using the VS gui.
