### ISSUE TITLE
short string optimization: excessive array length

### ISSUE THREAD

**Issue by dota17** [json-c/json-c#535]
I found one question about the LEN_DIRECT_STRING_DATA.@rgerhards @hawicz 
https://github.com/json-c/json-c/blob/360d28b9611a4ee9f4312e1e76e0b5c8d674ec14/json_object_private.h#L23
32 may be a little large and it results in that one json_object struct takes up more memory. for example, value (int) 100 will cost 24 (32-8,8 is pointer length) bytes memory additionally, compared with no short string optimazation. That violates the original intention for saving memory and increasing operating efficiency. 
For verifing this idea, I test the different LEN_DIRECT_STRING_DATA(4,8,16,32) with [nativejson-benchmark](https://github.com/miloyip/nativejson-benchmark). The results confirmed this idea. The parse memory(byte) with setting len as 4, 8, 16, 32 is 49802936, 49775744, 49754384, 53172472 respectively. The parse scenario is relatively fixed but does not affect the conclusion greatly. The other properties have little changes. 
32 bytes:
![32](https://user-images.githubusercontent.com/50514813/72677980-c5903580-3adc-11ea-9da4-e52d25b32a94.png)
16 bytes:
![16](https://user-images.githubusercontent.com/50514813/72677982-caed8000-3adc-11ea-8190-7d63fe641d0e.png)
8 bytes:
![8](https://user-images.githubusercontent.com/50514813/72677986-cfb23400-3adc-11ea-9a8e-de6b314d0955.png)
4 bytes:
![4](https://user-images.githubusercontent.com/50514813/72677990-d2ad2480-3adc-11ea-9106-6a247fb1d38b.png)

in cmmmit log [c4f8c](https://github.com/json-c/json-c/commit/c4f8cc34df91715d008166e4748c5f32ee894698), @rgerhards marked that "This brings a 24-bytes memory overhead, but I consider that still useful because the memory allocator usually also has quite some overhead (16 bytes) for dyn alloced memory blocks. In any case, the max buffer size can be tweaked via #define." I don't understand the memory allocator well.  Should we consider this in short string optimization?

In my opinion, the LEN_DIRECT_STRING_DATA should be set according to the data structure and using scenes. For example,  the data structure decide that the length should be set as 11/15 (32/64 bytes) in [rapidjson](https://github.com/Tencent/rapidjson). However, in json-c, I think the length could be set as 16.  The length's pros and cons depend on the using scenes. If json data have many number or short string(1-8 bytes, like name, occupation), it will waste many mamory. if the json data have longer string(20-30 bytes), the length should be larger. We should have a choice between 8-32. 32 may be not a suitable length.

In addition，I find another Interesting parameter (ARRAY_LIST_DEFAULT_SIZE) accidentally. Same principle as above. The value of default array size also depends on the using scenes. Usually the array size is not large.  
https://github.com/dota17/json-c/blob/360d28b9611a4ee9f4312e1e76e0b5c8d674ec14/arraylist.h#L25
32:
![json-c-32](https://user-images.githubusercontent.com/50514813/72675965-d0d86680-3ac6-11ea-82fb-216e6adb7b1c.png)
16:
![json-c-16](https://user-images.githubusercontent.com/50514813/72675983-fa918d80-3ac6-11ea-98a4-371d994a90f4.png)
8:
![json-c-8](https://user-images.githubusercontent.com/50514813/72675985-fe251480-3ac6-11ea-9bc1-c0783539d5f0.png)
4:
![json-c-4](https://user-images.githubusercontent.com/50514813/72675987-01200500-3ac7-11ea-8cde-7674a5490b7a.png)

Maybe the LEN_DIRECT_STRING_DATA/ARRAY_LIST_DEFAULT_SIZE set as 16/16 will get a good memory performance.
![1616](https://user-images.githubusercontent.com/50514813/72678296-7b5c8380-3adf-11ea-8c79-b2a31ba2fa45.png)

**Comment by hawicz** [comment]
Please let's keep ARRAY_LIST_DEFAULT_SIZE discussion separate.  It is very different from LEN_DIRECT_STRING_DATA in that we could easily allow that to be run-time configurable, and the considerations for what length to make arrays by default are very different than what we might do for strings.

On to the string handling:
53172472 - 49754384 / (32-16) == 213630.5
49754384 - 49775744 / ( 16 - 8) == 2670
49775744 - 49802936 /  (8 - 4) == 6798
Something seems quite off here, especially with the variation from 32-byte to 16-byte.  Were we to use the results of this benchmark to make a decision, an anlysis of exactly why the variation isn't consistent would be needed.  However, I would say not to bother with that, see below for why.

Keep in mind that LEN_DIRECT_STRING_DATA only affects string values, not keys.  Glancing at the data in nativejson-benchmark, it appears that the vast majority of values are not strings at all.
Even in the twitter.json data file, I estimate that more than half of the values are integers or booleans.
If you use just these it's pretty clear that you'll come to the conclusion that the direct string data should be shrunk, but I'm don't know that this is actually a representative sample of JSON documents in general.
Without a lot more research, I'm not convinced that we should override @rgerhards's judgement on this matter.
I don't think it's worth changing things here, at least not in this incremental way that is likely to improve only some workloads while making others worse.  Instead, if you really want to improve the overall memory usage, we should take advantage of the fact that json_object is a private, library-internal data structure, and _split it_ into different structures for the different json types, and change the code to implement a polymorphic cast & dispatch approach based on that.
i.e. any place we have things like "jso->p.c_string", etc... we instead do:
```
if (jso->o_type == json_type_string) {
    jso_str = (struct json_object_string *)jso;
   ...do stuff w/ jso_str...
}
etc...
```
Plus, define struct json_object_string to have "char data[1]" at the end, and have string data *always* be direct by allocating (sizeof(struct json_object_string) + strlen(s)).

```
struct json_object_base
{
  enum json_type o_type;
  uint32_t _ref_count;
  json_object_private_delete_fn *_delete;
  json_object_to_json_string_fn *_to_json_string;
  //struct printbuf *_pb;  (can probably be omitted from here)
  json_object_delete_fn *_user_delete;
  void *_userdata;
};

struct json_object_string
{
	struct json_object_base base;
	size_t len;
	// ... maybe add padding for alignment...
	char data[1];  // actually longer, at least len+1 bytes.
};
struct json_object_object
{
	struct json_object_base base;
	struct lh_table c_object; // note: not a pointer!
}
struct json_object_double
{
	struct json_object_base base;
	double c_double;
};
etc...
```

**Comment by dota17** [comment]
hi, hawicz 
I agree with your opinion. We couldn't have a direct conclusion on LEN_DIRECT_STRING_DATA due to different using scenarios. Especially the benchmark has Less string scene. Modifying this parameter directly is not a good solution.
As for ARRAY_LIST_DEFAULT_SIZE, I get your meaning and it's my fault. 
In addition, you suggest to split the json_value into different structures for the different json types. It is a good solution for improving the overall memory usage indeed. But it is  contrary to the slab allocator. I will learn more on memory usage.

**Comment by hawicz** [comment]
Fyi, I copied the notes about the struct json_object split over to https://github.com/json-c/json-c/wiki/Proposal:-struct-json_object-split, so if any of us wants to explore that idea more we have a convenient place to do so.
