### ISSUE TITLE
double serializes to the old value after set_double

### ISSUE THREAD

**Issue by dorssel** [json-c/json-c#539]
with version 0.13.1:

```
#include <json-c/json.h>
#include <stdio.h>

int main()
{
    json_object *obj = json_tokener_parse("{\"x\":1.1}");
    json_object *x;
    json_object_object_get_ex(obj, "x", &x);
    json_object_set_double(x, 2.2);
    puts(json_object_to_json_string(obj));
    json_object_put(obj);
    return 0;
}
```

The actual value is changed, but it still serializes as 1.1. The parser uses `json_object_new_double_s` and caches the original serialization by storing it in the userdata as "format string". However, it isn't actually a format string, but the original string representation. `json_object_set_double` sets the value, but leaves the formatter in tact. Upon serialization the original cached value (now obsolete) is output.

Suggested solution: the tokenizer should set the formatter to a new function `json_object_double_to_json_string_cached`. And `json_object_set_double` should reset the formatter to `json_object_double_to_json_string_default` if the current formatter is `json_object_double_to_json_string_cached`.

**Comment by hawicz** [comment]
Yep, that's a bug.  json_object_set_double() should do:

    if (jso->_to_json_string == &json_object_double_to_json_string_default)
        json_object_set_serializer(jso, NULL, NULL, NULL); 

Which will handle all necessary cleanup and set an appropriate default serializer.

**Comment by dorssel** [comment]
With this solution I suggest to update the `json_object_set_double` documentation so that it is clear that it has the side effect of resetting any user specific formatter (breaking change from current behavior). Because the sequence in user code:
```
json_object_new_double_s
json_object_set_double
```
or
```
json_object_set_serializer
json_object_set_double
```
will now use the default serializer instead of the one the user specified. My original suggestion allows `json_object_set_double` to unambiguously detect the cached value from the tokenizer.

**Comment by dota17** [comment]
yes, as @dorssel  said, we should update the ```json_object_set_double``` documentation.  The new ```json_object_set_double``` have reset the userdata and clean up the buffer data

otherwise, in commit [ae13ca524a0e](https://github.com/json-c/json-c/commit/ae13ca524a0e4567489c1e5138deedd568c161b6) , you forget to free the object. It causes the failure of travis-ci @hawicz. （‐＾▽＾‐）
https://github.com/json-c/json-c/blob/ae13ca524a0e4567489c1e5138deedd568c161b6/tests/test_set_value.c#L53

**Comment by hawicz** [comment]
There is no cached value just from the tokener that is different from json_object_new_double_s, that's exactly what it uses.  That said, I can see the value of having json_object_new_double_s use a serializer that is guaranteed not to be available to code outside of the library, and having json_object_set_double() check for _that_.
