### ISSUE TITLE
lib installation issues

### ISSUE THREAD

**Issue by tuanla1710** [json-c/json-c#549]
Dear authors, 
Many thanks for you contribution for the json-c. It is very useful with me. In current time, I have one issues to install this lib in my system.  
[json-c-master]$ ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal -I autoconf-archive/m4
configure.ac:171: error: Autoconf version 2.64 or higher is required
autoconf-archive/m4/ax_check_compile_flag.m4:60: AX_CHECK_COMPILE_FLAG is expanded from...
autoconf-archive/m4/ax_append_compile_flags.m4:59: AX_APPEND_COMPILE_FLAGS is expanded from...
../../lib/m4sugar/m4sh.m4:505: AS_IF is expanded from...
configure.ac:171: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
[json-c-master]$
 
Actually, it is hard to upgrade my Linux environment ,  have any one know how to install this library in manual?

**Comment by dota17** [comment]
@tuanla1710 ，Do you have the conditions to compile and build json-c with cmake?  json-c supports cmake above 2.8.

**Comment by hawicz** [comment]
Please see the README.md file, https://github.com/json-c/json-c/blob/master/README.md#manually-install-and-build-autoconf-automake-and-libtool will have the steps you need.
