### ISSUE TITLE
Figure out what needs to be done with Android.configure.mk

### ISSUE THREAD

**Issue by hawicz** [json-c/json-c#570]
The Android.configure.mk file is a wrapper around the rest of the autoconf, configure and build process to be able to build on Android, but now with the autoconf machinery removed it won't work.

@ford-prefect, I know it's been quite some time since you added this, but are you still using json-c on Android?  Would you be able to take a look at what it'd take to get it to build using cmake?

**Comment by hawicz** [comment]
See also issue #26.

**Comment by ford-prefect** [comment]
Hey Eric, unfortunately, I'm not really using json-c or this Android build infrastructure any more. I imagine it shouldn't be prohibitively hard to write a cmake script, though I don't think I can spare any time for this right now.

**Comment by hawicz** [comment]
Oh well, we'll just leave it as-is for now.  Hopefully someone else will step up and suggest a PR to fix it.

**Comment by wjorda** [comment]
I was able to get JSON-C to build on NDK v22 by using the included toolchain file: https://developer.android.com/ndk/guides/cmake#android_ld

My steps:
```
git clone https://github.com/json-c/json-c.git
cd json-c/
mkdir json-c-build
cd json-c-build/
export NDK_HOME=~/Library/Android/sdk/ndk/22.1.7171670/
cmake \
    --toolchain=$NDK_HOME/build/cmake/android.toolchain.cmake \
    -DANDROID_STL=none \
    -DANDROID_ABI=arm64-v8a \
    -DANDROID_PLATFORM=android-29 \
    -DANDROID_LD=lld \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=<install prefix> \
    -DENABLE_THREADING=true \
    -DDISABLE_WERROR=true \
    ..
make install
```
(Some of these flags are likely not necessary)

The only issue I have is a warning about superfluous bits in `open` in one of the tests, hence the `DISABLE_WERROR`:
```
[ 88%] Building C object tests/CMakeFiles/test_util_file.dir/test_util_file.c.o
<redacted>/json-c/tests/test_util_file.c:96:35: warning: 'open' has superfluous mode bits; missing O_CREAT? [-Wuser-defined-warnings]
        int d = open(file, O_RDONLY, 0600);
                                         ^
/Users/wjordan/Library/Android/sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/bits/fortify/fcntl.h:76:9: note: from 'diagnose_if' attribute on 'open':
        __clang_warning_if(!__open_modes_useful(flags) && modes,
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/wjordan/Library/Android/sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/sys/cdefs.h:139:54: note: expanded from macro '__clang_warning_if'
#define __clang_warning_if(cond, msg) __attribute__((diagnose_if(cond, msg, "warning")))
                                                     ^           ~~~~
1 warning generated.
```

**Comment by Haidar0096** [comment]
@wjorda this works nicely, thank you very much, maybe they should update the docs to include your steps
