### ISSUE TITLE
autogen.sh missing from repository

### ISSUE THREAD

**Issue by EddyHahn** [json-c/json-c#574]
Hi,
When I pull the repository and try to run autogen.sh it fails because the file is not included in the repository.

Thanks,

Eddy

**Comment by ploxiln** [comment]
intentionally removed in favor of cmake
https://github.com/json-c/json-c/commit/95737df9d40d21dd192a55588c2a4823702a589b

**Comment by hawicz** [comment]
I'm updating README.md to include current build instructions.

**Comment by hawicz** [comment]
See commit 270dc2f9, or https://github.com/json-c/json-c#readme
