### ISSUE TITLE
10796 Segmentation fault

### ISSUE THREAD

**Issue by guoyanzhang0817** [json-c/json-c#586]
CHAR *jsonMsgBuf = "{\"status\":\"online\",\"test\":\"aaa\"}";
	
    printf("\n@The parsing message is @ %s\n", jsonMsgBuf);
    pstObj = json_tokener_parse(jsonMsgBuf);
	
    if (NULL == pstObj)
    {
		printf("%s : json_tokener_parse failed.\n", __FUNCTION__);
    }
    else
    {
		json_object_object_foreach(pstObj, key1, val1)
        {
			if (0 == strcmp(key1, STATUS))
            {
                if (strcmp(json_object_get_string(val1), ON_LINE) == 0)
				{
					return 0;
				}
				else if (strcmp(json_object_get_string(val1), OFF_LINE) == 0)
				{
					return 1;
				}
            }
        }
		printf("127\n");
    }

**Comment by guoyanzhang0817** [comment]
There is an ‘10796 Segmentation fault’ problem with this code，why?

**Comment by hawicz** [comment]
Works fine for me.  I think your problem must lie outside of the code you posted.

**Comment by guoyanzhang0817** [comment]
thanks，i have solved it , because i used old json header files.
