### ISSUE TITLE
Building both static and shared libraries

### ISSUE THREAD

**Issue by jsmolic** [json-c/json-c#593]
Hi,
I'm currently using this package on Gentoo Linux, and I have a question on building static libraries. I would like to know whether it would be possible to build both static and shared library. I've investigated a bit, and if I'm not mistaken `CMakeLists` only enables either static or shared library, not both. I would like to add config option in Gentoo package which would enable building both static and shared libraries if static-libs support is selected. Would it be possible to do this? Thank you for answer.

Kind regards,
Jakov

**Comment by hawicz** [comment]
d'oh!  I knew there was something I forgot to get in to the last release.
I hope it's possible to do, but I don't know how off hand.  If you can dig up how to get cmake to do this, or even provide a PR, it would be greatly appreciated.

**Comment by jsmolic** [comment]
It should be doable, I'll investigate and try to come up with something when I catch some time :)

**Comment by jsmolic** [comment]
@dota17 @hofnarrr Thank for fixing this
