### ISSUE TITLE
QA Notice: Package triggers severe warnings

### ISSUE THREAD

**Issue by jsmolic** [json-c/json-c#596]
I ran into some warnings while compiling from master branch on Gentoo Linux:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/dev-libs/json-c-9999/work/json-c-9999/apps/json_parse.c:147:23: warning: format '%s' expects a matching 'char *' argument [-Wformat=]

```

**Comment by ploxiln** [comment]
This is in a demo program which is not used by the library.

```c
	fprintf(fp, "Usage: %s [-f] [-n] [-s]\n");
	fprintf(fp, "  -f - Format the output with JSON_C_TO_STRING_PRETTY\n");
	fprintf(fp, "  -n - No output\n");
	fprintf(fp, "  -s - Parse in strict mode, flags:\n");
	fprintf(fp, "       JSON_TOKENER_STRICT|JSON_TOKENER_ALLOW_TRAILING_CHARS\n");

	fprintf(fp, "\nWARNING WARNING WARNING\n");
	fprintf(fp, "This is a prototype, it may change or be removed at any time!\n");
```

That first line was intended to be something like:

```c
	fprintf(fp, "Usage: %s [-f] [-n] [-s]\n", argv[0]);
```

but must have been broken during refactoring, and wasn't noticed because this file/tool is very rarely used (and never used by programs that use `libjson-c`).

**Comment by ploxiln** [comment]
... and turns out this function is never called by this test program (or anything else), it's dead code currently ...

**Comment by hawicz** [comment]
Yeah, there were some other issue too, that I fixed and forgot to push.  oops.  Thanks for the PR.
