### ISSUE TITLE
Update to 0.15 release

### ISSUE THREAD

**Issue by jsmolic** [json-c/json-c#605]
Hello,

regarding recent security fixes and static-libs support patches, it would be good to release 0.15 versions (also in line with https://github.com/json-c/json-c/pull/603) so that downstream Linux distributions can have the latest updates in the package without the need to apply patches. Are there any plans for 0.15 in the near future?
Thank you.

Kind regards,
Jakov

**Comment by hawicz** [comment]
Yes, there will be a 0.15 release somewhat soon.  There's no need to open issues for things like this.
