### ISSUE TITLE
New release with security fix

### ISSUE THREAD

**Issue by ericonr** [json-c/json-c#615]
Hey there! I imagine you are dealing with fixing the CVE for all versions of json-c right now, but once that's more or less dealt with, would it be possible to make a new release (possibly 0.14.1)? It would make packaging a lot easier.

If you need any non-qualified help, lmk.

**Comment by ericonr** [comment]
Found the closed issues, sorry.

**Comment by hawicz** [comment]
Yes, please ask questions on the mailing list, not as reported bugs.
