### ISSUE TITLE
Parsing fails if UTF-16 low surrogate pair is not in same chunk is the high pair

### ISSUE THREAD

**Issue by bpeel** [json-c/json-c#616]
It looks like if a Unicode character outside the basic multilingual plane is encoded as a UTF-16 surrogate pair, then the second half of the pair has to be given to the parser in the same call to `json_tokener_parse_ex` or it will fail to parse. This is quite annoying if you are parsing a long JSON file by reading it in chunks because it’s hard to control where the buffer will be split.

Please look at the following example:

```C
#include <json_object.h>
#include <json_tokener.h>
#include <stdio.h>
#include <string.h>

static const char *
strings[] = {
        /* This is U+1D11E encoded as two UTF-16 surrogate pairs. The
         * parsing will be split into chunks. The split is in the
         * middle of the escape sequence for the second part of the
         * pair.
         */
        "\"\\ud834\\u",

        "dd1e\""
};

int
main(int argc, char **argv)
{
        struct json_tokener *tokener;

        tokener = json_tokener_new();

        struct json_object *o;

        o = json_tokener_parse_ex(tokener,
                                  strings[0],
                                  strlen(strings[0]));

        printf("After parsing first chunk:\n"
               "object = %p\n"
               "error = %s\n",
               o,
               json_tokener_error_desc(json_tokener_get_error(tokener)));

        o = json_tokener_parse_ex(tokener,
                                  strings[1],
                                  strlen(strings[1]));

        printf("After parsing second chunk:\n"
               "object = %p\n"
               "error = %s\n",
               o,
               json_tokener_error_desc(json_tokener_get_error(tokener)));

        /* Combine the two chunks into one to parse it as a single chunk */
        static char buf[1024];
        strcat(buf, strings[0]);
        strcat(buf, strings[1]);

        tokener = json_tokener_new();

        o = json_tokener_parse_ex(tokener, buf, strlen(buf));

        printf("After parsing as single chunk:\n"
               "object = %p\n"
               "error = %s\n",
               o,
               json_tokener_error_desc(json_tokener_get_error(tokener)));

        return 0;
}
```

**Version and Platform**
- json-c git commit hash `5b15c7567d05a6ad834c96461766340c187dfcc9`

**Comment by hawicz** [comment]
The output I get is:

```
$ gcc -g -Iinclude/json-c -Llib64 -Wl,-R`pwd`/lib64 test.c -ljson-c
$ ./a.out
After parsing first chunk:
object = (nil)
error = continue
After parsing second chunk:
object = (nil)
error = invalid string sequence
After parsing as single chunk:
object = 0xb3b970
error = success
```

The tokener code remembers that it's in state json_tokener_state_escape_unicode, but doesn't currently have any way to track that it's in the "high surrogate" substate, plus it gets the check for the start of the next unicode escape(i.e. `tok->st_pos == 4`) wrong, which fails even with a non-surrogate-pair unicode escape that's split after the `\u`.

We'll need to at least move the `got_hi_surrogate` field into struct json_tokener, but I think we'll _also_ need to separately track how far into the `\uNNNN` escape we are, instead of assuming `st_pos` will be usable without adjustment.

**Comment by dota17** [comment]
Yes, @hawicz . ```json_tokener```'s support for surrogate pair is not enough. And , I also find that if the buffer-split position is not controlled, the UTF-8 validate will also failed. like:
https://github.com/json-c/json-c/blob/fbe15436447b8b6e2c9eb4419fdc37cc8ef5b2cc/tests/test_parse.c#L384

**Comment by bpeel** [comment]
It might be nice to make a test case that parses a complicated JSON file by feeding one character at a time to `json_tokener_parse_ex` and making sure that it gets the same result as if the entire file is parsed with a single call. That way it could pick up any other missing state not tracked by the tokener.

Another option might be to make all of these existing tests also test by parsing one character at a time.

**Comment by hawicz** [comment]
The "test_parse" test has various explicit incremental parsing checks, but it would be fairly easy to tweak the single_basic_parse() function there to run multiple times, feeding the strings to json_tokener_parse() in various chunk sizes. (i.e. in chunks of n for every n from 1...strlen(test_string) )
I'm not going to have time to look at fixing the parsing code for a while though, so if anyone has some proposed fixed they'd be most welcome.

**Comment by dota17** [comment]
I try to implement this feature and supplement the testcase. Let's check them.

**Comment by hawicz** [comment]
I just merged #616, but it's not a complete fix, so I'm leaving this ticket open.

**Comment by hawicz** [comment]
I have some changes that I think will fix this, stay tuned.

**Comment by hawicz** [comment]
I believe this is now fixed, along with other incremental/partial parsing issues (e.g. see f23486a, 6eac698).
