### ISSUE TITLE
 json_tokener_parse : Segmentation fault

### ISSUE THREAD

**Issue by guoyanzhang0817** [json-c/json-c#623]
```c
407 void TestSegFunction(void)
408 {
409     int i = 0;
410     char *str = "\"{\"loop_number\":1}\"";     //wrong string
411 //    char *str = "{\"loop_number\":1}";     //right string
412     json_object *pstObj = NULL;
413     json_object *sonPstObj = NULL;
414     pstObj = json_tokener_parse(str);    //there is an issue.
415     if (NULL == pstObj)
416     {
417         printf("%s : json_tokener_parse failed.\n", __FUNCTION__);
418     }
419     else
420     {
421         json_object_object_foreach(pstObj, key1, val1)
422         {
423             if (0 == strcmp(key1, LOOP_NUMBER))
424             {
425                 i = json_object_get_int(val1);
426                 printf("i = %d\n", i);
427             }
428         }
429     }
430 }
```
====================
As shown in lines 410 and 411, if 410 lines of code are used, there will be a segment error in 414 lines of function calls. If 411 lines of code are used, there will be no error in 414 lines, because this function is called by others, and they may enter an error string. I don't want to see the segment error to stop the program. Is there any way to avoid this kind of paragraph error?

**Comment by hawicz** [comment]
There's no bug in json-c here, and the crash actually happens on line 421:
```
$ gdb ./apps/json_parse  # including your code
...
(gdb) run
Starting program: /home/erh/json-c/build/./apps/json_parse

Program received signal SIGSEGV, Segmentation fault.
0x0000000000401586 in TestSegFunction ()
    at /home/erh/json-c/apps/json_parse.c:174
174             json_object_object_foreach(pstObj, key1, val1)
(gdb)
```

The problem is that you're trying to iterate over something that isn't of type json_type_object.  You need to add a check like `if (json_object_get_type(pstObj) != json_type_object) { ...handle error...}` before the json_object_object_foreach

**Comment by guoyanzhang0817** [comment]
> There's no bug in json-c here, and the crash actually happens on line 421:
> 
> ```
> $ gdb ./apps/json_parse  # including your code
> ...
> (gdb) run
> Starting program: /home/erh/json-c/build/./apps/json_parse
> 
> Program received signal SIGSEGV, Segmentation fault.
> 0x0000000000401586 in TestSegFunction ()
>     at /home/erh/json-c/apps/json_parse.c:174
> 174             json_object_object_foreach(pstObj, key1, val1)
> (gdb)
> ```
> 
> The problem is that you're trying to iterate over something that isn't of type json_type_object. You need to add a check like `if (json_object_get_type(pstObj) != json_type_object) { ...handle error...}` before the json_object_object_foreach

thanks，very good!
