### ISSUE TITLE
Linking with Windows MINGW not working

### ISSUE THREAD

**Issue by julienmalard** [json-c/json-c#630]
Hello,
I am not sure if this is a bug in Json-c or if I am simply missing something (if the latter, appologies and please do let me know where better to post).

**Describe the bug**
I have successfully linked a fortran/c project to json-c (using `#include <json.h>` in the c file) while compiling under both MacOS and Linux. However, I cannot seem to get it to compile under Windows using MINGW (using VS is not an option because I also need some default MINGW libraries).
While json-c builds on the other platforms, on Windows it does not seem to clone or build at all and the build proceeds directly to my project's fortran and c files, then warns of a `Nonexistent include directory 'C:/Users/travis/build/joelz575/swatplus/build/external/include/json-c'`, and finally (expectedly) terminates with the error `fatal error: json.h: No such file or directory #include <json.h>`. If it is of any use, here is the build: https://travis-ci.com/github/joelz575/swatplus.

**Steps To Reproduce**
I compiled using the following steps:
```
mkdir build
cd build
cmake  -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ../src
cmake --build .
```
Below is my `CMakeLists.txt file`:
```
cmake_minimum_required (VERSION 3.12)

enable_language(Fortran)
project(SwatPlus)

FILE(GLOB src *.f90 *.c)
add_executable(swatplus_exe ${src} )

include(ExternalProject)
set(EXTERNAL_INSTALL_LOCATION ${CMAKE_BINARY_DIR}/external)
ExternalProject_Add(json-c
  GIT_REPOSITORY    https://github.com/json-c/json-c.git
  CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${EXTERNAL_INSTALL_LOCATION}
)

include_directories(${EXTERNAL_INSTALL_LOCATION}/include/json-c)
link_directories(${EXTERNAL_INSTALL_LOCATION}/lib)

install(TARGETS swatplus_exe DESTINATION bin)
```

**Version and Platform**
- json-c version: master branch from GitHub
- OS: Windows Server on Travis CI

Many thanks in advance,
Julien Malard

**Comment by hawicz** [comment]
https://stackoverflow.com/questions/15175318/cmake-how-to-build-external-projects-and-include-their-targets and https://stackoverflow.com/a/60606636/28275 look like they would be relevant to what you're trying to do.
Simply adding ExternalProject_Add() to your CMakeLists.txt doesn't build the json-c right away, so the include_directories, etc.. lines just after it aren't going to work.

Reading through some of the answers, you might have luck using https://cmake.org/cmake/help/v3.17/module/FetchContent.html instead.

**Comment by julienmalard** [comment]
@hawicz Many thanks, it works now! `FetchContent` did the trick.

**Comment by manjavacasjaime** [comment]
hey @julienmalard would you mind showing your working CMakeLists.txt file?? please

**Comment by julienmalard** [comment]
Sure, here it is:
https://github.com/joelz575/swatplus/blob/master/src/CMakeLists.txt

**Comment by manjavacasjaime** [comment]
@julienmalard thanks a lot for your extremely fast answer :))))
Do you remember which value did you gave to `${json-c_SOURCE_DIR}` ??? Or is it an auto-defined variable??

**Comment by hawicz** [comment]
That variable (and a couple others) are set by the FetchContent_MakeAvailable call. See https://cmake.org/cmake/help/latest/module/FetchContent.html#command:fetchcontent_makeavailable

**Comment by julienmalard** [comment]
No problem @manjavacasjaime! I'd forgotten the answer to that question but thanks @hawicz for answering.

**Comment by manjavacasjaime** [comment]
Thanks for your help guys! Problem was I'm building an OBS plugin and I guess OBS does not like the FetchContent thing.
Downloading the source code and building it with CMake works just fine.
