### ISSUE TITLE
expression has no effect warning in json_tokener.c

### ISSUE THREAD

**Issue by ssrlive** [json-c/json-c#635]
Current codebase, cmake build it on Ubuntu 20.04, 
I can't build it with `cmake . && make` command. It report error and stop.

I have to change this switch to ON, it can continue.

https://github.com/json-c/json-c/blob/7d3c2d9fad992293c1001e86789b866a5a168e4d/CMakeLists.txt#L96

and the output info like this.

```
/json-c/json_tokener.c: In function ‘json_tokener_parse_ex’:
/json-c/json_tokener.c:244:64: warning: right-hand operand of comma expression has no effect [-Wunused-value]
  244 | #define ADVANCE_CHAR(str, tok) (++(str), ((tok)->char_offset)++, c)
      |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
/json-c/json_tokener.c:649:5: note: in expansion of macro ‘ADVANCE_CHAR’
  649 |     ADVANCE_CHAR(str, tok);
      |     ^~~~~~~~~~~~
[ 12%] Building C object CMakeFiles/json-c.dir/json_util.c.o
```

please fix it.

**Comment by egee-irl** [comment]
Bumping - this is failing for me also.

**Comment by hawicz** [comment]
This doesn't seem to have anything to do with cmake.

**Comment by ssrlive** [comment]
So I hope you can change the C code, Not the cmake code.
