### ISSUE TITLE
json_object_put()  has 'double free or corruption (out) '

### ISSUE THREAD

**Issue by guoyanzhang0817** [json-c/json-c#637]
`UCHAR* ExtractMqtt_AndroidRequestStopModule(CHAR *jsonMsgBuf, INT32 *plen)   
{

    /*
	[
		{"loop_number": 1,  "sensor_address":1},
		{"loop_number": 1,  "sensor_address":1},
		{"loop_number": 2,  "sensor_address":1},
		{"loop_number": 2,  "sensor_address":1},
		…
	]
	*/
	// INT32 ln = 0;
	// INT32 sd = 0;
	INT32 i = 0;
	INT32 count = 0;
	INT32 temp = 0;
	json_object *array = NULL;
	struct json_object *arrayObj = NULL;
	UCHAR *moduleArray = NULL;

	array = json_tokener_parse(jsonMsgBuf);
	if (NULL == array)
    {
        printf("%s : json_tokener_parse failed.\n", __FUNCTION__);
		return NULL;
    }
    else
    {
		if (json_object_get_type(array) != json_type_array)
    	{
            json_object_put(array);
            printf(" %s an error json string!\n", __FUNCTION__);
            return NULL;
        }
		count = json_object_array_length(array);
		if (count < 1)
		{
			return NULL;
		}
		temp = count;
		*plen = 2*count+4;
		moduleArray = (UCHAR*)malloc(count*sizeof(UCHAR));
		if (moduleArray == NULL)
		{
			printf("%s malloc failed!\n");
			return NULL;
		}
		memset(moduleArray, 0, (2*count+4));
		count = 0;
 		for (i = 0; i < temp; i++)
		{
			arrayObj = json_object_array_get_idx(array, i);
			json_object_object_foreach(arrayObj, key1, val1)
			{
				if (0 == strcmp(key1, LOOP_NUMBER))
				{
					moduleArray[2+count] = json_object_get_int(val1);
					//printf("(debug) parsing value is %d\n", moduleArray[i].loopNumber);
				}
				else if (0 == strcmp(key1, SENSOR_ADDRESS))
				{
					moduleArray[2+count+1] = json_object_get_int(val1);
					//printf("(debug) parsing value is %d\n", moduleArray[i].sensorAddress);
				}
				//AllSensorInfoArray[ln-1][sd-1].startStopFlag = 2;  
			}
			count += 2;
        }
    }
	printf("first\n");
	json_object_put(array);                   //mark
	printf("first end!\n");
	return moduleArray;
}   `

**Comment by hawicz** [comment]
Both the call to memset() and for for-loop overrun the end of moduleArray.  Once you do that, don't expect much else to work reliably.

Also, a couple of other things:
You're missing json_object_put(array) calls in the "if (count < 1)" and "if (moduleArray == NULL)" cases)
Using a json_object_object_foreach loop is a bit silly to do here.  You should just use json_object_object_get() with the two keys you need.

**Comment by guoyanzhang0817** [comment]
> json_object_object_get()
------
Thank you for your answer, very nice. By the way, you suggest using thejson_object_object_get() function. Is it like this? So what's the advantage of it over the previous json_object_object_foreach() function? For example, fast execution?
------
 		for (i = 0; i < temp; i++)
		{
			arrayObj = json_object_array_get_idx(array, i);
			sonArrayObj = json_object_object_get(arrayObj, LOOP_NUMBER);
			moduleArray[2+count] = json_object_get_int(sonArrayObj);
			 printf("(debug) parsing value is %d\n", moduleArray[2+count]);
			sonArrayObj = json_object_object_get(arrayObj, SENSOR_ADDRESS);
			moduleArray[2+count+1] = json_object_get_int(sonArrayObj);
			printf("(debug) parsing value is %d\n", moduleArray[2+count+1]);
			/* json_object_object_foreach(arrayObj, key1, val1)
			{
				if (0 == strcmp(key1, LOOP_NUMBER))
				{
					moduleArray[2+count] = json_object_get_int(val1);
					// printf("(debug) parsing value is %d\n", moduleArray[i].loopNumber);
				}
				else if (0 == strcmp(key1, SENSOR_ADDRESS))
				{
					moduleArray[2+count+1] = json_object_get_int(val1);
					// printf("(debug) parsing value is %d\n", moduleArray[i].sensorAddress);
				}
				// AllSensorInfoArray[ln-1][sd-1].startStopFlag = 2;  //表示要停止
			} */
			count += 2;
        }

**Comment by hawicz** [comment]
If you're input data doesn't actually have more fields present in each object, I wouldn't expect much of a difference in speed; mostly I just think the code would be easier to understand if you eliminate that loop.

**Comment by guoyanzhang0817** [comment]
> If you're input data doesn't actually have more fields present in each object, I wouldn't expect much of a difference in speed; mostly I just think the code would be easier to understand if you eliminate that loop.

OK, thank you again for your wonderful reply.
