### ISSUE TITLE
not able to compare with string

### ISSUE THREAD

**Issue by paragikjain** [json-c/json-c#643]
```
struct json_object *input_method;
json_object_object_get_ex(parsed_json, "input_method", &input_method);
json_object_get_string(input_method)
```
so here  by line 3 i am getting some string as output but same string i am comparing with this json_object_get_string(input_method) function it is returning false. and when i do sizeof(json_object_get_string(input_method)) it always gives me 8 no matter what is the size of string in my json

**Comment by MarcT512** [comment]
You should use strlen() to get the length of a string. The sizeof() you’re using below will return the size of the pointer variable that points to the string. 8 bytes is 64 bits, so you’re on a platform that has 64 bit pointers.

Hope that helps!

**Comment by hawicz** [comment]
Also, you can use `json_object_get_string_len(input_method)`, which will be slightly more efficient than strlen().  e.g. (omitting any error handling):

```
struct json_object *input_method;
json_object_object_get_ex(parsed_json, "input_method", &input_method);
char *s = json_object_get_string(input_method);
int slen = json_object_get_string_len(input_method); // Equivalent, but faster than strlen(s)
printf("My string of length %d is: %s\n", slen, s);
```

Note that this is only valid if the value at key "input_method" really is a json_type_string.
