### ISSUE TITLE
Why src->_userdata not checked before calling strdup?

### ISSUE THREAD

**Issue by Pandorus2012** [json-c/json-c#644]
In json_object.c (line 1631) strdup called, but i cant find check for src->_userdata. Line 1625 you check (!src->_userdata && !src->_user_delete), but we can have situation when (src->_userdata == null, src->_user_delete != null).

**Comment by hawicz** [comment]
If the serializer is set to json_object_userdata_to_json_string the object is _required_ to have _userdata set, so there's no point in checking.
Note that if _userdata is NULL you'll also crash while serializing at the strlen() call in json_object_userdata_to_json_string  https://github.com/json-c/json-c/blob/master/json_object.c#L1154

**Comment by Pandorus2012** [comment]
I got it, thanks for the answer!
