### ISSUE TITLE
Misuse of tolower() in json_tokener.c

### ISSUE THREAD

**Issue by pascal-cuoq** [json-c/json-c#645]
Hello, I am a colleague of @jakub-zwolakowski. There is a last minor
problem we found by running extra tests that I thought you might want
to hear about.

In `json_tokener.c`, the standard function `tolower` [is used to
recognize the multiple forms that infinity can take](https://github.com/json-c/json-c/blob/a4e3700972fe1582189d7b5594b54b940894bdff/json_tokener.c#L433
):

```
inf_char = tolower((int)*str);
```

Here `str` is a pointer to `char` and is used to access a `char`
straight from the input. `char` is a signed type on most platforms,
in particular x86.

The clause [7.4:1 of the C17 standard](https://cigix.me/c17#7.4.p1) applies to `tolower`:

> In all cases the argument is an int, the value of which shall be representable as an unsigned char
> or shall equal the value of the macro EOF. If the argument has any other value, the behavior is
> undefined.

In principle, a libc could implement `tolower` with a
look-up table and omit the bound checks on the argument. If JSON-C
were used with such a libc, a malicious input containing well-placed
negative chars could cause an out-of-bounds read, possibly leading to a crash.

Since the behavior is undefined, an implementation of `tolower` could also
return `'i'`, `'n'`, `'f'`, `'n'`, `'t'`, or `'y'` for some negative `char`
values, leading the parser to recognize “infinity” in inputs that do
not contain this word.

In practice, Glibc does implement `tolower` with a look-up table, but
it validates the range of the input first, and musl-libc uses a
straightforward `if` to detect uppercase letters.  Neither of these
popular implementations will have the hypothetical problems above.

Interestingly, in the current version of the line, the char `*str` is
explicitly cast to `int` before being passed to `tolower`.  This cast
was introduce by this commit: [Add cast to int on tolower() to fix
warnings about array subscripts](https://github.com/json-c/json-c/commit/0e7ec2ffcda6591edb0475da64971b737aa5db6f).

The warning in question is likely GCC's warning about using a `char`
expression as array index, and we can infer that the headers of some
compilation platforms also expand `tolower(e)` to an expression in
which `e` is used as an array index (hopefully after having been
validated, but the compiler is not sophisticated enough to recognize
this and omit the warning).

I would suggest the following line as a replacement:
```
inf_char = tolower((unsigned char)*str);
```

This would silence GCC's ` -Wchar-subscripts` warning and it would
also ensure that the function `tolower` is used according to the
minimal guarantees provided by the C standard.

**Comment by ploxiln** [comment]
I suggest opening a quick pull request with this proposed change.
