### ISSUE TITLE
json-c tag 0.15 tarball contains a file doc/Doxyfile and generated doxygen files in doc/html

### ISSUE THREAD

**Issue by babelouest** [json-c/json-c#649]
**Describe the bug**
The last release tag 0.15 contains a file doc/Doxyfile which should be generated by cmake during build process.

Also, I don't know if that's expected, but the tarball downloaded from 0.15 tag contains the generated Doxygen files in doc/html/

**Steps To Reproduce**
Check file [doc/Doxyfile](https://github.com/json-c/json-c/blob/json-c-0.15/doc/Doxyfile) and the folder [doc/html](https://github.com/json-c/json-c/tree/json-c-0.15/doc/html) in the branch json-c-0.15.

**Comment by hawicz** [comment]
That's expected, part of the release process involved generating the docs.

**Comment by babelouest** [comment]
> That's expected, part of the release process involved generating the docs.

That's ok, but the file doc/Doxyfile is th one generated by `configure_file` in the cmake script, see : https://github.com/json-c/json-c/blob/json-c-0.15/doc/Doxyfile#L61 for example

**Comment by hawicz** [comment]
Yeah, that's not going to be too useful, other than to show how exactly the docs were built.  I'll make a note to drop that for the next release.
Fortunately, the presence of a Doxyfile there doesn't prevent cmake from creating a working one in your build directory, so a `make doc` will continue to work.
