### ISSUE TITLE
Waste memory

### ISSUE THREAD

**Issue by oneonce** [json-c/json-c#652]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/forum/#!forum/json-c

**Describe the bug**
A clear and concise description of what the bug is, and any information about where you're running into the bug that you feel might be relevant.

**Steps To Reproduce**
List the steps to reproduce the behavior.
If possible, please attach a sample json file and/or a minimal code example.

**Version and Platform**
- json-c version: [e.g. json-c-0.14, or a specific commit hash]
- OS: [e.g. Ubuntu 20.04, Debian Buster, NetBSD 9, etc...]
- Custom cmake/build flags, if any

**Comment by oneonce** [comment]
uinon Value
{
    char* valuestring;
    //int valueint; // can not save 0xffffffffffffffff
    long valuelong; // can save 0xffffffffffffffff
    double valuedouble;
} value;

**Comment by hawicz** [comment]
Were you meaning to report something?  Closing, since there doesn't seem to be anything here.
