### ISSUE TITLE
[Question] Is it possible to clear a ptr of json_object?

### ISSUE THREAD

**Issue by jclaessens97** [json-c/json-c#683]
Hello,

I came a cross a frustrating issue where I need to clear a json_object.
3 months ago I finished the code to parse a rabbitMQ message with json, do some calculations and then push the message back on the queue by creating a new json message with this lib.

However I forgot to clear the object_new which lead to a memory leak. Stupid but no worries I thought so I fixed it with this:

```
return json_object_to_json_string(root);
```
to 

```
const char* message = json_object_to_json_string(root);
json_object_put(root);
return message;
```
 However this leads to an issue that sometimes the message I send to rabbitmq is empty (not always, which seems odd imo).

I just read the last line of the README.md, and apparently the string is somehow still related to the json_object I deleted with `json_object_put`?

Now my question is how can I use a pointer of `json_object` to delay the cleanup after the message has been published?
If I use a pointer, pass it to my method and clean it afterwards it hits the assert of the `ref_count` in `json_object_put`.

This is what I tried so far:

main.c
```
  json_object* rootJsonObj;
  const char* outMessage = createMessage(rows, cols, &input, output, &rootJsonObj);
  publishMessage(conn, EVENT_QUEUE, outMessage);

  json_object_put(&rootJsonObj);
```

createMessage()
```
  *root = json_object_new_object();
  json_object_object_add(*root, "uid", uid);
  json_object_object_add(*root, "type", type);
  return json_object_to_json_string(*root);
```

If there is an alternative that I can apply, would be fine as well, but I definitely need to fix the memory leak.

Thanks!

**Comment by jclaessens97** [comment]
Not nescessary anymore.

**Comment by hawicz** [comment]
json_object_to_json_string() returns a pointer to a buffer allocated within the json_object structure.  If you free the json_object with json_object_put(), that memory is no longer valid, so you need to either ensure that the json_object's lifetime is long enough to cover all uses of the that string, or strdup() it, as [the docs suggest](https://json-c.github.io/json-c/json-c-current-release/doc/html/json__object_8h.html#ab7390c22baa1700d977c2af6b22d43a4) (and make sure to free that later!)

**Comment by jclaessens97** [comment]
strdup() did the trick. I only read that part of the docs after I asked the question. Sorry and thanks!

**Comment by hawicz** [comment]
Glad you got it working!  btw, in the future for general help, rather than bug reports, please use the forum over at https://groups.google.com/forum/#!forum/json-c

**Comment by jclaessens97** [comment]
Gotcha!
