### ISSUE TITLE
Remove dependency on libM::getrandom

### ISSUE THREAD

**Issue by tgraupmann** [json-c/json-c#686]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/forum/#!forum/json-c

**Describe the bug**
This JSON library has a dependency on getrandom from the math library libM which can't be statically linked. This is fine for compiling with gcc or clang. This is an issue for some LLVM pipelines (Google cough).

https://github.com/json-c/json-c/blob/1bc7a6b223429684107e5141a33bfabc44ab1a32/random_seed.c#L173

You can use a random lookup table instead.

**Steps To Reproduce**
List the steps to reproduce the behavior.
If possible, please attach a sample json file and/or a minimal code example.
Try to compile a C static library linking libM.a. This isn't possible.

**Version and Platform**
- json-c version: [e.g. json-c-0.14, or a specific commit hash]
- OS: [e.g. Ubuntu 20.04, Debian Buster, NetBSD 9, etc...]
- Custom cmake/build flags, if any
Latest master branch has this issue.

OS: Ubuntu 20.04

**Comment by hawicz** [comment]
If you have some environment where linking in getrandom is a problem, you can always arrange for HAVE_GETRANDOM to not be set, though I would expect the check_symbol_exists() call in CMakeLists.txt to already handle this.
I really have no interest in including an implementation of a random number generator in json-c, closing.
