### ISSUE TITLE
Does not build on Apple Silicon M1

### ISSUE THREAD

**Issue by EddyHahn72** [json-c/json-c#687]
**Describe the bug**
Checking out code from GItHub the build fails ld because CMake!? doesn't know what to do with Apple Silicon M1 (arm64)

**Steps To Reproduce**
git clone https://github.com/json-c/json-c.git
cd json-c
cmake

**Version and Platform**
- json-c version: latest form gitHub
- OS: macOS Big Sur on Apple Silicon M1

Error:

ld: warning: ignoring file CMakeFiles/test_object_iterator.dir/test_object_iterator.c.o, building for macOS-x86_64 but attempting to link with file built for unknown-arm64
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by hawicz** [comment]
If cmake doesn't handle this yet, there's probably not much we can do in json-c.  However, if you want to send me an M1 machine I'd be happy to take a look :)

**Comment by EddyHahn72** [comment]
You wish :-) but seriously all other library maintainer are fixing it by adding arm64. Lot of places when macOS is detected they default to x86_64. Just taking it from the OS instead of hard coding the value would fix it. 
Do you know which script the platform is detected? I'd give it a try to fi it...

**Comment by hawicz** [comment]
We don't detect the platform in _any_ script, we use cmake for platform specific operations that need to be done to build.  There's apparently all kinds of things to worry about wrt x86_64 vs arm64 on OSX, including the "Rosetta translation environment", considerations for the type of binary you're running (arm, x86 or universal) with probably plenty of opportunity for mismatch between what cmake runs as and what the compiler & linker run as and what they create.
Just a glance at some of the discussion around this (e.g. https://gitlab.kitware.com/cmake/cmake/-/issues/20989) makes it clear to me that I definitely do not know enough about it to even be able to suggest how to start fixing it.

**Comment by Kloenk** [comment]
It build on my m1, just the `LC_ID_DYLIB` in the dylib is wrong

**Comment by wit19** [comment]
> It build on my m1, just the `LC_ID_DYLIB` in the dylib is wrong

could you share what exactly you did with LC_ID_DYLIB and provide steps to fix it ?

**Comment by Kloenk** [comment]
It's a year ago, not sure anymore. Guess I looked at nixpkgs how the id is patched there. But would have to figure it out again.

**Comment by wit19** [comment]
Would be great ;)
As i'm a newbie in this section currently neither i know a piece about LC_ID_DYLIB nor nixpkgs ...
Just have instructions about the basics steps to take would be great, maybe [hawicz] is able to patch the issue with your help.

**Comment by Kloenk** [comment]
Im on vacation right now. I will try to remember doing it after. (Bit more than a week)

**Comment by wit19** [comment]
Enjoy your vacation ;) 
Any help is welcome, when you are back.

**Comment by bcr** [comment]
Using the master branch, it builds fine and the tests run on my M1. Is there any further action to take?

**Comment by hawicz** [comment]
I think we can close this for now.  If anyone is still having problems in the future (and ideally has a fix) they can reopen this, or start a new issue.
