### ISSUE TITLE
json-c-0.15-nodoc.tar.gz build fails

### ISSUE THREAD

**Issue by ploxiln** [json-c/json-c#688]
The download page includes a link to `json-c-0.15-nodoc.tar.gz`, similar to "nodoc" variants for many previous releases. However, the cmake build system does not work with the "doc" subfolder simply missing:

```
CMake Error at CMakeLists.txt:404 (add_subdirectory):
  add_subdirectory given source "doc" which is not an existing directory.
```

There is no conditional around `add_subdirectory(doc)`. I can work-around this by simply:

```
mkdir doc
touch doc/CMakeLists.txt
```

That is sufficient to make the build work. Of course, the regular `json-c-0.15.tar.gz` also works fine.

**Comment by hawicz** [comment]
I'm not going to fix the 0.15 (or 0.16) tarballs, but future nodoc tarballs will work better in this respect.
