### ISSUE TITLE
patch to add arc4random

### ISSUE THREAD

**Issue by hdatma** [json-c/json-c#692]
https://github.com/openbsd/ports/blob/22f59096e42f4bf9e6cd51073119c7653eaf83b9/devel/json-c/Makefile
https://github.com/openbsd/ports/tree/22f59096e42f4bf9e6cd51073119c7653eaf83b9/devel/json-c/patches

**Comment by hawicz** [comment]
Applied, with cmake changes instead of autoconf.

**Comment by An7ar35** [comment]
Head's up: geting a `/usr/bin/ld: ../libjson-c.so.5.1.0: undefined reference to `arc4random'` when trying to build from source now. Arch Linux 5.10.13, glibc 2.33-3, gcc 10.2.0, cmake.

P.s.: Thanks for all the work.

**Comment by hawicz** [comment]
In your build directory, does config.h have `#define HAVE_ARC4RANDOM`?  Does CMakeFiles/json-c.dir/link.txt include `-lbsd` ?  If not, I recommend trying with a brand new build dir.  If you're still having problems please post some more details over on https://groups.google.com/forum/#!forum/json-c and we'll try to sort things out.

**Comment by nmartin-cs** [comment]
@hawicz I'm seeing the same issue with cmake (3.19.6) / gcc (10.2.0)
```
$ mkdir build && cd $_
$ cmake ..
$ cmake -DCMAKE_INSTALL_PREFIX=/usr .
$ sudo make install  
...
[ 35%] Linking C executable test_float
/usr/bin/ld: ../libjson-c.so.5.1.0: undefined reference to `arc4random'
```
I'll take a look at your [commit](https://github.com/json-c/json-c/commit/041cef434afe0d0c6da8b6ac1d1fa26087246dda)

**Comment by moonburnt** [comment]
Got the same issue, thus had to downgrade to json-c-0.15-20200726 (luckily it wasn't critical). Cmake 3.22.2 + clang 13.0.1

**Comment by An7ar35** [comment]
For anyone that uses CMake, here's my work-around to avoid arc4random issues by compiling with it off and do static linking. In your `CMakeList.txt`:

```
set(JSONC_DOWNLOAD_PATH "${CMAKE_CURRENT_SOURCE_DIR}/tmp/libjsonc")
set(JSONC_INSTALL_PATH "${CMAKE_CURRENT_SOURCE_DIR}/external")

add_custom_target(make-jsonc-install-dir ALL
        COMMAND ${CMAKE_COMMAND} -E make_directory ${JSONC_INSTALL_PATH}
)

ExternalProject_Add(libjsonc
        PREFIX              "${JSONC_DOWNLOAD_PATH}"
        SOURCE_DIR          "${JSONC_DOWNLOAD_PATH}/src/libjsonc-build"
        GIT_REPOSITORY      "https://github.com/json-c/json-c.git"
        CMAKE_ARGS          "-DBUILD_STATIC_LIBS=ON"
                            "-DBUILD_SHARED_LIBS=OFF"
                            "-DCMAKE_INSTALL_PREFIX:PATH=${JSONC_INSTALL_PATH}"
                            "-DHAVE_ARC4RANDOM=OFF"
                            "-DCMAKE_BUILD_TYPE=release"
)

set(JSONC_LIBRARIES
        ${JSONC_INSTALL_PATH}/lib/libjson-c.a
        bsd
)
```

..and then:
```
add_executable(myapp ${SOURCE_FILES})
add_dependencies(myapp libjsonc)

target_link_libraries(myapp PRIVATE ${JSONC_LIBRARIES})
```

Hope that helps.

**Comment by hawicz** [comment]
No, that doesn't help.  @An7ar35, please explain over on #766 why you needed to do this, so I can detect whatever is wrong with your system and make it unnecessary.  (You turned off arc4random, _and_ you explicitly linked in libbsd, _and_ you needed to link statically?  What?)
