### ISSUE TITLE
json_object_get_string() return value truncated when assigning it to a pointer type in Win32 App

### ISSUE THREAD

**Issue by corkeee** [json-c/json-c#697]
I am currently developing an x64 Win32 App on VS 2017, which needs to link to the json-c.lib. 
When assigning the returned `const char*` of ` json_object_get_string()` to a pointer type, the upper 32bits seem to be truncated (see the debugger image for more info). My code is like this:
![image](https://user-images.githubusercontent.com/79334924/110507361-cb682200-80b4-11eb-9bd9-86878cd2d7ab.png)

The problem happens on line `ptr = json_object_get_string(js_obj);`. 

I've debugged with VS, I saw that the debugger could catch the correct return value. However, after the assignment, the upper 32 bits were truncated somehow. See the pic below.
![image](https://user-images.githubusercontent.com/79334924/110505215-ca35f580-80b2-11eb-8a44-5b6a830e71af.png)
The program was run on a VM and I used the remote debugger on VS. Both the host machine and the VM are windows 10 64 bits. I do not have any idea where the problem is from the C code itself since it happens after the assignment, the most basic operator in C. I double-checked the linked json-c.lib & json-c.dll by using `DUMPBIN /headers <filename> | findstr machine`, both are x64 version. 

Maybe I should disassemble the binary file and see the assembly code? Do you have any idea?

**Comment by hawicz** [comment]
That's a strange problem.  The only thing that comes to mind at the moment is that perhaps you're missing the json_object_get_string() prototype and thinking it returns an int, but I don't really see how that would be possible.

**Comment by corkeee** [comment]
> That's a strange problem. The only thing that comes to mind at the moment is that perhaps you're missing the json_object_get_string() prototype and thinking it returns an int, but I don't really see how that would be possible.

Yes, that's where the problem is. I checked the assembly code and find the unexpected `CDQE` instruction after the call to the function. Finally, I realized that somehow I forget to include json.h. So the compiler thinks the return value is int by default. Now the bug is fixed. Thanks a lot! I will close this issue.
