### ISSUE TITLE
Feature request: set allocator

### ISSUE THREAD

**Issue by darkSKULL-labs** [json-c/json-c#698]
Would like if could add custom memory allocator for malloc, calloc, realloc and free.

**Comment by ploxiln** [comment]
see #540

**Comment by darkSKULL-labs** [comment]
Thank you, I am not woried about those reason though. I decided I will have to just change how I was using it.

**Comment by michellemartni** [comment]
I’m no thank you sugar

**Comment by darkSKULL-labs** [comment]
I dont actually have a clue what that is about.
