### ISSUE TITLE
Linking to libjson-c Issue

### ISSUE THREAD

**Issue by nishithvpoojary** [json-c/json-c#699]
I have tried various ways. But I couldn't understand what the linking really meant. I use Windows 10.
![image](https://user-images.githubusercontent.com/45986919/112839628-09f16b00-90bc-11eb-8d9f-5beeff2f15b7.png)
This is what I'm trying to run.
![image](https://user-images.githubusercontent.com/45986919/112839692-1970b400-90bc-11eb-9a4b-7097d14049eb.png)
 Here which **Make file** are they talking about. Please provide the necessary details. Thank You.

**Comment by commodo** [comment]
you should use cmake to build this;
there's a guide here  https://github.com/json-c/json-c/wiki#building  using cmake + msbuild

but you should already be familiar with how to setup cmake + visual studio on windows;

**Comment by nishithvpoojary** [comment]
Thanks for your response. I opened the link you provided.
![image](https://user-images.githubusercontent.com/45986919/112951560-1d064880-9159-11eb-8997-f27dac7bb451.png)
I went to README.md from there and did the following
![image](https://user-images.githubusercontent.com/45986919/112951821-68b8f200-9159-11eb-84f9-70b189543ae0.png)
Now I have a "json-c-build" folder in my C Drive. Then I tried this below
![image](https://user-images.githubusercontent.com/45986919/112952006-9f8f0800-9159-11eb-93d6-754cefe1dbe3.png)
![image](https://user-images.githubusercontent.com/45986919/112952088-bdf50380-9159-11eb-8be4-537f8d48dd60.png)
 Should I skip this?

**Comment by hawicz** [comment]
By default, cmake will not create a Makefile when you're on Windows, so you need to use the windows-specific instructions in the _next_ paragraph of the README.md file.

**Comment by Prathik-Bhundary** [comment]
Thank You. Its Working.

**Comment by nishithvpoojary** [comment]
Thank you. Its working.
