### ISSUE TITLE
'file system sandbox blocked mmap()' error on iOS

### ISSUE THREAD

**Issue by Torrekie** [json-c/json-c#710]
**Describe the bug**
json-c dylibs not working on iOS, with error message:
```
iPhone:~/proj/json-c-json-c-0.15-20200726/build mobile$ ../tests/test1
dyld: Library not loaded: /var/mobile/proj/json-c-json-c-0.15-20200726/libjson-c.5.dylib
  Referenced from: /private/var/mobile/proj/json-c-json-c-0.15-20200726/build/../tests/test1
  Reason: no suitable image found.  Did find:
        /var/mobile/proj/json-c-json-c-0.15-20200726/libjson-c.5.dylib: file system sandbox blocked mmap() of '/var/mobile/proj/json-c-json-c-0.15-20200726/libjson-c.5.dylib'
        /usr/local/lib/libjson-c.5.dylib: code signature invalid for '/usr/local/lib/libjson-c.5.dylib'

        /usr/local/lib/libjson-c.5.dylib: stat() failed with errno=1
        /private/var/mobile/proj/json-c-json-c-0.15-20200726/libjson-c.5.1.0.dylib: file system sandbox blocked mmap() of '/private/var/mobile/proj/json-c-json-c-0.15-20200726/libjson-c.5.1.0.dylib'
Abort trap: 6
```

**Steps To Reproduce**
build, then `make test`, all tests fails

**Version and Platform**
- json-c version: [0.15]
- OS: [iOS]

**Comment by ploxiln** [comment]
The real reason is:
> code signature invalid for '/usr/local/lib/libjson-c.5.dylib'

This will depend on how you build and link json-c for your app. This repo's build scripts do not currently have anything iOS specific, as far as I can tell. (Maybe if you build and link statically into your app, it'll be effectively included during the normal app signature step?) You should probably ask your company's iOS build expert how to build and link C libraries for iOS.

**Comment by hawicz** [comment]
We don't really have support for iOS, and personally I don't know anything about building for that platform, so I don't think there's much I can help with here either.  If you do figure out what needs to happen, we can apply the fixes, but until then I'm going to close this issue.

**Comment by Torrekie** [comment]
I figured out this recently, as there is some sandbox restrictions in iOS, tasks that requiring mmap may needs additional codesign entitlements: `com.apple.private.security.container-required`, `get-task-allow` and `dynamic-codesigning`. Also, dylibs and executables required to be installed under /usr but not /usr/local (/usr/local are blocked to use mmap by sandbox).
For embedding to iOS apps may also requires `com.apple.security.cs.allow-jit` entitlement.
