### ISSUE TITLE
building json-c using cmake for ESP32

### ISSUE THREAD

**Issue by ameerhazo** [json-c/json-c#712]
Hello, I'm thinking about using this library in my program on my ESP32 as another library I'm trying to use is based on the json-c. Is it possible to do so? I'm quite a newbie at CMake still but I'm willing to learn. Thanks for the help.

Ameer

**Comment by hawicz** [comment]
This doesn't appear to be a bug report of any kind, closing.
Please ask general questions like this on more appropriate forums, such as https://groups.google.com/forum/#!forum/json-c, and when you do, you'll want to include more detail. i.e. what library are you trying to use (a fork of json-c?), what are you trying to do with it, what actual problems you've run into, etc...
