### ISSUE TITLE
When value converted to char* can not compare it with another value

### ISSUE THREAD

**Issue by gomidas** [json-c/json-c#713]
I am trying to check if keys value is equal to specific value. I can print it on screen but can not compare.

```
struct  JResult
{
    json_bool result;
    json_object *object;
};

struct JResult findJsonKey(json_object *json, char *key)
{
    struct JResult jr;
    json_object *foundJsonObj;
    json_bool b = json_object_object_get_ex(json, key, &foundJsonObj);
    jr.result = b;
    jr.object = foundJsonObj;

    return jr;
}
...
struct JResult jr;
      jr = findJsonKey(login_details_json, "username");
      if (jr.result)
      {
        printf("%s", json_object_get_string(jr.object)); //PRINTS myvalue

if( json_object_get_string(jr.object) == "myvalue")/PRINTS nothing
        printf("%s", json_object_get_string(jr.object));
      }
...
```

**Comment by MarcT512** [comment]
You can't compare strings like this in C
`if( json_object_get_string(jr.object) == "myvalue")`

You need to use strcmp() / strcasecmp() or better still strncmp() / strncasecmp () functions to check for string equality.

**Comment by gomidas** [comment]
> You can't compare strings like this in C:
> `if( json_object_get_string(jr.object) == "myvalue")`
> 
> What that actually does is compare a pointer to the return value of json_object_get_string(jr.object) against a pointer to (address in memory of) the string literal "myvalue", which will never be equal.
> 
> You must use strcmp() / strcasecmp() or better still strncmp() / strncasecmp () functions to check for string equality. You may need to include string.h. These functions all return 0 for equal strings.
> 
> Example:
> `if ( strcmp(json_object_get_string(jr.object), "myvalue") == 0 )`

Thank you. I forgot that.
