### ISSUE TITLE
json_object_from_file()  execution segment error

### ISSUE THREAD

**Issue by GuoYanZhang92** [json-c/json-c#725]
This is a piece of my code. I found that there will be segment errors after the code is executed to json_object_from_file(path), but I don't know why there will be segment errors, or what methods can be used to avoid segment errors when errors occur, or continue to execute the program?

`	
        #define FROM_FILE   1
        void Function(char readType)
       {
                    struct json_object *pstObj = NULL;
	            char *path = "/mnt/internal_storage/share/rw/main_program.json";
                    if (FROM_FILE == readType)
	           {
		            pstObj = json_object_from_file(path);
	           }
       }`

**Comment by hawicz** [comment]
Can you get a stack backtrace for where it's failing?  
What version of json-c are you using?
Is there anything unusual about the contents of main_program.json?

**Comment by hawicz** [comment]
json_object_from_file() works fine in our tests (e.g. https://github.com/json-c/json-c/blob/8be2ffd/tests/test_util_file.c#L288) so I'm going to assume this is some user error that you were able to solve yourself.  Closing.

**Comment by amresh0591** [comment]
if i am trying to call 2 times json_object_from_file(path) in the same power cycle getting segmentation fault

**Comment by hawicz** [comment]
@amresh0591, please don't hijack closed issues.  If you're having trouble with your code you can ask over at https://groups.google.com/u/0/g/json-c
