### ISSUE TITLE
Need a comparison with other JSON libraries in C

### ISSUE THREAD

**Issue by eyalroz** [json-c/json-c#730]
There are several C libraries for JSON parsing which are relatively or very popular, even here on GitHub (e.g. cJSON, oj). It would help if you could post a comparison of the foci, strengths and weaknesses of these other libraries vis-a-vis json-c. It could be a Wiki page or a README section.

**Comment by hawicz** [comment]
Do you know of a good comparison?  The only one I've seen that looks reasonably comprehensive is https://github.com/miloyip/nativejson-benchmark, but it has measurements for a quite old version of json-c (0.12.1, 5+ years old now) and I have no idea how up-to-date any of the other libraries it tested are.

**Comment by eyalroz** [comment]
@hawicz : If I had a specific comparison in mind, I'd link to it here. I'm just saying that potential users of the library would benefit from it.

It doesn't need to be super-comprehensive to be useful: Just a qualitative description, in text or table form, of key strengths and weaknesses of your library _as you see them_ relative to other JSON libraries would already be a great improvement.  You could also build that benchmark package and post your score...

But it wouldn't be a bad idea to contact the author of that repository and ask them to re-run everything with newer versions of the libraries.

**Comment by eyalroz** [comment]
You may also want to discuss this with [Prof. Daniel Lemire](https://github.com/lemire), I know he's pretty interested in these issues.

**Comment by hawicz** [comment]
I have neither the desire nor the time to put together any kind of comparison like this, not even just a benchmark.  If anyone else want to do so, I'll be happy to post some links in json-c docs, but until then I'm closing this ticket.
