### ISSUE TITLE
Official release? 1.0?

### ISSUE THREAD

**Issue by rubyFeedback** [json-c/json-c#733]
Hello.

Going to:

https://github.com/json-c/json-c/releases

One does not see any releases.

Would it be possible to add an official release e. g. 1.0 or something?

This is not necessarily strictly needed, because we can just use git
checkout, but I'd like to have a "formalized" release that can be
quickly "wget" downloaded, if possible.

Right now I use json-c-0.15-20200726.tar.xz which is a bit outdated
so I will use a current git checkout - but it would be nice if some
officially "stable" json-c could be released. I needed it indirectly
for libsoup and appstream-glib, to then compile gimp from source -
hope I could explain my use case a little. Thanks for reading!

**Comment by ploxiln** [comment]
fwiw the official releases are here: https://s3.amazonaws.com/json-c_releases/releases/index.html
and the tags reflect that: https://github.com/json-c/json-c/tags

**Comment by hawicz** [comment]
Yeah, we're not using github's releases feature.  That said, it _has_ been some time since the previous release, so creating a new one sounds like a good idea.  I'll try to get one going, probably next week some time.

**Comment by besser82** [comment]
> Yeah, we're not using github's releases feature. That said, it _has_ been some time since the previous release, so creating a new one sounds like a good idea. I'll try to get one going, probably next week some time.

A new release would be really nice…

**Comment by hawicz** [comment]
Release 0.16 is out: https://groups.google.com/g/json-c/c/a2h1MG5LHec
