### ISSUE TITLE
json_object.c:308: json_object_put: Assertion `jso->_ref_count > 0' failed

### ISSUE THREAD

**Issue by elgerg** [json-c/json-c#736]
**Describe the bug**
I get json_object.c:308: json_object_put: Assertion `jso->_ref_count > 0' failed 
when in a loop

Error here in 3rd loop:
			printf("Put tile holder\n");
			json_object_put(tile_holder);
			printf("Put object holder\n");
			json_object_put(object_holder);

**Steps To Reproduce**

void loadTiles(lv_obj_t * parent)
{
	struct json_object *json_tile_data, *tile_array, *tile_array_obj, *tile_array_obj_name;
	int arraylen, i;
	int objectID = 0;

	static const char filename[] = "./tiles.json";
	json_tile_data = json_object_from_file(filename);
	tile_array = json_object_object_get(json_tile_data, "Tiles");

	// medi_array is an array of objects
	arraylen = json_object_array_length(tile_array);

	for (i = 0; i < arraylen; i++) {
		// get the i-th object in tile_array
		tile_array_obj = json_object_array_get_idx(tile_array, i);
		// get the name attribute in the i-th object
		tile_array_obj_name = json_object_object_get(tile_array_obj, "TileTitle");
		// print out the name attribute
		printf("TileTitle=%s\n", json_object_get_string(tile_array_obj_name));

		int x = 8;
		int y = 5;

		y = y + (230 * (i/3));
		printf("LocationY=%i\n", y);

		x = x + (338 * (i%3));
		printf("LocationX=%i\n", x);

		//create tile (page)
		lv_obj_t * page = createPage(parent, x, y, json_object_get_string(tile_array_obj_name));
		//8.1 to fix
		//lv_obj_set_drag_parent(page, true);

		//handle the object array
		struct json_object *object_array, *object_holder, *tile_holder;
		object_array = json_object_object_get(tile_array_obj, "Objects");

		int objectarraylen, inneri;
		objectarraylen = json_object_array_length(object_array);

		for (inneri = 0; inneri < objectarraylen; inneri++)
		{

			strcpy(roomItems[objectID].TileName, json_object_get_string(tile_array_obj_name));

			object_holder = json_object_array_get_idx(object_array, inneri);
			tile_holder = json_object_object_get(object_holder, "Name");
			printf("Object_Name=%s\n", json_object_get_string(tile_holder));
			//RoomItem.ObjectName = json_object_get_string(tile_holder);

			char* value = json_object_get_string(tile_holder);
			strcpy(roomItems[objectID].ObjectName, value);

			tile_holder = json_object_object_get(object_holder, "Type");
			printf("Object_Type=%s\n", json_object_get_string(tile_holder));
			value = json_object_get_string(tile_holder);
			strcpy(roomItems[objectID].ObjectType, value);
			//RoomItem.ObjectType = json_object_get_string(tile_holder);

			tile_holder = json_object_object_get(object_holder, "Topic");
			printf("Object_Topic=%s\n", json_object_get_string(tile_holder));
			value = json_object_get_string(tile_holder);
			strcpy(roomItems[objectID].ObjectTopic, value);
			//RoomItem.ObjectTopic = json_object_get_string(tile_holder);

		    struct objReturnVal retVal;
		    if(strcmp(roomItems[objectID].ObjectType, "Dimmer") == 0)
		    {
				retVal = createSlider(page, roomItems[objectID].ObjectName, startPos+(inc*inneri));
				lv_obj_add_event_cb(retVal.obj, generic_event_slider_cb, LV_EVENT_VALUE_CHANGED, NULL);   /*Assign an event callback*/
				roomItems[objectID].LVObject = retVal.obj;
				roomItems[objectID].LVLabelObject = retVal.label;
		    }
		    else if(strcmp(roomItems[objectID].ObjectType, "Button") == 0)
			{
				retVal = createButton(page, roomItems[objectID].ObjectName, startPos+((inc+10)*inneri)-20);
				lv_obj_add_event_cb(retVal.obj, generic_event_button_cb, LV_EVENT_VALUE_CHANGED, NULL);   /*Assign an event callback*/
				roomItems[objectID].LVObject = retVal.obj;
				roomItems[objectID].LVLabelObject = retVal.label;
			}
		    else if(strcmp(roomItems[objectID].ObjectType, "Switch") == 0)
			{
				retVal = createSwitch(page, roomItems[objectID].ObjectName, startPos+((inc+10)*inneri)-20);
				lv_obj_add_event_cb(retVal.obj, generic_event_switch_cb, LV_EVENT_VALUE_CHANGED, NULL);   /*Assign an event callback*/
				roomItems[objectID].LVObject = retVal.obj;
				roomItems[objectID].LVLabelObject = retVal.label;
			}

			//memcpy(roomItems, &RoomItem, sizeof RoomItem);
			//roomItems[objectID] = RoomItem;

			printf("Put tile holder\n");
			json_object_put(tile_holder);
			printf("Put object holder\n");
			json_object_put(object_holder);

			objectID++;

		}

		printf("Put object array\n");
		json_object_put(object_array);

	}

	printf("Put tile_array_obj_name\n");
	json_object_put(tile_array_obj_name);
	printf("Put tile_array_obj\n");
	json_object_put(tile_array_obj);
	printf("Put tile_array\n");
	json_object_put(tile_array);
	printf("Put json_tile_data\n");
	json_object_put(json_tile_data);

}

**Version and Platform**
- json-c version: Not sure, whatever is installable via apt-get on raspberry pi
- OS: Debian buster Raspberry P 400 (ARM)
- Custom cmake/build flags, if any:
#
# Makefile
# WARNING: relies on invocation setting current working directory to Makefile location
# This is done in .vscode/task.json
#
PROJECT 			?= lvgl-sdl
MAKEFLAGS 			:= -j $(shell nproc)
SRC_EXT      		:= c
OBJ_EXT				:= o
CC 					?= gcc

SRC_DIR				:= ./
WORKING_DIR			:= ./build
BUILD_DIR			:= $(WORKING_DIR)/obj
BIN_DIR				:= $(WORKING_DIR)/bin
UI_DIR 				:= ui

LIBS = -lmosquitto -ljson-c

WARNINGS 			:= -Wall -Wextra \
						-Wshadow -Wundef -Wmaybe-uninitialized -Wmissing-prototypes -Wno-discarded-qualifiers \
						-Wno-unused-function -Wno-error=strict-prototypes -Wpointer-arith -fno-strict-aliasing -Wno-error=cpp -Wuninitialized \
						-Wno-unused-parameter -Wno-missing-field-initializers -Wno-format-nonliteral -Wno-cast-qual -Wunreachable-code -Wno-switch-default  \
					  	-Wreturn-type -Wmultichar -Wformat-security -Wno-ignored-qualifiers -Wno-error=pedantic -Wno-sign-compare -Wno-error=missing-prototypes -Wdouble-promotion -Wclobbered -Wdeprecated  \
						-Wempty-body -Wshift-negative-value -Wstack-usage=2048 \
            			-Wtype-limits -Wsizeof-pointer-memaccess -Wpointer-arith -fcommon

CFLAGS 				:= -O0 -g0 $(WARNINGS)

# Add simulator define to allow modification of source
DEFINES				:= -D SIMULATOR=1 -D LV_BUILD_TEST=0

# Include simulator inc folder first so lv_conf.h from custom UI can be used instead
INC 				:= -I./ui/simulator/inc/ -I./ -I./lvgl/
LDLIBS	 			:= -lSDL2 -lm $(LIBS)
BIN 				:= $(BIN_DIR)/demo

COMPILE				= $(CC) $(CFLAGS) $(INC) $(DEFINES)

# Automatically include all source files
SRCS 				:= $(shell find -L $(SRC_DIR) -type f,l -name '*.c' -not -path '*/\.*')
OBJECTS    			:= $(patsubst $(SRC_DIR)%,$(BUILD_DIR)/%,$(SRCS:.$(SRC_EXT)=.$(OBJ_EXT)))

all: default

$(BUILD_DIR)/%.$(OBJ_EXT): $(SRC_DIR)/%.$(SRC_EXT)
	@echo 'Building project file: $<'
	@mkdir -p $(dir $@)
	@$(COMPILE) -c -o "$@" "$<"

default: $(OBJECTS)
	@mkdir -p $(BIN_DIR)
	$(CC) -o $(BIN) $(OBJECTS) $(LDFLAGS) ${LDLIBS}

clean:
	rm -rf $(WORKING_DIR)

install: ${BIN}
	install -d ${DESTDIR}/usr/lib/${PROJECT}/bin
	install $< ${DESTDIR}/usr/lib/${PROJECT}/bin/

**Comment by elgerg** [comment]
output from terminal

Load Tiles
TileTitle=Lounge
LocationY=5
LocationX=8
Object_Name=Main
Object_Type=Dimmer
Object_Topic=LoungeMainDimmer
Put tile holder
Put object holder
Object_Name=Lamp 1
Object_Type=Dimmer
Object_Topic=LoungeLamp1
Put tile holder
Put object holder
Object_Name=Lamp 2
Object_Type=Dimmer
Object_Topic=LoungeLamp2
Put tile holder
Put object holder
demo: ./json_object.c:308: json_object_put: Assertion `jso->_ref_count > 0' failed.

Content from json fie:
{
	"Tiles": [
		{
			"TileTitle": "Lounge",
			"Objects": [
				{
					"Name": "Main",
					"Type": "Dimmer",
					"Topic": "LoungeMainDimmer"
				},
				{
					"Name": "Lamp 1",
					"Type": "Dimmer",
					"Topic": "LoungeLamp1"
				},
				{
					"Name": "Lamp 2",
					"Type": "Dimmer",
					"Topic": "LoungeLamp2"
				},
				{
					"Name": "Book 1",
					"Type": "Dimmer",
					"Topic": "BookCase1"
				},
				{
					"Name": "Book 2",
					"Type": "Dimmer",
					"Topic": "BookCase2"
				}
			]
		},
		{
			"TileTitle": "Macros",
			"Objects": [
				{
					"Name": "All Lights Off",
					"Type": "Button",
					"Topic": "Macros/AllLights/Off"
				},
				{
					"Name": "Mood Lighting On",
					"Type": "Button",
					"Topic": "Macros/MoodLighting/On"
				}
			]
		},
		{
			"TileTitle": "Dining",
			"Objects": [
				{
					"Name": "Main",
					"Type": "Dimmer",
					"Topic": "DiningDimmer"
				},
				{
					"Name": "Kitchen",
					"Type": "Dimmer",
					"Topic": "KitchenDimmer"
				},
				{
					"Name": "Audio",
					"Type": "Switch",
					"Topic": "KitchenSpeakers"
				}
			]
		},
		{
			"TileTitle": "Master",
			"Objects": [
				{
					"Name": "Main",
					"Type": "Dimmer",
					"Topic": "MasterMain"
				},
				{
					"Name": "Bed",
					"Type": "Dimmer",
					"Topic": "BedLight"
				},
				{
					"Name": "EnSuite",
					"Type": "Dimmer",
					"Topic": "EnSuiteLight"
				}
			]
		},
		{
			"TileTitle": "Spare Room",
			"Objects": [
				{
					"Name": "Main",
					"Type": "Dimmer",
					"Topic": "SpareRoomLight"
				},
				{
					"Name": "Mirror",
					"Type": "Dimmer",
					"Topic": "SpareRoomMirror"
				}
			]
		},
		{
			"TileTitle": "Jacobs Room",
			"Objects": [
				{
					"Name": "Main",
					"Type": "Dimmer",
					"Topic": "JacobsBedroomLight"
				}
			]
		}
	]
}

**Comment by elgerg** [comment]
After further testing I copied over the source that works fine on my Pi Zero running buster.
It builds fine but once executed i get the same error:

2021-12-16 23:57:02::: registration_response {"type":"rangeUpdate","rangeData":{"rnglounge":0,"rnglamp1":4.5,"rnglamp2":4.5,"rnglamp3":4.5,"rngdining":0,"rngwifirelay":1023,"rngjacob":0,"rngjacobled1":0,"rngjacobled2":0,"rngjacobled3":0,"rngsr":0,"rngsremirror":0,"rngmaster":0,"rngmasterlamp1":0,"rngensuite":0,"inisinhouse":0,"inallowHomeControl":0}}
2021-12-16 23:57:02::: WiFiRelayValue 1023
2021-12-16 23:57:02::: rnglounge 0
2021-12-16 23:57:02::: rnglamp1 4
2021-12-16 23:57:02::: Range set, lets set it to 30 ! 
2021-12-16 23:57:02::: rnglamp2 4
2021-12-16 23:57:02::: Range set, lets set it to 30 ! 
2021-12-16 23:57:02::: rnglamp3 4
2021-12-16 23:57:02::: Range set, lets set it to 30 ! 
2021-12-16 23:57:02::: rngdining 0
2021-12-16 23:57:02::: rngsr 0
2021-12-16 23:57:02::: rngsremirror 0
2021-12-16 23:57:02::: rngjacob 0
HAControlPanel.bin: ./json_object.c:308: json_object_put: Assertion `jso->_ref_count > 0' failed.

Has something changed between buster and bullseye that is causing this to fail?

'void handleRegistrationItem(lv_obj_t * range, lv_obj_t * label, struct json_object *rangeData_struct, char* rangeName)
{

	struct json_object *payload;
	json_object_object_get_ex(rangeData_struct, rangeName, &payload);
    double rangeValue = json_object_get_double(payload);
	if(debugLevel >= 1)
	{
		printDateTime();
	    printf("%s %d\n", rangeName, json_object_get_int(payload));
	}

    if(rangeValue > 0)
    {
    	setSlider(range, label, rangeValue);
    }

	json_object_put(payload);
}
'

**Comment by hawicz** [comment]
Thank you for the detailed error report!

The problem in that code is that you're calling json_object_put far too often.  In particular, you should _not_ call it on any object you get back from json_object_object_get() or json_object_array_get_idx(), etc... because those function do not change the reference count.
e.g. see the docs [json_object_object_get docs](https://json-c.github.io/json-c/json-c-current-release/doc/html/json__object_8h.html#a1a097805abb53b4c8a60d573730a8939) which point out "No reference counts will be changed."

I haven't fully analyzed your code, but most likely the **only** thing you need to free with json_object_put() is the very first json_tile_data object allocated by json_object_from_file() (which also automatically frees any objects connected to that tree)

As for why the behavior you're seeing is different between buster and bullseye, whether or not you get the refcount assertion upon using previously free'd memory is going to depend a lot on how the malloc implementation works, and how things happen to be arranged in memory.  If you're curious you could probably track down exactly why, with a deep dive into malloc internals and paying close attention to when particular pointer addresses are malloc'd, free'd and re-malloc'd, but it's probably more trouble than it's worth.

**Comment by fabioz23** [comment]
Hi all,

i've the same problem with a little different use case: i need to parse and search some fields in a json.
I've done some (different) test obtaining the same problem, memory leak.

My last (desperate) test is this below trying to re-parse a json string every for-loop cycle :

```
for (int k = 0; k < n_fields; k++) {
            json_object *root, *tmp;
            root = json_tokener_parse_verbose(res, &jerr);

            if (jerr != json_tokener_success) {
                fprintf(stderr, "ERROR: Failed to parse json string");
                json_object_put(root);
                return 1;
            }

            tmp = json_object_object_get(root, filterres[k]);
            enum json_type o_type = json_object_get_type(tmp);

            if (o_type == json_type_array) {
                int idx = 0;
                idx = atoi(filterres[k + 1] + 1);
                if (debug) printf("Get array idx = %d\n", idx);

                size_t nr = json_object_array_length(tmp);
                if (idx < nr) {
                    memset(res, 0, BUFSIZ);
                    strcat(res, json_object_to_json_string(json_object_array_get_idx(tmp, idx)));

                    if (debug) printf("JSON %d: [%d] %s\n", k, idx, json_object_to_json_string(tmp));
                    k++;
                    continue;
                }
            } else if (o_type == json_type_object) {
                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            } else if (o_type == json_type_boolean) {
                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            } else if (o_type == json_type_int) {
                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            } else if (o_type == json_type_string) {

                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            } else if (o_type == json_type_double) {

                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            } else if (o_type == json_type_null) {
                // error
                if (debug) printf("JSON %d: %s\n", k, json_object_to_json_string(tmp));
            }

            memset(res, 0, BUFSIZ);
            strcat(res, json_object_to_json_string(tmp));

            // json_object_put(tmp);
            json_object_put(root);

        }
```

in all test my valgrind says:


![Schermata 2022-02-15 alle 15 17 59](https://user-images.githubusercontent.com/729310/154080055-32eef94e-1c3a-4cb9-bb72-48549e51d5da.jpg)

I've followed doc and example and i can't find how to solve this memory leak.

**Comment by hawicz** [comment]
The "continue" inside the json_type_array case is the problem.  At that point root is still valid and un-freed, but you're looping back to the beginning and calling root=json_tokener_parse_verbose(...) w/o freeing it.  Are you intending to abandon abandon fetching fields from your top-level object at that point?  If yes, try adding a json_object_put(root) there.  If not, you might need to restructure your code into a recursive function, but then the apparently flat filterres array doesn't seem like it meshes.

**Comment by fabioz23** [comment]
@hawicz thanks.

adding `json_object_put(root);` before `continue;` makes no mem leakage.

In my 1st version instead of re-parsing from string at each loop i was looping over a `json_object *tmp` but in that case trying to free resources at the end of each loop caused empty object ad next loop run.

I think that the same problem will be present on recursive calls if i pass a `json_object *`, the deepest will be able to free its resources (but are nested on the root object), the (deepest - 1) run will thrown an error on freeing resources.
May i free resources only at the end of top level call?

@hawicz What do you suggest for a more efficient json parsing and filtering (i've a char[] with the field to search in the tree).

Thanks againg.

**Comment by hawicz** [comment]
You only need to free the top level object tree allocated by json_tokener_parse_verbose().  You probably want a structure vaguely like:

    your_top_level_func(...) {
        root = json_tokener_parse_verbose(res, &jerr);
        your_recursive_function(root, fllterres, other, args, etc...);
        json_object_put(root);
    }

I don't know exactly what's you are trying to do with your "filtering" and your use of filterres, so it's a bit hard to comment on a good approach.

In any case, I don't see any problem with json-c itself, so I'm going to close this issue.  To continue a more general discussion please use the forums at https://groups.google.com/g/json-c
