### ISSUE TITLE
General question - Is there an SLA for handling newly detected security issues?

### ISSUE THREAD

**Issue by adarpp** [json-c/json-c#738]

**Comment by adarpp** [comment]
I consider to start using json-c but am asked to answer the question of how fast will security breaches will be fixed in case they are discovered.

Thanks a lot!

**Comment by hawicz** [comment]
Sorry, formal SLAs are for $DAYJOB, and json-c is currently a solely volunteer project.  Also, "security breach" implies there's some system that's been breached, which would involve how json-c is packaged and deployed on your OS, what version is used, and ultimately how it is being used in applications, all of which are beyond the control of the json-c project.
The most I can offer is:
* If a well written and non-conflicting patch is provided (i.e. it doesn't break API usage nor change behavior in egregiously incompatible ways) then I'll merge it to master within about a week.
* If you suspect there is a bug that has a security impact, I'll be happy to work with you to confirm that and suggest approaches for fixing it.  However, I can't guarantee that I, nor anyone else that might have contributed to json-c, will have time at any particular moment to actively write code to implement any such fix.
