### ISSUE TITLE
json_object_put: Assertion `jso->_ref_count > 0' failed

### ISSUE THREAD

**Issue by CaledoniaProject** [json-c/json-c#747]
**Describe the bug**
Trying to call put on all the json_object I've created, but fails with assertion error

**Steps To Reproduce**

According to the document I should call put on all objects, but it crashes:

```
struct json_object *obj_root, *obj_status;
obj_root = json_tokener_parse(input);
if (obj_root == NULL)
{
	return NULL;
}

obj_status = json_object_object_get(obj_root, "Status");
if (obj_status == NULL)
{
	return NULL;
}

json_object_put(obj_status);
json_object_put(obj_root);     // crashes here
```

**Version and Platform**
- json-c version: 0.13.1
- OS: Ubuntu 20.04

**Comment by hawicz** [comment]
You're freeing obj_status twice, first explicitly, then again as part of freeing obj_root.  [json_object_object_get()](https://json-c.github.io/json-c/json-c-0.15/doc/html/json__object_8h.html#a1a097805abb53b4c8a60d573730a8939) does not change reference counts on the object it returns so you must not free that separately from its containing object.
