### ISSUE TITLE
Question: Is there any way to build this with Gnu Make?

### ISSUE THREAD

**Issue by rsbeckerca** [json-c/json-c#756]
CMake does not port to my platform. Is there any way to build using Gnu Make and c99?

Thanks.

**Comment by hawicz** [comment]
What platform are you on that has c99 but not cmake?

If you really can't get cmake to build and run on your system, perhaps you could try building json-c on some other similar system with "make VERBOSE=1", note all the `cc` commands, and manually run those on your system?  (adjusting as needed for different paths, compiler arguments, libraries to link against, etc...)

**Comment by rsbeckerca** [comment]
> What platform are you on that has c99 but not cmake?
> 
> If you really can't get cmake to build and run on your system, perhaps you could try building json-c on some other similar system with "make VERBOSE=1", note all the `cc` commands, and manually run those on your system? (adjusting as needed for different paths, compiler arguments, libraries to link against, etc...)

The platform is HPE NonStop ia64 and x86. CMake depends on gcc, which cannot be ported - not for lack of trying.

**Comment by hawicz** [comment]
oof, sorry to hear that.
Without cmake the hardest part will likely be creating an appropriate config.h (based on cmake/config.h.in).  However, once you do that then actually building a library in _some_ form should be fairly straight forward.  You'd need to do whatever the equivalent of this is for the HPE compiler:

    cc -fPIC -g -I dir/where/configh/exists/ *.c
    cc -fPIC -g  -shared -Wl,-soname,libjson-c.so.5 -o libjson-c.so.5.1.0 *.o -lbsd

**Comment by MarcT512** [comment]
If it helps at all, I used to build on Win32 TDM-GCC as follows.
You could probably do something similar. Remove -m32 for the 64bit platform.

```
rem Compile all .c files into object .o files:
gcc -Wall -Wpedantic -Wextra -Wno-unused-parameter -s -c -m32 arraylist.c debug.c json_c_version.c json_object.c json_object_iterator.c json_tokener.c json_util.c linkhash.c printbuf.c random_seed.c strerror_override.c
@
rem Build .o files into library (archive) .a file:
ar rcs libjson-c.a arraylist.o debug.o json_c_version.o json_object.o json_object_iterator.o json_tokener.o json_util.o linkhash.o printbuf.o random_seed.o strerror_override.o
@
rem Now build .o files into shared library (dll):
gcc -Wall -s -shared -m32 -o libjson-c.dll arraylist.o debug.o json_c_version.o json_object.o json_object_iterator.o json_tokener.o json_util.o linkhash.o printbuf.o random_seed.o strerror_override.o
@
rem Build Shared Library (DLL) without intermediate .o files:
rem gcc -Wall -s -shared -m32 -o libjson-c.dll arraylist.c debug.c json_c_version.c json_object.c json_object_iterator.c json_tokener.c json_util.c linkhash.c printbuf.c random_seed.c strerror_override.c
```

**Comment by rsbeckerca** [comment]
> If it helps at all, I used to build on Win32 TDM-GCC as follows. You could probably do something similar. Remove -m32 for the 64bit platform.
> 
> ```
> rem Compile all .c files into object .o files:
> gcc -Wall -Wpedantic -Wextra -Wno-unused-parameter -s -c -m32 arraylist.c debug.c json_c_version.c json_object.c json_object_iterator.c json_tokener.c json_util.c linkhash.c printbuf.c random_seed.c strerror_override.c
> @
> rem Build .o files into library (archive) .a file:
> ar rcs libjson-c.a arraylist.o debug.o json_c_version.o json_object.o json_object_iterator.o json_tokener.o json_util.o linkhash.o printbuf.o random_seed.o strerror_override.o
> @
> rem Now build .o files into shared library (dll):
> gcc -Wall -s -shared -m32 -o libjson-c.dll arraylist.o debug.o json_c_version.o json_object.o json_object_iterator.o json_tokener.o json_util.o linkhash.o printbuf.o random_seed.o strerror_override.o
> @
> rem Build Shared Library (DLL) without intermediate .o files:
> rem gcc -Wall -s -shared -m32 -o libjson-c.dll arraylist.c debug.c json_c_version.c json_object.c json_object_iterator.c json_tokener.c json_util.c linkhash.c printbuf.c random_seed.c strerror_override.c
> ```

Thanks. That's up next on my porting list. Will advise.

**Comment by hawicz** [comment]
It looks like there's a workable solution here, closing.

**Comment by rsbeckerca** [comment]
I would not call it a sustainable solution, but so be it. Manually configuring and building Open Source projects is awkward.
