### ISSUE TITLE
Some people have trouble with undefined references to arc4random 

### ISSUE THREAD

**Issue by hawicz** [json-c/json-c#766]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/g/json-c

**Describe the bug**
On some systems, json-c uses `arc4random()`, but then the linker fails to find it.
See e.g. messages from @nmartin-cs and @moonburnt at https://github.com/json-c/json-c/issues/692#issuecomment-793057630

**Steps To Reproduce**
```
mkdir build && cd $_
cmake ..
cmake -DCMAKE_INSTALL_PREFIX=/usr .
sudo make install  
```
**Version and Platform**
Arch Linux 5.10.13, glibc 2.33-3, gcc 10.2.0, cmake

**Comment by hawicz** [comment]
@nmartin-cs, @moonburnt, can you please check how the json-c build is pulling in arc4random, and in which library the symbol is defined in on your system?
For the former, does cmake output look like:
```
-- Looking for arc4random
-- Looking for arc4random - not found
-- Looking for bsd/stdlib.h
-- Looking for bsd/stdlib.h - found
-- Looking for arc4random
-- Looking for arc4random - found
```
Or does it find arc4random at the first check?

Is the symbol defined only in a libbsd.so?  i.e. what does `grep -rl arc4random /usr/lib*` return ?

**Comment by hawicz** [comment]
Fyi, steps to reproduce a failure in ctune:

* Launch a VM using a Arch Linux AMI from 2022/05/15 ([ami-093c23d628e71e751](https://console.aws.amazon.com/ec2/v2/home?region=us-west-2#LaunchInstanceWizard:ami=ami-093c23d628e71e751), from http://arch-ami-list.drzee.net/)
* Login, be root
* First time arch linux setup
```
gpg --refresh-keys
pacman-key --init
pacman-key --populate archlinux
pacman-key --refresh-keys
pacman-key --populate
pacman -Syuu
pacman -S git cmake make gcc
pacman -S libbsd
pacman -S ffmpeg curl sdl2 pandoc
```
* ctune build failure:
```
git clone https://github.com/An7ar35/ctune
cd ctune/
rm -rf tmp external build
mkdir buildX
cd buildX
cmake ..
make    # this one works ok
sed -i -e'/HAVE_ARC4RANDOM/d' ../CMakeLists.txt  # i.e. try to enable arc4random
cmake ..
make    # this one fails
```

**Comment by An7ar35** [comment]
@hawicz Thanks for looking into this. Glad it's not my weird build process! Still, you're right on the lack of self-contained build. Something I've been meaning to go back to and sort at some stage.

**Comment by brad0** [comment]
I just came across this bug report Google searching, but just FYI, glibc 2.36 will include arc4random() in stdlib removing the need for linking libbsd.

**Comment by hawicz** [comment]
I don't think there's anything else that needs to be fixed here.  We can open a new issue if someone runs into similar problems in the future.
