### ISSUE TITLE
commits from May 30, 2022 killed my docker build process

### ISSUE THREAD

**Issue by zikkuratti** [json-c/json-c#768]
[ 98%] Building C object apps/CMakeFiles/json_parse.dir/json_parse.c.o
/usr/json-c/apps/json_parse.c: In function 'main':
/usr/json-c/apps/json_parse.c:170:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
  170 |   case 'h': usage(argv[0], 0, NULL);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/usr/json-c/apps/json_parse.c:171:3: note: here
  171 |   default: /* '?' */ usage(argv[0], EXIT_FAILURE, "Unknown arguments");
      |   ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [apps/CMakeFiles/json_parse.dir/build.make:63: apps/CMakeFiles/json_parse.dir/json_parse.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1757: apps/CMakeFiles/json_parse.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by zikkuratti** [comment]
i up again from fork, but just some info 4 u

**Comment by hawicz** [comment]
s/b fixed w/ pr#769
