### ISSUE TITLE
json_parse.c:170:13: error: this statement may fall through

### ISSUE THREAD

**Issue by jcheng2021** [json-c/json-c#770]
/home/ubuntu/json-c/apps/json_parse.c: In function ‘main’:
/home/ubuntu/json-c/apps/json_parse.c:170:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
  170 |   case 'h': usage(argv[0], 0, NULL);
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/home/ubuntu/json-c/apps/json_parse.c:171:3: note: here
  171 |   default: /* '?' */ usage(argv[0], EXIT_FAILURE, "Unknown arguments");
      |   ^~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [apps/CMakeFiles/json_parse.dir/build.make:76: apps/CMakeFiles/json_parse.dir/json_parse.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1698: apps/CMakeFiles/json_parse.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

In case 'h', break is needed to solve this

**Comment by AjayShendkar** [comment]
/usr/src/json-c/apps/json_parse.c: In function 'main':
/usr/src/json-c/apps/json_parse.c:170:13: error: this statement may fall through [-Werror=implicit-fallthrough=]
   case 'h': usage(argv[0], 0, NULL);
             ^~~~~~~~~~~~~~~~~~~~~~~
/usr/src/json-c/apps/json_parse.c:171:3: note: here
   default: /* '?' */ usage(argv[0], EXIT_FAILURE, "Unknown arguments");
   ^~~~~~~
all warnings being treated as errors
make[2]: *** [apps/CMakeFiles/json_parse.dir/build.make:82: apps/CMakeFiles/json_parse.dir/json_parse.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1803: apps/CMakeFiles/json_parse.dir/all] Error 2
make: *** [Makefile:182: all] Error 2

Similar issue observed, c++ fallthrough attribute can be added to solve this.

**Comment by hawicz** [comment]
dup of #768
