### ISSUE TITLE
The function add_compile_options was added to CMake version 2.8.12 and later but your minimum is 2.8 which will not work

### ISSUE THREAD

**Issue by nicebub** [json-c/json-c#774]
**Describe the bug**
Will not build with CMAKE prior to version 2.8.12

**Steps To Reproduce**
Try to build with version CMAKE < 2.8.12

**Version and Platform**
- json-c version: [e.g. json-c-0.15, or a specific commit hash]
- OS: [e.g. Ubuntu 18.04.6, ]
- cmake version 2.8.4

**Comment by hawicz** [comment]
It's probably past time to bump the minimum version.  Do you know of some system still stuck on cmake<2.8.12

**Comment by nicebub** [comment]
unfortunately.

**Comment by hawicz** [comment]
unfortunately past time?  or unfortunately you know of some system that can't use a newer cmake?  If the latter, why not?

**Comment by nicebub** [comment]
yes and yes. I only have control of specific tools and libraries.
