### ISSUE TITLE
ghpages update was not published for json-c-0.16

### ISSUE THREAD

**Issue by tony--** [json-c/json-c#786]
http://json-c.github.io/json-c/ still lists json-c-0.15 as the current release, but json-c-0.16 has been released.

The doc update for 0.16 was incomplete and not published.

Compare the ghpages/index.html update for 0.16 with the 0.15 update:
[0.16](https://github.com/json-c/json-c/commit/294efecc10aaf3a91e99c43820fa298b95fac2d1)
[0.15](https://github.com/json-c/json-c/commit/9af901b5b5a78032f04249f5cad02e48c15147a0)

Note that the incomplete changes made for 0.16 have not been published:
http://json-c.github.io/json-c/

**Comment by hawicz** [comment]
I'm not sure why it wasn't published before.  I updated that last reference to 0.15, and then told github to re-run the deployment workflow, and now it looks better.
