### ISSUE TITLE
json_object_object_foreach not ISO-C compliant

### ISSUE THREAD

**Issue by mdorier** [json-c/json-c#791]
**Describe the bug**

Using `json_object_object_foreach` makes the compiler print a warning (which may be treated as an error depending on the flags used):

```
include/json-c/json_object.h:488:14: warning: ISO C forbids braced-groups within expressions [-Wpedantic]
  488 |              ({                                                                  \
      |              ^
note: in expansion of macro ‘json_object_object_foreach’
  493 |     json_object_object_foreach(vms, vm_name, vm_config) {
```

The problem points to this line:
https://github.com/json-c/json-c/blob/master/json_object.h#L488

**Version and Platform**
- json-c version: 0.16
- OS: Ubuntu 22.04
- compiler: gcc 11.2.0
- Custom cmake/build flags, if any: `-Wextra -Wall -Wpedantic`

**Comment by hawicz** [comment]
If you're doing to add `-Wpedantic`, then you should probably be using `-ansi` too, in which case the check for `__STRICT_ANSI__` in json_object.h will kick in and it'll use the other definition of that macro.
