### ISSUE TITLE
#error You do not have strncasecmp on your system.

### ISSUE THREAD

**Issue by Haidar0096** [json-c/json-c#801]
- I cloned the repository
- ran cmake command to generate the config files
- added the source and header files to my project
 - linked against them directly like this in `CMakeLists.txt`;
```
 # json-c
include_directories(Dependencies/json-c/include)
file(GLOB JSON_C_SOURCES Dependencies/json-c/Src/*.c)
add_library(json-c STATIC ${JSON_C_SOURCES})
target_link_libraries(demo json-c)
```
The problem is that when I try to run I get 
```
You do not have strncasecmp on your system.
```
It is coming from `json_tokener.c` from this code:
```
#if !HAVE_STRNCASECMP && defined(_MSC_VER)
/* MSC has the version as _strnicmp */
#define strncasecmp _strnicmp
#elif !HAVE_STRNCASECMP
#error You do not have strncasecmp on your system.
#endif /* HAVE_STRNCASECMP */
```

I am running on windows 11 and using clion to compile the project (so I guess it is using gcc), If I change 
`#error You do not have strncasecmp on your system.` into `#define strncasecmp _strnicmp` it works, but is this the right approach? what should I do?

**Comment by hawicz** [comment]
I recommend configuring CLion to use the visual studio compiler: https://www.jetbrains.com/help/clion/quick-tutorial-on-configuring-clion-on-windows.html#MSVC
