### ISSUE TITLE
Feature request json_object_new_uint() 

### ISSUE THREAD

**Issue by olignyf** [json-c/json-c#809]
**Problem**
We cannot print `unsigned int` readily. Current workaround is to print as string or do gymnastics to convert to int64 while preserving the positive sign of values larger than INT32_MAX.

**Feature request**
Add new json_object_new_uint() that takes unsigned int (32 bit) input.

I don't think we need uint64() because Javascript would have trouble with the precision in the larger ranges. I usually print them as strings. 

Note that I posted this question on the user forum before creating this ticket.
https://groups.google.com/u/1/g/json-c/c/T_Eg0SBZNGo

Thanks

**Comment by hawicz** [comment]
Use `json_object_new_uint64()`
Since the values are stored as 64 bit internally anyway there's really no value in adding an extra 32-bit function.
