### ISSUE TITLE
dependence on execution character set

### ISSUE THREAD

**Issue by Humm42** [json-c/json-c#811]
json-c depends on the execution character set being similar to ASCII. The parser compares bytes of the JSON to character constants (`'{'`), which are not guaranteed to be equal to their Unicode code point. To reproduce, have a little fun with `-fexec-charset`.

To fix, the character constants could be replaced by either the integer values (`0x7b /* { */`) or, in a few decades when C23 might be old enough to be used, by UTF-8 character constants (`u8'{'`, which is of type `unsigned char`, aka. `char8_t`).

**Comment by hawicz** [comment]
No, I think we'll skip that.  Build your own code with whatever charset you want, but json-c will stick with UTF-8

**Comment by michellemartni** [comment]
Unsubscribe pleaseMichelle Martin On Mar 21, 2023, at 6:56 PM, Eric Hawicz ***@***.***> wrote:﻿
No, I think we'll skip that.  Build your own code with whatever charset you want, but json-c will stick with UTF-8

**Comment by Humm42** [comment]
It’s not like you control the build. I’m sad about your resolution. I think it should be documented that json-c requires the execution character set to include ASCII.
