### ISSUE TITLE
Hi I need to generate libjson-c.so.3 and libjson-c.so.3.0.1, please help with steps

### ISSUE THREAD

**Issue by georgethomas08** [json-c/json-c#816]
I have a gateway which have have yocto linux preloaded and rrot folder are read only, on that shared library is libjson-c.so.3 and libjson-c.so.3.0.1, I wanted to install this on my system for cross compile

Please help me to solve this

**Comment by hawicz** [comment]
This is definitely not a bug, and sounds like not even anything json-c specific.  Instead, I expect you need to setup a yocto development environment.  I know nothing about how to do that but I found some docs that might be helpful:
https://docs.yoctoproject.org/sdk-manual/index.html

Note that libjson-c.so.3 is *really* old.  If building json-c from source you'll need to grab some variant of the 0.13 branch (e.g. https://github.com/json-c/json-c/tree/json-c-0.13.1-20180305)
