### ISSUE TITLE
build with intel 2023 fails on vasprintf

### ISSUE THREAD

**Issue by VictorEijkhout** [json-c/json-c#819]
If I read cppreference correctly

https://en.cppreference.com/w/c/experimental/dynamic/asprintf

the routine `vasprintf` is a GNU extensions and therefore limits built to GNU compilers. Intel 19 actually builds this, but intel 23 which is llmv based, doesn't.

```
/opt/intel/oneapi/compiler/2023.1.0/linux/bin/icx -Djson_c_EXPORTS -I/admin/build/admin/rpms/frontera/BUILD/jsonc-git -I/admin/build/admin/rpms/frontera/SOURCES/build-git-clx-intel23 -g -fPIC   -D JSON_C_DLL -D_REENTRANT -MD -MT CMakeFiles/json-c.dir/json_visit.c.o -MF CMakeFiles/json-c.dir/json_visit.c.o.d -o CMakeFiles/json-c.dir/json_visit.c.o -c /admin/build/admin/rpms/frontera/BUILD/jsonc-git/json_visit.c
/admin/build/admin/rpms/frontera/BUILD/jsonc-git/printbuf.c:163:15: error: call to undeclared function 'vasprintf'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                if ((size = vasprintf(&t, msg, ap)) < 0)
                            ^
```

**Comment by hawicz** [comment]
Does it work if you stick in a `#define vasprintf __libcpp_vasprintf` somewhere?

**Comment by hawicz** [comment]
Even if the compiler doesn't have vasprintf, json-c provides vasprintf_compat.h so the build should work.  I don't have an environment like this to test in, so I couldn't tell you why it's not working, but I suggest trying to figure out why the detection of vasprintf (and the setting or clearing of HAVE_VASPRINTF) doesn't work when you run cmake.
