### ISSUE TITLE
ISO C forbids in 

### ISSUE THREAD

**Issue by Nonesence999** [json-c/json-c#820]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/g/json-c

**Describe the bug**

In function '_json_c_visit':
library/json-c/json_object.h:488:14: error: ISO C forbids braced-groups within expressions [-Werror=pedantic]
  488 |              ({                                                                  \
In function 'json_object_copy_serializer_data':
library/json-c/json_object.c:1637:29: error: ISO C forbids conversion of function pointer to object pointer type [-Werror=pedantic]
 1637 |                     "%p\n", (void *)dst->_to_json_string);

**Steps To Reproduce**
include json-c into a c project whit 
```cmake
set(CMAKE_C_STANDARD 23)
add_compile_options(-Wall -Wextra -Wpedantic -O3)
add_subdirectory(library/json-c)
target_link_libraries(PROJECTNAME PRIVATE json-c)
```

**Version and Platform**
- json-c version: json-c-0.14
- OS: Windows 11
- Custom cmake/build flags, add_compile_options(-Wall -Wextra -Wpedantic -O3)

**Comment by hawicz** [comment]
We haven't normally targeted building with `-Wpedantic`, but if you have some generally non-intrusive patches I'll be happy to consider merging them.

For that first error, perhaps adding `-ansi` (so `__STRICT_ANSI__` is defined) will avoid the code that it's complaining about.

**Comment by hawicz** [comment]
Apparently there's no easy way to print a function pointer: https://stackoverflow.com/questions/2741683/how-to-format-a-function-pointer
If you really want to build with -Wpedantic, feel free to write some kind of print_a_funcptr() function and submit a PR, but I think it's mostly needless cruft.
