### ISSUE TITLE
Any release planing for 0.17?

### ISSUE THREAD

**Issue by GitMensch** [json-c/json-c#821]
Since 0.16 in April 20122 there were ~42commits (with possibly 10 only merge commits). I just wanted to recheck if there's any plan on releasing a new version / a list of things that should possibly done before.

**Comment by hawicz** [comment]
Opening github issues really isn't the right way to ask questions like this, use https://groups.google.com/forum/#!forum/json-c instead.
However, Re: 0.17, see https://github.com/json-c/json-c/wiki/Notes-for-v0.17-release
Mostly, I'm aiming to make one more pass through the PRs (including #702 which I have a pile of changes for) and issues, then create the release.  Maybe in the next week or two.

**Comment by hawicz** [comment]
Fyi, json-c-0.17 is released: https://groups.google.com/g/json-c/c/2y9WUcsY9ag
