### ISSUE TITLE
Symbol not found during linking stage of libjson-c.so

### ISSUE THREAD

**Issue by kostadinsh** [json-c/json-c#823]
**Describe the bug**
Warning about the json_number_char symbol not being found during linking stage of libjson-c.so
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/json-c.dir/link.txt --verbose=1
/usr/bin/cc -fPIC  -ffunction-sections -fdata-sections -Werror -Wall -Wcast-qual -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter -Wstrict-prototypes -g -fuse-ld=mold -Wl,-Bsymbolic-functions -Wl,--version-script,/home/kshishmanov/json-c/json-c.sym -shared -Wl,-soname,libjson-c.so.5 -o libjson-c.so.5.2.0 "CMakeFiles/json-c.dir/arraylist.c.o" "CMakeFiles/json-c.dir/debug.c.o" "CMakeFiles/json-c.dir/json_c_version.c.o" "CMakeFiles/json-c.dir/json_object.c.o" "CMakeFiles/json-c.dir/json_object_iterator.c.o" "CMakeFiles/json-c.dir/json_tokener.c.o" "CMakeFiles/json-c.dir/json_util.c.o" "CMakeFiles/json-c.dir/json_visit.c.o" "CMakeFiles/json-c.dir/linkhash.c.o" "CMakeFiles/json-c.dir/printbuf.c.o" "CMakeFiles/json-c.dir/random_seed.c.o" "CMakeFiles/json-c.dir/strerror_override.c.o" "CMakeFiles/json-c.dir/json_pointer.c.o" "CMakeFiles/json-c.dir/json_patch.c.o"  -lm 
mold: warning: /home/kshishmanov/json-c/json-c.sym: cannot assign version `JSONC_0.14` to symbol `json_number_chars`: symbol not found
```

**Steps To Reproduce**
1. `git clone https://github.com/json-c/json-c`
2. `mkdir json-c/build && cd json-c/build`
3. if using GNU's ld linker run `export LDFLAGS="-Wl,--no-undefined-version"` or if using a recent enough version of LLVM's lld or the mold linker go to step 4
4. `cmake .. && make`

**Version and Platform**
- json-c version: 87127d31c615a0b2c85336448a35fa8e5cc9324d
- OS: Gentoo Linux
- GCC: gcc (Gentoo Hardened 13.2.0 p3) 13.2.0
- Custom cmake/build flags, if any: LDFLAGS="-Wl,--no-undefined-version" if using GNU's ld linker

**Comment by hawicz** [comment]
Looks like we lost that back in commit f23486a3
