### ISSUE TITLE
Cannot build with clang-cl

### ISSUE THREAD

**Issue by sykhro** [json-c/json-c#829]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/g/json-c

**Describe the bug**
Building with clang-cl currently fails due to CMake not distinguishing it from clang with the GNU-style CLI.
```
clang-cl.exe  /nologo -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -D_UNICODE -IC:\Users\Erin\.conan2\p\b\json-e2cfe01b7c40f\b\src -IC:\Users\Erin\.conan2\p\b\json-e2cfe01b7c40f\b\build\Debug /EHsc /permissive- /Zc:preprocessor /volatile:iso -Wno-unused-command-line-argument -fuse-ld=lld /DWIN32 /D_WINDOWS /W3 -ffunction-sections -fdata-sections -Werror -Wall -Wcast-qual -Wno-error=deprecated-declarations -Wextra -Wwrite-strings -Wno-unused-parameter /Zi /Ob0 /Od /RTC1 -MDd /showIncludes /FoCMakeFiles\json-c.dir\json_util.c.obj /FdCMakeFiles\json-c.dir\json-c.pdb -c -- C:\Users\Erin\.conan2\p\b\json-e2cfe01b7c40f\b\src\json_util.c
clang-cl: error: unknown argument ignored in clang-cl: '-ffunction-sections' [-Werror,-Wunknown-argument]
clang-cl: error: unknown argument ignored in clang-cl: '-fdata-sections' [-Werror,-Wunknown-argument]
```
The proper fix is using [CMAKE_C_COMPILER_FRONTEND_VARIANT](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_COMPILER_FRONTEND_VARIANT.html#cmake-lang-compiler-frontend-variant), but it would require bumping the CMake version to 3.14.

I know about the `DISABLE_WERROR` option, but `clang-cl` needs to be detected as MSVC.

**Steps To Reproduce**
1. Configure CMake with `CMAKE_C_COMPILER` set to `clang-cl`
2. Build

**Version and Platform**
- json-c version: >= 0.16
- OS: Any
- Custom cmake/build flags, if any: None that would be relevant

**Comment by hawicz** [comment]
I don't think bumping up to 3.14 is something we can do just yet.
I found https://discourse.cmake.org/t/how-to-determine-if-clang-or-clang-cl-is-used-on-windows/4129/9 as an example of using `execute_process(COMMAND "${CMAKE_${lang}_COMPILER}" -?)` to figure out what kind of clang is in use, so we could stuff something like that into json-c's CMakeLists.txt

**Comment by hawicz** [comment]
I don't have an environment to test it in, but commit e3464a2 should make this work better.
