### ISSUE TITLE
Null pointer dereference in tokener_parse_ex_fuzzer.cc

### ISSUE THREAD

**Issue by HansolChoe** [json-c/json-c#836]
Hi, I am interested in fuzzing json-c through oss-fuzz.

Therefore, I am running oss-fuzz locally using the latest version of the target fuzzer
(`tokener_parse_ex_fuzzer`) and its build script.

I've noticed an area of improvement in the `fuzz/tokener_parse_ex_fuzzer.cc` and want to raise an issue regarding it.

**Describe the bug**

As soon as fuzzing begins, it results in a null pointer dereference, causing it to terminate immediately. Here is a snippet of the output indicating the issue:

```
$ python infra/helper.py run_fuzzer json-c tokener_parse_ex_fuzzer
...
AddressSanitizer:DEADLYSIGNAL
=================================================================
==12==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x0000004de051 bp 0x7ffc18a34eb0 sp 0x7ffc18a34e90 T0)
==12==The signal is caused by a READ memory access.
==12==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
    #0 0x4de051 in lh_table_head /src/json-c/linkhash.h:350:12
    #1 0x4de051 in LLVMFuzzerTestOneInput /src/tokener_parse_ex_fuzzer.cc:11:2
...
```

**Steps To Reproduce**
In reference to `tokener_parse_ex_fuzzer.cc`, I have written code that causes a null pointer dereference when handling an empty string. The code is as follows:

```c
#include <stdint.h>

#include <json.h>

int main(int argc, char* argv[])
{
    const char *data1 = "";
    json_tokener *tok = json_tokener_new();
    json_object *obj = json_tokener_parse_ex(tok, data1, -1);

    json_object_object_foreach(obj, key, val) {
        (void)json_object_get_type(val);
        (void)json_object_get_string(val);
    }
    (void)json_object_to_json_string_ext(obj, JSON_C_TO_STRING_PRETTY | JSON_C_TO_STRING_SPACED);

    json_object_put(obj);
    json_tokener_free(tok);
    return 0;
}

```

The above code can be built using the following command:

```
$ clang -fsanitize=address -I/path/to/json-c/install/include reproduce.c -o reproduce -ljson-c
```

Upon execution, the same error occurs as shown below:

```
$ ./reproduce
AddressSanitizer:DEADLYSIGNAL
=================================================================
==137401==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000008 (pc 0x55e2e786d056 bp 0x7fff55ce7840 sp 0x7fff55ce7830 T0)
==137401==The signal is caused by a READ memory access.
==137401==Hint: address points to the zero page.
    #0 0x55e2e786d056 in lh_table_head reproduce.c
    #1 0x55e2e786cf7d in main (/home/hschoe/json-c/reproduce/reproduce+0xdbf7d) (BuildId: e233417fec696a1447f891378646edc9eb85d1c2)
    #2 0x7f7145809d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7f7145809e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #4 0x55e2e77af384 in _start (/home/hschoe/json-c/reproduce/reproduce+0x1e384) (BuildId: e233417fec696a1447f891378646edc9eb85d1c2)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV reproduce.c in lh_table_head
==137401==ABORTING
```

Upon inspecting the code related to the aforementioned error, I discovered that the null pointer dereference arises due to an assumption in the **`json_object_object_foreach(obj, key, val)`** macro. Specifically, the code assumes that the return value of **`json_object_get_object`** cannot be null. This oversight leads to a null pointer dereference error.

As a workaround for this issue, I have implemented a null check for the value returned by **`json_object_get_object`**. The modified `tokener_parse_ex_fuzzer.cc` is provided below:

```c
#include <stdint.h>

#include <json.h>

extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
{
    const char *data1 = reinterpret_cast<const char *>(data);
    json_tokener *tok = json_tokener_new();
    json_object *obj = json_tokener_parse_ex(tok, data1, size);

    struct lh_table *pTable = json_object_get_object(obj);
    if (pTable) {
        json_object_object_foreach(obj, key, val) {
            (void)json_object_get_type(val);
            (void)json_object_get_string(val);
        }
    }
    (void)json_object_to_json_string_ext(obj, JSON_C_TO_STRING_PRETTY | JSON_C_TO_STRING_SPACED);

    json_object_put(obj);
    json_tokener_free(tok);
    return 0;
}
```

If the above code is acceptable, I am willing to make a Pull Request. Additionally, I'm curious to know if there's any interest in adding a new Fuzzing Driver? I have experimented with creating a new Fuzzing Driver and am open to contributing this as well if it aligns with your development goals.

Please let me know your thoughts on this or if there are any specific requirements or guidelines I should follow for contributing to your project in this manner.

**Version and Platform**

- json-c version: [ad8b8af](https://github.com/json-c/json-c/commit/ad8b8afa7d567053b87f2d37ee4a534e13c210c7) (latest commit of master branch)
- OS: Ubuntu 20.04.6 LTS (oss-fuzz-base image)

**Comment by hawicz** [comment]
> Upon inspecting the code related to the aforementioned error, I discovered that the null pointer dereference arises due to an assumption in the json_object_object_foreach(obj, key, val) macro. Specifically, the code assumes that the return value of json_object_get_object cannot be null. This oversight leads to a null pointer dereference error.

This is expected behavior from the library.  Using json_object_object_foreach is only valid on json_object pointers that are of type json_type_object.  Using it with anything else is a programming error on the part of the caller.  The normal way to check for this would be to use something like:

    if (json_object_is_type(obj, json_type_object) {
        json_object_object_foreach(obj, key, val) { ... }
    }
    // else if json_object_is_type(obj, json_type_string) { ... }, etc...
    // other per-type handling, as desired

A PR to do that would be welcome.

If you want to discuss something about a new fuzzing driver (I have no particular opinion about this at the moment), feel free to start a thread on the mailing list.
