### ISSUE TITLE
Random crash in json_tokener_parse

### ISSUE THREAD

**Issue by sunzj** [json-c/json-c#841]
random crash in json_tokener_parse, Error message is：
Abort message: 'Scudo ERROR: invalid chunk state when deallocating address 0x200006f599d8250'

Header:
88bce2b38e08c110565ff4db5bdcca09644e2882

Backtrace is:
json-c/json_object.c:520
json-c/linkhash.c:572
json-c/json_object.c:526
json-c/json_tokener.c:196
json-c/json_tokener.c:230
json_tokener_parse()

**Steps To Reproduce**
 /*
   read data buffer  from socket.
*/

    if (NULL == mTok) {
        mTok = json_tokener_new();
    }
    do {
        mObj = json_tokener_parse_ex(mTok, buffer + offset, strlen(buffer) - offset);
        // printf("Server Recv:%s, %p, %d-%d\n", buffer + offset, obj, len, offset);
        if (mObj) {
            offset += mTok->char_offset;
            objTimeStamp = NULL;
            if (json_object_object_get_ex(mObj, TimeStamp, &objTimeStamp)) {
                time_us = json_object_get_int64(objTimeStamp);
                msg.timestamp = time_us;
            }
            payLoad = NULL;
            if (json_object_object_get_ex(mObj, PayLoadKey, &payLoad)) {
                objPayLoad  = NULL;
                if (payLoad) {
                    char *payLoadStr = strdup(json_object_get_string(payLoad));
                    if (payLoadStr) {
                        /*******************************************************************************************
                          ************************************ crash at here.****************************************
                        ********************************************************************************************/
                        objPayLoad = json_tokener_parse(payLoadStr); 
                        free(payLoadStr);
                        payLoadStr = NULL;
                    }
                }
              if (objPayLoad) {
                    // json_object_object_get(objPayLoad, )
                    json_object_put(objPayLoad);
                    objPayLoad = NULL;
                }
            }
              /*******************************************************************************************
               *******************************some times crash at here.**********************************
               ********************************************************************************************/
            json_object_put(mObj);
            mObj = NULL;
        } else {
            break;
        }
    } while (offset < len);

    if (json_tokener_get_error(mTok) != json_tokener_continue) {
        json_tokener_free(mTok);
        mTok = NULL;
    }

Seams not init t->table[i].k_is_constant when create lh_table_new.
https://github.com/json-c/json-c/blob/master/linkhash.c#L521C6-L521C11

**Comment by hawicz** [comment]
It looks to me like k_is_constant should be initialized just fine, either through the calloc in `lh_table_new()` that allocates `t->table`, or by setting `opts` appropriately in `lh_table_resize()`

I don't see anything obviously wrong with the code you listed either, so this will take some puzzling through to figure out.

**Comment by hawicz** [comment]
I wrapped your code in a function: 
```
json_tokener *mTok = NULL;
void testit(char *buffer)
{
   size_t offset = 0;
   struct json_object *mObj;
   size_t len = strlen(buffer);
   const char *TimeStamp = "TimeStamp";
   struct json_object *objTimeStamp;
   uint64_t time_us;
   struct {
       uint64_t timestamp;
   } msg __attribute__((__unused__));
   struct json_object *payLoad;
   const char *PayLoadKey = "PayLoad";
   struct json_object *objPayLoad;
...your code...
}
```

and tried calling it with a variety of buffer contents, but wasn't able to reproduce a crash, nor did valgrind report any errors.
Do you have a specific input that you can share that reproduces the problem?

**Comment by sunzj** [comment]
Thanks, 

i just add  "t->table[i].k_is_constant = = JSON_C_OBJECT_KEY_IS_CONSTANT;" to https://github.com/json-c/json-c/blob/master/linkhash.c#L521C6-L521C11. 

Try to reproduce the issue and capture the input.

**Comment by sunzj** [comment]
I tried differenct release, the crash was always there, and i did some inverstigation, it may case by the following code.

if (NULL == mTok) {
    mTok = json_tokener_new();
}
do {
    mObj = json_tokener_parse_ex(mTok, buffer + offset, strlen(buffer) - offset);
    // printf("Server Recv:%s, %p, %d-%d\n", buffer + offset, obj, len, offset);
    if (mObj) {
        offset += mTok->char_offset;
        objTimeStamp = NULL;
        if (json_object_object_get_ex(mObj, TimeStamp, &objTimeStamp)) {
            time_us = json_object_get_int64(objTimeStamp);
            msg.timestamp = time_us;
        }
        payLoad = NULL;
        if (json_object_object_get_ex(mObj, PayLoadKey, &payLoad)) {
            objPayLoad  = NULL;
            if (payLoad) {
                char *payLoadStr = strdup(json_object_get_string(payLoad));
                if (payLoadStr) {
                    /*******************************************************************************************
                      ************************************ crash at here.****************************************
                    ********************************************************************************************/
                    objPayLoad = json_tokener_parse(payLoadStr); 
                    free(payLoadStr);
                    payLoadStr = NULL;
                }
            }
          if (objPayLoad) {
                    /**************************************** may case by following code******************************************/
                    /* objPerfCounter is arrylist, objPerfCounter may free when json_object_put(objPmu); 
                        then free again by  json_object_put(objPayLoad); 
                        i don't how to increment the refcount of objPerfCounter, it's arrylist, if  use " json_object_get_array" to get 
                        array_list*, then how to add array_list* to objPmu?
                    */
                    if (json_object_object_get_ex(objPayLoad, PerfCountersKey, &objPerfCounter)) {
                        struct json_object  *objPmu = json_object_new_object();
                        json_object_object_add(objPmu, PerfCountersKey, objPerfCounter);
                        char *perfCounters = strdup(json_object_to_json_string(objPmu));
                        json_object_put(objPmu);
                       // send(perfCounters );
                    }
                json_object_put(objPayLoad);
                objPayLoad = NULL;
            }
        }       
         
          /*******************************************************************************************
           *******************************some times crash at here.**********************************
           ********************************************************************************************/
        json_object_put(mObj);
        mObj = NULL;
    } else {
        break;
    }
} while (offset < len);

if (json_tokener_get_error(mTok) != json_tokener_continue) {
    json_tokener_free(mTok);
    mTok = NULL;
}

**Comment by hawicz** [comment]
You can call `json_object_get(objPerfCounter)` to increment it's refcount just before adding it to objPmu.  The json_object_object_add docs explain the ownership transfer, see
https://json-c.github.io/json-c/json-c-0.17/doc/html/json__object_8h.html#a27bd808a022251059a43f1f6370441cd

**Comment by sunzj** [comment]
> You can call `json_object_get(objPerfCounter)` to increment it's refcount just before adding it to objPmu. The json_object_object_add docs explain the ownership transfer, see https://json-c.github.io/json-c/json-c-0.17/doc/html/json__object_8h.html#a27bd808a022251059a43f1f6370441cd

**Comment by sunzj** [comment]
After adding `json_object_get(objPerfCounter)` , test 12+ hours, can't reproduce the crash.
