### ISSUE TITLE
json_tokener_parse_verbose does not set the error indicator when it fails to allocate the tokener

### ISSUE THREAD

**Issue by bhaible** [json-c/json-c#853]
**Describe the bug**
The function `json_tokener_parse_verbose` is documented to "if it fails return the error in *error". However, it does not do so if there is a memory allocation failure when allocating the tokener.

**Steps To Reproduce**
Compile and run this program `foo.c`:
```
#include <stdlib.h>
#include <unistd.h>
#include <json.h>

void *malloc (size_t n) { return NULL; }
void *calloc (size_t n, size_t s) { return NULL; }

int main ()
{
  write (1, "before\n", 7);
  enum json_tokener_error jerrno = -1;
  struct json_object *j = json_tokener_parse_verbose ("{}", &jerrno);
  char message[] = "after: j == NULL, jerrno == -1\n";
  message[9] = (j != NULL ? '!' : '=');
  message[25] = (jerrno != -1 ? '!' : '=');
  write (1, message, 31);
  return jerrno;
}
```

```
$ gcc -Wall -I/usr/include/json-c foo.c /usr/lib/x86_64-linux-gnu/libjson-c.a 
$ ./a.out 
before
after: j == NULL, jerrno == -1
```

As you can see, `jerrno` remained unchanged although `json_tokener_parse_verbose` returned NULL.

**Version and Platform**
- json-c version: 0.15
- OS: Ubuntu 22.04
- Custom cmake/build flags, if any

**Comment by bhaible** [comment]
Also reproduced with json-c version 0.17 (built from source).

**Comment by hawicz** [comment]
dup of #854

**Comment by bhaible** [comment]
Thanks for the fix. I confirm it's fixed.
