### ISSUE TITLE
Using libjson-c.so or compiling from source seg faults on json_tokener_parse_ex in alpine docker container

### ISSUE THREAD

**Issue by yogch** [json-c/json-c#856]
Running the below application causes a segmentation fault on `alpine docker` container.

This code:
```
#include "json-c/json.h"

int main() {
        enum json_tokener_error jerror;
        const char* str = "{}";
        json_object *jobj = json_tokener_parse_verbose(str, &jerror);
        return 0;
}
```

Compiling in `ubuntu` or inside the `alpine docker` container and running causes a seg fault.  
Inside the `alpine docker` container, this sample application links to either a lib comes from `apk add` or by compiling the source.

Docker contains:
```
FROM node:lts-alpine3.19
...
RUN apk add --no-cache bash curl libc6-compat
```
You may add `apk add json-c-dev` and `apk add json-c`, or compile `libjson-c` from sources.

App compilation:
```
gcc -g json.c -o json.out -ljson-c
```

Run + segfault:
```
# ./json.out
Segmentation fault (core dumped)
```

**Note: the application gets the `segfault` due to a call to `duplocale()` in `json_tokener_parse_ex`**

**Version and Platform**
- json-c version: [json-c-0.17-20230812](https://github.com/json-c/json-c/releases/tag/json-c-0.17-20230812)
- OS: Alpine docker container 3.19

**Comment by hawicz** [comment]
Works fine when I try it (including through valgrind, once I add a `json_object_put(jobj)` near the end of main()), using json-c-dev inside the alpine3.19 container, however I'm running on ARM (aarch64) so maybe there's some platform dependent bug.

How do you know duplocale is to blame?  Do you have a stack trace?

**Comment by yogch** [comment]
I couldn't print a valuable stack trace. I'm not sure why. I verified I have symbols, but the stack trace was without symbols.

I know because I debugged it with prints and eventually saw it crashes there.

I'm on x86 and actually used node:lts-alpine3.19

**Comment by hawicz** [comment]
I tried this on a x86_64 machine (Windows, AMD Ryzen cpu, docker desktop) , using both the json-c package, and compiling from source, and in all cases it works fine.  
So, what's different about your environment?  At the very least the steps you listed above are incomplete, I needed to also install gcc and libc-dev to compile your sample code.

Extra packages installed with: `apk add --no-cache libc-dev gcc gdb cmake make git`

**Comment by yogch** [comment]
I don't know what to say.
I now cannot reproduce as well with this sample code, only by using my more complex form.
But this sample code did cause a seg fault :/

I'm truly sorry,
Thank you for your time 🙏.
I'll see if I can somehow reproduce it again.
