### ISSUE TITLE
Assertion usage

### ISSUE THREAD

**Issue by Darnethal0z** [json-c/json-c#865]
During the usage of the library, i have naturally encountered several assertions errors, mainly with `json_object_put()`.

Is there any reasons why assertions are used rather than any other statements ? I know that they can help to catch eventual programming errors, but can some uses of `assert()` in the library be replaced by something less abrupt ?

For a particular instance, when i look at the `json_object_put()` function definition, i can see those lines (json_object.c, 272) : 

```
int json_object_put(struct json_object *jso)
{
	if (!jso)
		return 0;

	/* Avoid invalid free and crash explicitly instead of (silently)
	 * segfaulting.
	 */
	assert(jso->_ref_count > 0);

	[...]
}
```

I understand that to prevent invalid free we must check if the refcount is superior to zero, but why not return an error code rather than using `assert()` ? With a simple condition like : 

```
int json_object_put(struct json_object *jso)
{
	if (!jso)
		return 0;

	/* Avoid invalid free and crash explicitly instead of (silently)
	 * segfaulting.
	 */
	if (jso->_ref_count == 0)
		return SOME_ERROR_CODE;

	[...]
}
```

I've checked for any caveats in the modified library with a modified test, and everything went fine.

Maybe there is some design matters behind it due to the nature of the library, i would like to learn more about it.

Thanks you in advance !

**Comment by hawicz** [comment]
A ref count that ends up unexpectedly to zero is evidence that a serious coding error has been made, often in the form of memory corruption that wrote garbage over the object or perhaps trying to use already freed memory.  In these situations it's hard enough for a person debugging interactively to make sense of what happened, and pre-written error handling has very little chance of being able to safely do anything sensible.

If you really wish to disable the asserts you can build json-c with something like `export CFLAGS="-DNDEBUG=1"`, but I would not recommend it.

**Comment by Darnethal0z** [comment]
Ok, thanks a lot !
