### ISSUE TITLE
I meet compile error in harmony  

### ISSUE THREAD

**Issue by Shian-Wang** [json-c/json-c#868]
**Describe the bug**
Does everybody compile arm64-v8a static lib for harmony of huawei?
I meet error in make ad below message

clang: error: argument unused during compilation: '--gcc-[  1%] Building C object CMakeFiles/json-c.dir/arraylist.c.obj
[  2%] Building C object CMakeFiles/json-c.dir/debug.c.obj
clang: error: argument unused during compilation: '--gcc-toolchain=/Users/Shian_Wang/Library/Huawei/Sdk/openharmony/9/native/llvm' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '--gcc-toolchain=/Users/Shian_Wang/Library/Huawei/Sdk/openharmony/9/native/llvm' [-Werror,-Wunused-command-line-argument]
make[2]: *** [CMakeFiles/json-c.dir/debug.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/json-c.dir/arraylist.c.obj] Error 1
make[1]: *** [CMakeFiles/json-c.dir/all] Error 2

**Version and Platform**
- json-c version: 0.17
- OS: macosx 14.5

**Comment by hawicz** [comment]
Can you show what commands you ran to end up with that error, in particular how you ran cmake?

My guess is that something like what is mentioned at https://lists.llvm.org/pipermail/llvm-dev/2020-September/145084.html may be needed (i.e. specify a whole slew of `-DCMAKE_AR=...`, -DCMAKE_C_FLAGS=...`, etc... options to cmake), but I'm not particular familiar with setting up cross-compiles, and not at all familiar with doing so for OpenHarmony.

**Comment by Shian-Wang** [comment]
this my command and setting

CUR_DIR=`pwd`
HOME=`echo $HOME`


export OHOS_NATIVE_HOME="/Users/steve/Library/Huawei/Sdk/openharmony/9/native"
export PATH="${OHOS_NATIVE_HOME}/llvm/bin:$PATH"

LIBS_DIR=$CUR_DIR/libs/openssl
BUILD_DIR=$CUR_DIR/buildlib

THE_ARCH="arm64-v8a"

BASE_FLAGS="--sysroot=${OHOS_NATIVE_HOME}/sysroot -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -fPIC"

case "$THE_ARCH" in
  armv7a|armeabi-v7a)
    OHOS_ARCH="armeabi-v7a"
    OHOS_TARGET="arm-linux-ohos"
    OPENSSL_ARCH="linux-armv4"
    FF_EXTRA_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS -march=armv7a"
    FF_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS -march=armv7a"
    ;;
  armv8|armv8a|aarch64|arm64|arm64-v8a)
    OHOS_ARCH="arm64-v8a"
    OHOS_TARGET="aarch64-linux-ohos"
    OPENSSL_ARCH="linux-aarch64"
    FF_EXTRA_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS"
    FF_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS"
    DESTDIR="$BUILD_DIR/openssl-arm64-v8a"
    ;;
  x86_64|x64)
    OHOS_ARCH="x86_64"
    OHOS_TARGET="x86_64-linux-ohos"
    OPENSSL_ARCH="linux-x86_64"
    FF_EXTRA_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS"
    FF_CFLAGS="--target=$OHOS_TARGET $BASE_FLAGS"
    ;;
  *)
  echo "ERROR: Unknown architecture $1"
  [ "$0" = "$BASH_SOURCE" ] && exit 1 || return 1
  ;;
esac

BUILD_CMAKE=$OHOS_NATIVE_HOME/build/cmake
TOOLCHAIN=$OHOS_NATIVE_HOME/llvm

SYSROOT=$OHOS_NATIVE_HOME/sysroot
CC=$TOOLCHAIN/bin/clang 
CXX=$TOOLCHAIN/bin/clang++
LD=$TOOLCHAIN/bin/ld-lld
AS=$TOOLCHAIN/bin/llvm-as
AR=$TOOLCHAIN/bin/llvm-ar
NM=$TOOLCHAIN/bin/llvm-nm
RANLIB=$TOOLCHAIN/bin/llvm-ranlib
STRIP=$TOOLCHAIN/bin/llvm-strip

#!/bin/bash

export CC="$CC"
export CXX="$CXX"
export CXXFLAGS=$FF_EXTRA_CFLAGS
export CFLAGS=$FF_CFLAGS
export AR="$AR"
export LD="$LD"
export AS="$AS"
export NM="$NM"
export RANLIB="$RANLIB"
export STRIP="$STRIP"
export LDFLAGS="--rtlib=compiler-rt -fuse-ld=lld"

cmake --toolchain=${BUILD_CMAKE}/ohos.toolchain.cmake \
    -DOHOS_ARCH=${OHOS_ARCH} \
    -DBUILD_SHARED_LIBS=OFF \
    -DCMAKE_BUILD_TYPE=MinSizeRel \
    -DCMAKE_INSTALL_PREFIX=$PWD/buildlib/harmony-arm64-v8a/ \
    -DENABLE_THREADING=true 

make clean
make -j4

Error Msg:
clang: error: argument unused during compilation: '--gcc-[ 1%] Building C object CMakeFiles/json-c.dir/arraylist.c.obj
[ 2%] Building C object CMakeFiles/json-c.dir/debug.c.obj
clang: error: argument unused during compilation: '--gcc-toolchain=/Users/Shian_Wang/Library/Huawei/Sdk/openharmony/9/native/llvm' [-Werror,-Wunused-command-line-argument]
clang: error: argument unused during compilation: '--gcc-toolchain=/Users/Shian_Wang/Library/Huawei/Sdk/openharmony/9/native/llvm' [-Werror,-Wunused-command-line-argument]
make[2]: *** [CMakeFiles/json-c.dir/debug.c.obj] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/json-c.dir/arraylist.c.obj] Error 1
make[1]: *** [CMakeFiles/json-c.dir/all] Error 2

**Comment by hawicz** [comment]
Just guessing here, but maybe try removing `--target=$OHOS_TARGET` from FF_CFLAGS and FF_EXTRA_CFLAGS, and instead pass ` -DCMAKE_C_COMPILER_TARGET="$OHOS_TARGET"` to cmake?

Also, is the part starting from `#!/bin/bash` a separate script?  If so, all those export lines are completely useless: either $CC, $CXX, etc... are already exported variables, in which case those are no-op, or the script won't see the un-exported variables you set before you run it and you're just exporting variables with an empty string.
