### ISSUE TITLE
At a high level how are jsons parses? Are they terminated by the new line?

### ISSUE THREAD

**Issue by Redhawk18** [json-c/json-c#869]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/g/json-c

**Describe the bug**
Hi, I'm communicating with a open sourced monero pool that uses this library. I ran into a bug the other day where I'm required to add a new line to the end of my json to get the server to process my request. I wanted to ask if this is normal? My first thought was it was my library that was wrong so I made an issue here

https://github.com/serde-rs/json/issues/1163#issuecomment-2264041479

Since it's not part of the spec I wanted to ask where this problem would come from.

**Comment by hawicz** [comment]
Note: for general questions and comments, please use the forums at:
https://groups.google.com/g/json-c

The json-c library does not require newlines, but reading input a line at a time is something that services may do themselves before passing input to the parsing functions.
